---
title: "BMI"
output:
  html_document: default
---

```{r include=FALSE}
library(knitr)
library(kableExtra)
library(lubridate)
library(tidyverse)
library(dplyr)
purl("creating_datasets.Rmd", output = "creating_datasets.R", documentation = 2)
source(file="creating_datasets.R")
```


---


```{r include=FALSE}
#BMI by year
BMIbyyear<-fulluniquefams %>%
  group_by(year(Visitdate)) %>% 
  filter(!is.na(BMI.x)) %>% 
  dplyr::summarize(total_BMI_assessments=n())

#BMI normal by year
BMInormbyyear<-fulluniquefams %>%
  group_by(year(Visitdate)) %>% 
  filter(!is.na(BMI.x) & normal==TRUE) %>% 
  dplyr::summarize(BMI_normal=n())

#RX for normal by year
RXfornorm<-fulluniquefams %>%
  group_by(year(Visitdate)) %>% 
  filter(!is.na(BMI.x) & normal==TRUE) %>% 
   filter(FreshRX=="FreshRX") %>% 
  dplyr::summarize(RX_for_normal=n())

normaltable<-full_join(BMInormbyyear,RXfornorm)

BMIRXtable<-full_join(BMIbyyear,normaltable)

#BMI overweight/obese by year
BMIoverbyyear<-fulluniquefams %>%
  group_by(year(Visitdate)) %>% 
  filter(!is.na(BMI.x) & over==TRUE) %>% 
  dplyr::summarize(BMI_over=n())

#RX for overweight/obese by year
RXforover<-fulluniquefams %>%
  group_by(year(Visitdate)) %>% 
  filter(!is.na(BMI.x) & over==TRUE) %>% 
   filter(FreshRX=="FreshRX") %>% 
  dplyr::summarize(RX_for_over=n())

overtable<-full_join(BMIoverbyyear,RXforover)
BMIRXtable2<-full_join(BMIRXtable,overtable)

#Overweight/obese rate by year
BMIbyyeartb<-suppressMessages(full_join(BMIbyyear,BMIoverbyyear))
BMIbyyearrate<-BMIbyyeartb %>% 
  mutate(`Overweight/Obese_rate%`=round((BMI_over/total_BMI_assessments)*100))


#RXforBMItable totals
m<-sum(BMIRXtable2$total_BMI_assessments)
n<-sum(BMIRXtable2$BMI_normal)
o<-sum(na.omit(BMIRXtable2$RX_for_normal))
p<-sum(BMIRXtable2$BMI_over)
q<-sum(na.omit(BMIRXtable2$RX_for_over))

RXforBMItabletotals<-c("totals",m,n,o,p,q)
BMIRXtable3<-rbind(BMIRXtable2,RXforBMItabletotals)
```

```{r echo=FALSE}
BMIbyyearrate %>% 
  knitr::kable("html", caption="Overweight/Obese rate by year (2012-17)") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")
```


```{r echo=FALSE}
BMIRXtable3 %>% 
  knitr::kable("html", caption="RX rate (%) by BMI status (2012-17)") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")
```


```{r include=FALSE}
BMIRXtable4<-BMIRXtable2[4:6,] %>% 
  mutate(RX_for_normal_rate=round((RX_for_normal/BMI_normal)*100)) %>% 
  mutate(RX_for_over_rate=round((RX_for_over/BMI_over)*100))

RXbyBMIrate<-BMIRXtable4 %>% 
  select('year(Visitdate)',RX_for_normal_rate,RX_for_over_rate)
```

```{r echo=FALSE}
 RXbyBMIrate %>% 
  knitr::kable("html", caption="RX rate (%) by BMI status (2015-17)") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")
```



```{r include=FALSE}
normalredemps<-fulluniquefams %>% 
  filter(Status=="Complete") %>% 
  filter(normal==TRUE) %>% 
  summarize(redemps=n())

normalnonredemps<-fulluniquefams %>% 
  filter(Status!="Complete") %>% 
  filter(normal==TRUE) %>% 
  summarize(non_redemps=n())

normals<-cbind(normalredemps,normalnonredemps)

overredemps<-fulluniquefams %>% 
  filter(Status=="Complete") %>% 
  filter(over==TRUE) %>% 
  summarize(redemps=n())

overnonredemps<-fulluniquefams %>% 
  filter(Status!="Complete") %>% 
  filter(over==TRUE) %>% 
  summarize(non_redemps=n())

overs<-cbind(overredemps,overnonredemps)

tbyt<-rbind(normals,overs)

categories<-c("normal weight","overweight/obese")

bmitable<-cbind(categories, tbyt)
```


```{r echo=FALSE}
bmitable %>% 
  knitr::kable("html", caption="Redemptions by BMI status") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")
```



```{r echo=FALSE, eval=TRUE}
BMIredemps<-c(14,6)
BMInonredemps<-c(32,5)
redempbyBMI<-cbind(BMIredemps,BMInonredemps)
redempbyBMI<-as.data.frame(redempbyBMI)
row.names(redempbyBMI)<-c("normal weight","overweight/obese")
chisq.test(redempbyBMI,correct=FALSE)
fisher.test(redempbyBMI)
```