---
title: "BMIN503/EPID600 Project"
author: "Zheyuan(Aria) Huang"
output: 
  html_document:
    theme: paper
    highlight: tango
---
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 400)
```  
***
Use this template to complete your project throughout the course. Your Final Project presentation will be based on the contents of this document. Replace the title/name above and text below with your own, but keep the headers.

### Overview
Give a brief a description of your project and its goal(s), what data you are using to complete it, and what three faculty/staff in different fields you have spoken to about your project with a brief summary of what you learned from each person. Include a link to your final project GitHub repository.

The project aims to design protein circuits that can sense clusters of diseased proteins to cause targeted cell death. The data analyzed here are collected based on cell apoptosis after cells being transfected with different apoplectic constructs at various time points. The goal of this project is to determine the optimal protein circuit design to engineer cell death in cancerous cells. 


### Introduction 
Describe the problem addressed, its significance, and some background to motivate the problem.

Explain why your problem is interdisciplinary, what fields can contribute to its understanding, and incorporate background related to what you learned from meeting with faculty/staff.

The goal of the project is to engineer protein clusters that could lead to controlled apoptosis thus creating a therapeutic tool for cancer treatment. The problem of interest here seeks the expertise from protein engineering, cell signaling, cancer biology, and quantitative analysis. By combining knowledge from these fields, we will be able to deepen our knowledge on protein clustering as an emergent form of cancer therapy.  
From my conversations with the faculties, I realized that the dataset might seem simple from a mathematical perspective, but to interpret it correctly and drawing the correlation between different techniques with phenotype will be challenging. It will be crucial to put any finding into the context and evaluate the results by biological and technical principles. 

### Methods
Source data: Split TEV Cry2.csv
Variables: 
- Time: time point when the cells were imaged 
  t = 0/2/6/8/12 hrs 

- Plasmid: 
  split TEV-PC3
  TEV trunc
  TEV trunc TEVcsQ
  TEV trunc TEVcsL
  TEV trunc TEVcsM
  Cry2-GFP
  
- Fluorescent Channels: 
  mCherry
  mCherry+DAPI
  mCherry+FITC
  mCherry+FITC+DAPI
  
- Treatments: 
  base 
  stimulated (stimulated with FITC)
  
- Experiment setup: 
  Cells stimulated with FITC are hypothesized to express the transfected constructs which would lead to cell apoptosis. 
  mCherry - apoptosis circuit is activated 
  DAPI: cell nuclei
  FITC: cry2 - to stimulate the death circuit to start 
  
- Using the time point fluorescence data collected on cells transfected with different constructs, I plan to analyze 
  1. fluorescence progression throughout the time course for each construct  
  2. cell count for fluorescence expressing cells and dying cells at each time point in each channel 
  3. expression difference between stimulated and base cells

### Load data 
finaldata <- read.csv(
  file = "Split TEV Cry2.csv",
  header = TRUE,
  sep = ",",
  dec = "."
)
# rename and clean data here if needed 

### plot time points data 
# seperate basal and stimulated data
basaldata<-filter(finaldata,treatments=base)
sdata<-filter(finaldata,treatments=stimiulated)
# plot seperately
library("ggplot2")
ggplot(basaldata, aes(time, plasmid)) +
           geom_point(na.rm=TRUE)+
           ggtitle("basal death %") +
           xlab("groups") + ylab("basal expression death % ")
ggplot(sdata, aes(time, plasmid)) +
           geom_point(na.rm=TRUE)+
           ggtitle("stimulated death %") +
           xlab("groups") + ylab("stimulated expression death % ")
           

### dying and expression comparison at each time point 
# seperate data by time point 
data0<-filter(finaldata,time=0)
data2<-filter(finaldata,time=2)
data6<-filter(finaldata,time=6)
data8<-filter(finaldata,time=8)
data12<-filter(finaldata,time=12)

# t test on expression
# for t0
t.test(x = data0$mCherry+DAPI, y=data0$mCherry+FITC+DAPI,
       alternative = c("two.sided", "less", "greater"),
       mu = 0, paired = FALSE, var.equal = FALSE,
       conf.level = 0.95, …)
# repeat for the rest time points 



### Results
Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

# figure 1: basal death %
# y-axis: basal expression death % 
# x-axis: construct groups and pbs (control)

# figure 2: stimulated death %
# y-axis: stimulated expression death % 
# x-axis: construct groups and pbs (control)

# also inlcude normalized curve on each plot (normalize to t0)

# statistical results
#---------------
