#Clear existing data and graphics
#rm(list=ls())
graphics.off()
#Load Hmisc library
library(Hmisc)
#Read Data
data=read.csv('ChronicConditionSpec_DATA_2019-10-02_1538.csv')

#Set factors
source('factors.r')

#Set Levels
source('levels.r')

levels(data$act_nutri_kids11.factor)=c(" I did not eat fruit during the past 7 days"," 1 to 3 times during the past 7 days"," 4 to 6 times during the past 7 days "," 1 time per day"," 2 times per day2 vez por día"," 3 times per day3 vez por día"," 4 or more times per day4 veces por día o mas")
levels(data$act_nutri_kids12.factor)=c(" I did not eat green salad during the past 7 days"," 1 to 3 times during the past 7 days  "," 4 to 6 times during the past 7 days "," 1 time per day"," 2 times per day"," 3 times per day"," 4 or more times per day")
levels(data$act_nutri_kids13.factor)=c(" I did not eat potatoes during the past 7 days"," 1 to 3 times during the past 7 days  "," 4 to 6 times during the past 7 days "," 1 time per day"," 2 times per day"," 3 times per day"," 4 or more times per day")
levels(data$act_nutri_kids14.factor)=c(" I did not eat carrots during the past 7 days"," 1 to 3 times during the past 7 days  "," 4 to 6 times during the past 7 days "," 1 time per day"," 2 times per day"," 3 times per day"," 4 or more times per day")
levels(data$act_nutri_kids15.factor)=c(" I did not eat other vegetables during the past 7 days"," 1 to 3 times during the past 7 days  "," 4 to 6 times during the past 7 days "," 1 time per day"," 2 times per day"," 3 times per day"," 4 or more times per day")
levels(data$act_nutri_kids16.factor)=c(" I did not eat pizza during the past 7 days"," 1 to 3 times during the past 7 days  "," 4 to 6 times during the past 7 days "," 1 time per day"," 2 times per day"," 3 times per day"," 4 or more times per day")
levels(data$act_nutri_kids17.factor)=c(" I did not drink 100% fruit juice during the past 7 days"," 1 to 3 times during the past 7 days  "," 4 to 6 times during the past 7 days "," 1 time per day"," 2 times per day"," 3 times per day"," 4 or more times per day")
levels(data$act_nutri_kids18.factor)=c(" I did not drink soda or pop during the past 7 days"," 1 to 3 times during the past 7 days  "," 4 to 6 times during the past 7 days "," 1 time per day"," 2 times per day"," 3 times per day"," 4 or more times per day")
levels(data$act_nutri_kids19.factor)=c(" I did not drink sugar-sweetened beverages  during the past 7 days"," 1 to 3 times during the past 7 days  "," 4 to 6 times during the past 7 days "," 1 time per day"," 2 times per day"," 3 times per day"," 4 or more times per day")
levels(data$act_nutri_kids20.factor)=c(" I did not drink water during the past 7 daysNo he bebido agua "," 1 to 3 times during the past 7 days  "," 4 to 6 times during the past 7 days "," 1 time per day"," 2 times per day"," 3 times per day"," 4 or more times per day")
levels(data$act_nutri_kids21.factor)=c(" None"," 1/2 cup or less"," 1/2 cup to 1 cup"," 1 to 2 cups"," 2 to 3 cups"," 3 to 4 cups"," 4 or more cups")
levels(data$act_nutri_kids22.factor)=c(" None"," 1/2 cup or less"," 1/2 cup to 1 cup"," 1 to 2 cups"," 2 to 3 cups"," 3 to 4 cups"," 4 or more cups")
levels(data$act_nutri_kids23.factor)=c(" 0 days"," 1 day"," 2 days "," 3 days "," 4 days "," 5 days "," 6 days "," 7 days ")
levels(data$act_nutri_kids24.factor)=c(" 0 days"," 1 day"," 2 days "," 3 days "," 4 days "," 5 days "," 6 days "," 7 days ")
levels(data$act_nutri_kids25.factor)=c(" 0 days"," 1 day"," 2 days "," 3 days "," 4 days "," 5 days "," 6 days "," 7 days ")
levels(data$act_nutri_kids26.factor)=c(" Never"," Rarely"," Sometimes"," Most of the time"," Always")
levels(data$act_nutri_kids27.factor)=c(" Never"," Rarely"," Sometimes"," Most of the time"," Always")
levels(data$physical_activity_nutrition_patient_complete.factor)=c("Incomplete","Unverified","Complete")
levels(data$weight_01.factor)=c("Not True At All 1No es cierto en lo absoluto","2","3","Somewhat TrueAlgo Cierto4","5","6","Very TrueMuy Cierto7")
levels(data$weight_02.factor)=c("Not True At All 1No es cierto en lo absoluto","2","3","Somewhat TrueAlgo Cierto4","5","6","Very TrueMuy Cierto7")
levels(data$weight_03.factor)=c("Not True At All 1No es cierto en lo absoluto","2","3","Somewhat TrueAlgo Cierto4","5","6","Very TrueMuy Cierto7")
levels(data$weight_04.factor)=c("Not True At All 1No es cierto en lo absoluto","2","3","Somewhat TrueAlgo Cierto4","5","6","Very TrueMuy Cierto7")
levels(data$weight_05.factor)=c("Not True At All 1No es cierto en lo absoluto","2","3","Somewhat TrueAlgo Cierto4","5","6","Very TrueMuy Cierto7")
levels(data$weight_06.factor)=c("Not True At All 1No es cierto en lo absoluto","2","3","Somewhat TrueAlgo Cierto4","5","6","Very TrueMuy Cierto7")
levels(data$weight_07.factor)=c("Not True At All 1No es cierto en lo absoluto","2","3","Somewhat TrueAlgo Cierto4","5","6","Very TrueMuy Cierto7")
levels(data$weight_08.factor)=c("Not True At All 1No es cierto en lo absoluto","2","3","Somewhat TrueAlgo Cierto4","5","6","Very TrueMuy Cierto7")
levels(data$weight_09.factor)=c("Not True At AllNo es cierto en lo absoluto 1","2","3","Somewhat TrueAlgo Cierto4","5","6","Very TrueMuy Cierto7")
levels(data$weight_10.factor)=c("Not True At AllNo es cierto en lo absoluto 1","2","3","Somewhat TrueAlgo Cierto4","5","6","Very TrueMuy Cierto7")
levels(data$weight_11.factor)=c("Not True At AllNo es cierto en lo absoluto 1","2","3","Somewhat TrueAlgo Cierto4","5","6","Very TrueMuy Cierto7")
levels(data$weight_12.factor)=c("Not True At AllNo es cierto en lo absoluto 1","2","3","Somewhat TrueAlgo Cierto4","5","6","Very TrueMuy Cierto7")
levels(data$weight_13.factor)=c("Not True At AllNo es cierto en lo absoluto 1","2","3","Somewhat TrueAlgo Cierto4","5","6","Very TrueMuy Cierto7")
levels(data$weight_14.factor)=c("Not True At AllNo es cierto en lo absoluto 1","2","3","Somewhat TrueAlgo Cierto4","5","6","Very TrueMuy Cierto7")
levels(data$weight_15.factor)=c("Not True At AllNo es cierto en lo absoluto 1","2","3","Somewhat TrueAlgo Cierto4","5","6","Very TrueMuy Cierto7")
levels(data$weight_16.factor)=c("Not True At AllNo es cierto en lo absoluto 1","2","3","Somewhat TrueAlgo Cierto4","5","6","Very TrueMuy Cierto7")
levels(data$has_asthma.factor)=c("YesSí ","No")
levels(data$weight_patient_complete.factor)=c("Incomplete","Unverified","Complete")
levels(data$asthma01___0.factor)=c("Unchecked","Checked")
levels(data$asthma01___1.factor)=c("Unchecked","Checked")
levels(data$asthma01___11.factor)=c("Unchecked","Checked")
levels(data$asthma01___00.factor)=c("Unchecked","Checked")
levels(data$asthma01___000.factor)=c("Unchecked","Checked")
levels(data$asthma01___111.factor)=c("Unchecked","Checked")
levels(data$asthma01___0000.factor)=c("Unchecked","Checked")
levels(data$asthma01___00000.factor)=c("Unchecked","Checked")
levels(data$asthma01___000000.factor)=c("Unchecked","Checked")
levels(data$asthma01___1111.factor)=c("Unchecked","Checked")
levels(data$asthma02.factor)=c(" True"," False")
levels(data$asthma03.factor)=c(" True"," False")
levels(data$asthma04.factor)=c(" True"," False")
levels(data$asthma05.factor)=c(" True"," False")
levels(data$asthma07.factor)=c(" True"," False")
levels(data$asthma08.factor)=c(" True"," False")
levels(data$asthma09.factor)=c(" True"," False")
levels(data$asthma10___0.factor)=c("Unchecked","Checked")
levels(data$asthma10___00.factor)=c("Unchecked","Checked")
levels(data$asthma10___1.factor)=c("Unchecked","Checked")
levels(data$asthma10___000.factor)=c("Unchecked","Checked")
levels(data$asthma10___0000.factor)=c("Unchecked","Checked")
levels(data$asthma10___11.factor)=c("Unchecked","Checked")
levels(data$asthma10___00000.factor)=c("Unchecked","Checked")
levels(data$asthma10___000000.factor)=c("Unchecked","Checked")
levels(data$asthma10___0000000.factor)=c("Unchecked","Checked")
levels(data$asthma10___00000000.factor)=c("Unchecked","Checked")
levels(data$asthma10___111.factor)=c("Unchecked","Checked")
levels(data$asthma10___000000000.factor)=c("Unchecked","Checked")
levels(data$asthma10___1111.factor)=c("Unchecked","Checked")
levels(data$asthma10___0000000000.factor)=c("Unchecked","Checked")
levels(data$asthma10___00000000000.factor)=c("Unchecked","Checked")
levels(data$asthma10___11111.factor)=c("Unchecked","Checked")
levels(data$asthma10___000000000000.factor)=c("Unchecked","Checked")
levels(data$asthma10___0000000000000.factor)=c("Unchecked","Checked")
levels(data$asthma10___000000000000000.factor)=c("Unchecked","Checked")
levels(data$asthma10___0000000000000000.factor)=c("Unchecked","Checked")
levels(data$asthma10___111111.factor)=c("Unchecked","Checked")
levels(data$asthma11___1.factor)=c("Unchecked","Checked")
levels(data$asthma11___11.factor)=c("Unchecked","Checked")
levels(data$asthma11___0.factor)=c("Unchecked","Checked")
levels(data$asthma11___111.factor)=c("Unchecked","Checked")
levels(data$asthma11___00.factor)=c("Unchecked","Checked")
levels(data$asthma11___000.factor)=c("Unchecked","Checked")
levels(data$asthma11___0000.factor)=c("Unchecked","Checked")
levels(data$asthma11___00000.factor)=c("Unchecked","Checked")
levels(data$asthma11___000000.factor)=c("Unchecked","Checked")
levels(data$asthma11___0000000.factor)=c("Unchecked","Checked")
levels(data$asthma11___00000000.factor)=c("Unchecked","Checked")
levels(data$asthma11___000000000.factor)=c("Unchecked","Checked")
levels(data$asthma11___0000000000.factor)=c("Unchecked","Checked")
levels(data$asthma11___00000000000.factor)=c("Unchecked","Checked")
levels(data$asthma11___1111.factor)=c("Unchecked","Checked")
levels(data$asthma11___000000000000.factor)=c("Unchecked","Checked")
levels(data$asthma11___0000000000000.factor)=c("Unchecked","Checked")
levels(data$asthma11___00000000000000.factor)=c("Unchecked","Checked")
levels(data$asthma11___000000000000000.factor)=c("Unchecked","Checked")
levels(data$asthma11___11111.factor)=c("Unchecked","Checked")
levels(data$asthma11___0000000000000000.factor)=c("Unchecked","Checked")
levels(data$asthma12.factor)=c(" True"," False")
levels(data$asthma13.factor)=c(" True"," False")
levels(data$asthma14.factor)=c(" True"," False")
levels(data$asthma15.factor)=c(" True"," False")
levels(data$asthma16.factor)=c(" True"," False")
levels(data$asthma17.factor)=c(" True"," False")
levels(data$asthma18.factor)=c(" True"," False")
levels(data$asthma19.factor)=c(" True"," False")
levels(data$asthma20.factor)=c(" True"," False")
levels(data$asthma22.factor)=c(" True"," False")
levels(data$asthma24.factor)=c(" True"," False")
levels(data$asthma25.factor)=c(" True"," False")
levels(data$asthma26.factor)=c(" True"," False")
levels(data$asthma27.factor)=c(" True"," False")
levels(data$asthma28.factor)=c(" True"," False")
levels(data$asthma29.factor)=c(" True"," False")
levels(data$asthma30.factor)=c(" True"," False")
levels(data$asthma31.factor)=c(" True"," False")
levels(data$asthma_knowledge_patient_complete.factor)=c("Incomplete","Unverified","Complete")
levels(data$dem_parent_sex.factor)=c("FemaleFemenino","MaleMasculino")
levels(data$dem_parent_ethnicity.factor)=c("Black, Non-HispanicNegro o Afroamericano, no Hispano","white, Non-HispanicBlanco, no Hispano","Asian or Pacific IslanderAsiático o Asiático-americano, o de las Islas del Pacífico","Native American or Alaskan NativeIndio americano o nativo Americano, o nativo de Alaska","HispanicHispano","OtherOtro")
levels(data$dem_parent_language_pref.factor)=c("EnglishInglés","CreoleCreole Haitiano","SpanishEspañol","OtherOtro")
levels(data$dem_parent_school.factor)=c("Never attended school fue a la escuela","1st to 8th grade (elementary)1 a 8 grado (primaria)","9th to 11th grade (some high school)9 al 11 grado (educación secundaria incompleta)","12th grade or GED (high school graduate)12 grado o GED (graduado de la escuela secundaria)","1 to 3 years college (some college or technical school)1 a 3 años de universidad (algunos años de universidad o escuela técnica)","4 or more years college (college graduate)4 o más años de universidad (graduado de la universidad)","Graduate training or professional degreeFormación de postgrado o título profesional")
levels(data$dem_parent_nationality.factor)=c("United StatesEstados Unidos","CubaCuba","MexicoMéxico","HaitiHaití","OtherOtros")
levels(data$dem_parent_us.factor)=c("Less than 1 yearMenos de 1 año","1-3 years1 - 3 años","4-6 years4 - 6 años","7-9 years7 - 9 años","10-12 years10 - 12 años","13-15 years13 - 15 años","More than 15 yearsMás de 15 años")
levels(data$dem_kid_nationality.factor)=c("United StatesEstados Unidos","CubaCuba","MexicoMéxico","HaitiHaití","OtherOtros")
levels(data$dem_kid_us.factor)=c("Less than 1 yearMenos de 1 año","1-3 years1 - 3 años","4-6 years4 - 6 años","7-9 years7 - 9 años","10-12 years10 - 12 años","13-15 years13 - 15 años","More than 15 yearsMás de 15 años")
levels(data$dem_parent_job.factor)=c("Full TimeTiempo completo","Part TimeTiempo parcial","RetiredJubilado/Retirado","UnemployedDesempleado")
levels(data$dem_parent_income.factor)=c("Below $10,000Por debajo de $ 10,000","$10,000 - $24,999$10,000 - $24,999","$25,000 - $39,999$25,000 - $39,999","$40,000 - $54,999$40,000 - $54,999","$55,000 - $69,999$55,000 - $69,999","$70,000 - $84,000$70,000 - $84,000","Over $85,000Mas de $85,000")
levels(data$dem_parent_marital.factor)=c("SingleSoltero","MarriedCasado","SeparatedSeparado","DivorcedDivorciado","WidowedViudo")
levels(data$dem_parent_habitants.factor)=c("2 people2 personas","3 people3 personas","4 people4 personas","5 people5 personas","6 people6 personas","7 people7 personas","More than 7 peopleMás de 7 personas")
levels(data$dem_kid_pmhx___1.factor)=c("Unchecked","Checked")
levels(data$dem_kid_pmhx___2.factor)=c("Unchecked","Checked")
levels(data$dem_kid_pmhx___3.factor)=c("Unchecked","Checked")
levels(data$dem_kid_pmhx___4.factor)=c("Unchecked","Checked")
levels(data$dem_kid_pmhx___5.factor)=c("Unchecked","Checked")
levels(data$dem_kid_pmhx___6.factor)=c("Unchecked","Checked")
levels(data$dem_kid_pmhx___7.factor)=c("Unchecked","Checked")
levels(data$dem_kid_pmhx___8.factor)=c("Unchecked","Checked")
levels(data$dem_kid_pmhx___9.factor)=c("Unchecked","Checked")
levels(data$dem_kid_famhx___1.factor)=c("Unchecked","Checked")
levels(data$dem_kid_famhx___2.factor)=c("Unchecked","Checked")
levels(data$dem_kid_famhx___3.factor)=c("Unchecked","Checked")
levels(data$dem_kid_famhx___4.factor)=c("Unchecked","Checked")
levels(data$dem_kid_famhx___5.factor)=c("Unchecked","Checked")
levels(data$dem_kid_famhx___6.factor)=c("Unchecked","Checked")
levels(data$dem_kid_famhx___7.factor)=c("Unchecked","Checked")
levels(data$dem_kid_famhx___8.factor)=c("Unchecked","Checked")
levels(data$dem_kid_famhx___9.factor)=c("Unchecked","Checked")
levels(data$demographics_parent_complete.factor)=c("Incomplete","Unverified","Complete")
levels(data$tech_parent_device.factor)=c("smart phone","tablet","both a smart phone and a tablet","neither")
levels(data$tech_parent_brand___1.factor)=c("Unchecked","Checked")
levels(data$tech_parent_brand___2.factor)=c("Unchecked","Checked")
levels(data$tech_parent_brand___3.factor)=c("Unchecked","Checked")
levels(data$tech_parent_brand___4.factor)=c("Unchecked","Checked")
levels(data$tech_parent_brand___5.factor)=c("Unchecked","Checked")
levels(data$tech_parent_brand___6.factor)=c("Unchecked","Checked")
levels(data$tech_parent_brand___7.factor)=c("Unchecked","Checked")
levels(data$tech_parent_os___1.factor)=c("Unchecked","Checked")
levels(data$tech_parent_os___2.factor)=c("Unchecked","Checked")
levels(data$tech_parent_os___3.factor)=c("Unchecked","Checked")
levels(data$tech_parent_os___4.factor)=c("Unchecked","Checked")
levels(data$tech_parent_os___6.factor)=c("Unchecked","Checked")
levels(data$tech_parent_os___7.factor)=c("Unchecked","Checked")
levels(data$tech_parent_phone_service.factor)=c("YesSi","NoNo"," Unsure or Not ApplicableNo estoy seguro o no aplicable")
levels(data$tech_parent_disconnect.factor)=c("1-2 times/year1-2 veces / año","3-4 times/year3-4 veces / año","More than 5 times/yearMás de 5 veces / año")
levels(data$tech_parent_apps.factor)=c("YesSi","NoNo")










#remove '.factor' from names
data <- data[c(1, 473, 3, 474:478, 9:10, 479:483, 16, 484, 18, 485:487, 22, 488, 24, 489:491, 28, 492, 30, 493:504, 43, 505:510, 50, 511:536, 77, 537:560, 102, 561:588, 131, 589:606, 150, 607:684, 229, 685:715, 261, 716:765, 312, 766:789, 337, 790:821, 370, 822:899, 449, 900:917, 468, 918:919, 471, 920)]
names(data) <- gsub(".factor", "", names(data), fixed = TRUE)

#Name all columns
source('labels.r')