---
title: "chi_square_analysis"
output:
  html_document: default
---

```{r include=FALSE}
library(knitr)
library(kableExtra)
library(lubridate)
library(tidyverse)
library(dplyr)
purl("creating_datasets.Rmd", output = "creating_datasets.R", documentation = 2)
source(file="creating_datasets.R")
```

```{r include=FALSE}
####### for printing table
posredemps<-fullmerge %>% 
  filter(FI.x=="yes"|FI.y=="yes") %>% 
  filter(Status=="Complete") %>% 
  summarize(`FI_redemps`=n())
#posredemps

posnonredemps<-fullmerge %>% 
  filter(FI.x=="yes"|FI.y=="yes") %>% 
  filter(Status!="Complete") %>% 
  summarize(`FI_non_redemps`=n())
#posnonredemps

positives<-cbind(posredemps,posnonredemps)
#positives

negredemps<-fullmerge %>% 
  filter(FI.x=="no"|FI.y=="no") %>%
  filter(Status=="Complete") %>% 
  summarize(`FI_redemps`=n())
#negredemps

negnonredemps<-fullmerge %>% 
  filter(FI.x=="no"|FI.y=="no") %>%
  filter(Status!="Complete") %>% 
  summarize(`FI_non_redemps`=n())
#negnonredemps

negatives<-cbind(negredemps,negnonredemps)
#negatives

t2t<-rbind(positives,negatives)
#t2t

results<-c("positive","negative")

total<-cbind(results, t2t)
#total
```

```{r echo=FALSE}
#how many FI+ get RXes? 

total %>% 
  knitr::kable("html", caption="Redemptions by screen results") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")

#ggplot(screenfamtable, aes(x=`year(Visitdate)`, y=FI_total_screens, color="red")) +
 # geom_line()
  #geom_line(aes(y=FIpositivescreens, color="blue"))+
   # theme(panel.grid.major.x = element_line(size=.1, color="black"),
    #       panel.grid.major.y = element_line( size=.1, color="black"))
```

```{r echo=FALSE, eval=TRUE}
####for analysis
## straight numbers
FIredemps<-c(21,66)
FInonredemps<-c(63,216)
redempbyscreen<-cbind(FIredemps,FInonredemps)
redempbyscreen<-as.data.frame(redempbyscreen)
row.names(redempbyscreen)<-c("positive","negative")
redempbyscreen
chisq.test(redempbyscreen,correct=FALSE)
```



```{r include=FALSE}
normalredemps<-fulluniquefams %>% 
  filter(Status=="Complete") %>% 
  filter(normal==TRUE) %>% 
  summarize(redemps=n())
normalredemps

normalnonredemps<-fulluniquefams %>% 
  filter(Status!="Complete") %>% 
  filter(normal==TRUE) %>% 
  summarize(non_redemps=n())
normalnonredemps

normals<-cbind(normalredemps,normalnonredemps)

overredemps<-fulluniquefams %>% 
  filter(Status=="Complete") %>% 
  filter(over==TRUE) %>% 
  summarize(redemps=n())
overredemps

overnonredemps<-fulluniquefams %>% 
  filter(Status!="Complete") %>% 
  filter(over==TRUE) %>% 
  summarize(non_redemps=n())
overnonredemps

overs<-cbind(overredemps,overnonredemps)

tbyt<-rbind(normals,overs)

categories<-c("normal weight","overweight/obese")

bmitable<-cbind(categories, tbyt)
#total
```


```{r echo=FALSE}
bmitable %>% 
  knitr::kable("html", caption="Redemptions by BMI status") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")

#ggplot(screenfamtable, aes(x=`year(Visitdate)`, y=FI_total_screens, color="red")) +
 # geom_line()
  #geom_line(aes(y=FIpositivescreens, color="blue"))+
   # theme(panel.grid.major.x = element_line(size=.1, color="black"),
    #       panel.grid.major.y = element_line( size=.1, color="black"))
```



```{r echo=FALSE, eval=TRUE}
####for analysis
## straight numbers
BMIredemps<-c(14,6)
BMInonredemps<-c(32,5)
redempbyBMI<-cbind(BMIredemps,BMInonredemps)
redempbyBMI<-as.data.frame(redempbyBMI)
row.names(redempbyBMI)<-c("normal weight","overweight/obese")
chisq.test(redempbyBMI,correct=FALSE)
fisher.test(redempbyBMI)
```
