---
title: "Contact"
output:
  html_document: default
---

```{r include=FALSE}
library(knitr)
library(kableExtra)
library(lubridate)
library(tidyverse)
library(dplyr)
library(ggplot2)
purl("creating_datasets.Rmd", output = "creating_datasets.R", documentation = 2)
source(file="creating_datasets.R")
```

```{r include=FALSE}
#Recips by year
recipsbyyear<- distinctRXrecips %>%
  group_by(year(Visitdate)) %>% 
  dplyr::summarize(recipients=n())
recipsbyyear<-na.omit(recipsbyyear)

#Recips contacted by year
contacted<-distinctRXrecips %>%
  filter(Called=="Yes" | Called=="Walk-In") 

contactedbyyear<-contacted %>%
  group_by(year(Visitdate)) %>% 
  dplyr::summarize(contacted=n())
contactedbyyear<-na.omit(contactedbyyear)

#contacted by call by year
calledbyyear<-contacted %>%
  group_by(year(Visitdate)) %>% 
  filter(Called=="Yes") %>% 
  dplyr::summarize(called=n())

#contacted by walk-in by year
walkedbyyear<-contacted %>%
  group_by(year(Visitdate)) %>% 
  filter(Called=="Walk-In") %>% 
  dplyr::summarize(walked_in=n())

contacttable<-full_join(recipsbyyear,contactedbyyear)
methodtable<-full_join(calledbyyear,walkedbyyear)

recipcontactedtable<-full_join(contacttable,methodtable)


mm<-sum(recipcontactedtable$recipients)
nn<-sum(recipcontactedtable$contacted)
oo<-sum(recipcontactedtable$called)
pp<-sum(recipcontactedtable$walked_in)

recipcontactedtabletotals<-c("totals",mm,nn,oo,pp)
recipcontactedtable2<-rbind(recipcontactedtable,recipcontactedtabletotals)
recipcontactedtable2

#convert fields to numeric
makenumeric2<-c("recipients","contacted","called","walked_in")
recipcontactedtable2[makenumeric2] <- lapply(recipcontactedtable2[makenumeric2],as.numeric)

recipcontactedpercent<-recipcontactedtable2 %>% 
  mutate(percent_contacted=round((contacted/recipients)*100)) %>% 
  mutate(percent_called=round((called/contacted)*100)) %>% 
  mutate(percent_walked_in=round((walked_in/contacted)*100)) %>% 
  select(-recipients,-contacted,-called,-walked_in)
```
```{r echo=FALSE}
recipcontactedtable2 %>% 
  knitr::kable("html", caption="Referral recipient contact by method by year (2014-17)") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")


recipcontactedpercent %>% 
  knitr::kable("html", caption="Referral recipient contact rate by method by year (2014-17)") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")
```



```{r include=FALSE}
contactedredemps<-distinctRXrecips%>% 
  filter(Called=="Yes"|Called=="Walk-In") %>% 
  filter(Status=="Complete") %>% 
  summarize(redemps=n())

contactednonredemps<-distinctRXrecips %>% 
  filter(Called=="Yes"|Called=="Walk-In") %>% 
  filter(Status!="Complete") %>% 
  summarize(non_redemps=n())

contact<-cbind(contactedredemps, contactednonredemps)

nocontactredemps<-distinctRXrecips %>% 
  filter(Called!="Yes"& Called!="Walk-In") %>% 
  filter(Status=="Complete") %>% 
  summarize(redemps=n())

nocontactnonredemps<-distinctRXrecips%>% 
  filter(Called!="Yes"& Called!="Walk-In") %>% 
  filter(Status!="Complete") %>% 
  summarize(non_redemps=n())

nocontact<-cbind(nocontactredemps,nocontactnonredemps)

redempbycontact<-rbind(contact,nocontact)
categories<-c("contacted","no contact")
redempbycontacttable<-cbind(categories, redempbycontact)
```


```{r echo=FALSE}
redempbycontacttable %>% 
  knitr::kable("html", caption="Redemptions by contact status") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")
```
```{r echo=FALSE}
contactedcounts<-c(142,530)
nocontactcounts<-c(206,4)
redempbycontact<-cbind(contactedcounts,nocontactcounts)
redempbycontact<-as.data.frame(redempbycontact)
row.names(redempbycontact)<-c("contacted","no contact")
chisq.test(redempbycontact,correct=FALSE)
fisher.test(redempbycontact)
```

```{r include=FALSE}
calledredemps<-contacted%>% 
  filter(Called=="Yes") %>% 
  filter(Status=="Complete") %>% 
  summarize(redemps=n())

walkinredemps<-contacted %>% 
  filter(Called=="Walk-In") %>% 
  filter(Status=="Complete") %>% 
  summarize(redemps=n())
```

```{r echo=FALSE}
redempbymethod<-rbind(calledredemps,walkinredemps)
categories<-c("called","walk-in")
redempbymethodtable<-cbind(categories, redempbymethod)
redempbymethodtable
```