---
title: "Exploring Countermovement Jump (CMJ) Scan Movement Signatures in Men's COllegiate Lacrosse Athletes"
author: "Bernadette D'Alonzo"
output: 
  html_document:
    toc: false 
    depth: 3 
    theme: paper 
    highlight: tango
---
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 400)
```  
***
Use this template to complete your project throughout the course. Your Final Project presentation will be based on the contents of this document. Replace the title/name above and text below with your own, but keep the headers.

### Overview
Members of Penn Athletics, Penn Sports Medicine, and the Penn Injury Science Center are collaborating on a large study titled “Force Plate Analysis in Collegiate Athletes: An Epidemiologic and Injury Prevention Study,” a project that has been active at Penn over the last 5 years. The overarching goal of that study is to evaluate whether force plate measurements can predict injuries, and performance outcomes, and whether (and how) measurements vary across sports and sex. Exploring this may identify sport-specific profiles that may inform customized strength and conditioning injury prevention programs. The objective of this project is to take a step back from prediction to first answer the question of whether and how these measurements vary between athletes from the same sport compared to within one athlete over time, and we will examine this in the context of men’s lacrosse players. For this project, I have been working with Dr. Doug Wiebe, Professor of Epidemiology, Dr. Abby Bretzin, Postdoctoral Fellow at the Penn Injury Science Center (PISC), Dr. Jeremy Weeks, Associate Director of Penn Strength & Conditioning, and Dr. Brian Sennett, Chair of Athletic Medicine at Penn.


### Introduction 
The specific problem that this project addresses, is that we currently do not have a strong understanding of how and the extent to which force plate measurements vary across collegiate athletes in the larger study playing the same sport, and within an athlete over time. This is a key concept to explore prior to estimating or predicting injury. By eventually identifying individuals who may be at increased risk of injury, we may be able to inform the development of targeted injury prevention programs, thereby improving their effectiveness. Sparta Science is a sports performance and injury evaluation tool utilized by multiple human movement-based industries, with significant use in military, athletic, and clinical settings. Sparta Science has been described as having a technology that may enable identifying athletes at-risk for sustaining an injury.

The interdisciplinary nature of the team involved in this study is a strength and critical to the success of any of our projects. Penn’s Strength & Conditioning leadership and staff bring expertise in research utilizing force plates to date and Penn’s utilization and implementation of Sparta Science assessments. Penn Sports Medicine and Athletic Training contribute knowledge regarding the appropriateness and application of findings related to injury. Finally, Epidemiologists and Data Scientists provides support for study design, identify opportunities for natural and planned experiments, and interpretation of results.

From meetings with Strength & Conditioning, we have learned that the technology used in the Sparta Science system consists of a force plate, proprietary software, and a dataset projected to consist of data captured from more than 1,500,000 assessments. Current Sparta Science set-up at Penn consists of force plates with dedicated computers and software, and it is used with athletes across all years and varsity sports. Athletes begin with a standardized warm up that is completed just prior to the assessments; counter movement jump (CMJ), single leg balance scan, and single arm plank scan. The results of each assessment are computed by the software and converted to T-scores, by comparing to the Sparta Science dataset. For the CMJ assessment, the system generates industry-standard variables of force/time including Load, Explode, and Drive, which we will examine in this project. These scores represent an individual's ability to Create, Transfer, and Apply force efficiently and are referred to by Sparta as the individual's Movement Signature™. We have also learned that men’s lacrosse coaches have utilized the software most consistently in recent years, and at the encouragement of the Epidemiologists providing guidance on this project, we will focus on those athletes here. From Sports Medicine and Athletic Training, we have learned that lower-extremity injuries (LEIs) have been common among men’s lacrosse players at Penn, further underscoring this population as an ideal one to first explore patterns in CMJ scan measurements among team members and over time.


### Methods
Describe the data used and general methodological approach. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why. 


### Results
Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.
