---
title: "The relationship between FI and FreshRX"
output:
  html_document: default
  html_notebook: default
  word_document: default
  pdf_document: default
---


```{r include=FALSE}
library(knitr)
library(kableExtra)
library(lubridate)
library(tidyverse)
library(dplyr)
purl("creating_and_merging_datasets_final_project.Rmd", output = "creating_and_merging_datasets_final_project.R", documentation = 2)
source(file="creating_and_merging_datasets_final_project.R")
```

```{r echo=FALSE}
datasettable %>% 
  knitr::kable("html", caption="Overview of datasets used and created") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")
```


```{r include=FALSE}
##FI screening by year
#total screens by year - totals 16,284 b/c of 13 with no screening results
screensbyyear<-distinctFI %>% #dataset with one line per visit per child
  group_by(year(Visitdate)) %>% #group all visits by year
  filter(!is.na(FIworry)|!is.na(FInotlast)) %>% #look at only those with screen info
  dplyr::summarize(FI_total_screens=n())  #count screens (by year group)
#screensbyyear

#positive screens by year
positivesbyyear<-distinctFI %>% 
  group_by(year(Visitdate)) %>% 
  filter(!is.na(FIworry)|!is.na(FInotlast)) %>% 
  filter(FI=="yes") %>% 
  dplyr::summarize(FI_positive_screens=n())
#positivesbyyear

#combined table
screensbyyeartb<-suppressMessages(full_join(screensbyyear,positivesbyyear))
screensbyyeartb<-screensbyyeartb %>% 
  mutate(`FI_rate%`=round((FI_positive_screens/FI_total_screens)*100))
#screensbyyeartb

#RXes for positive screens by year
RXforposFI<-distinctFI %>% 
  group_by(year(Visitdate)) %>% 
  filter(!is.na(FIworry)|!is.na(FInotlast)) %>% 
  filter(FI=="yes") %>% 
  filter(FreshRX=="FreshRX") %>% 
  dplyr::summarize(RX_for_positives=n()) 
 #RXforposFI

RXforscreenstable<-suppressMessages(full_join(screensbyyeartb,RXforposFI)) %>% 
  mutate(`RX_for_FI_rate%`=round((RX_for_positives/FI_positive_screens)*100))
RXforscreenstable
```
```{r echo=FALSE}
#how many FI+ get RXes? 

RXforscreenstable %>% 
  knitr::kable("html", caption="FI screening by year (2012-17)") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")

#ggplot(screenfamtable, aes(x=`year(Visitdate)`, y=FI_total_screens, color="red")) +
 # geom_line()
  #geom_line(aes(y=FIpositivescreens, color="blue"))+
   # theme(panel.grid.major.x = element_line(size=.1, color="black"),
    #       panel.grid.major.y = element_line( size=.1, color="black"))

```





```{r include=FALSE}
##RX recipients by year w/FIstatus
#scripts written by year
RXtb<-RXrecips %>%
  group_by(year(Visitdate)) %>% 
  dplyr::summarize(RXes=n())
#RXtb

#scripts written by year with FI
RXFItb<-RXrecips %>%
  group_by(year(Visitdate)) %>% 
  filter(FI=="yes") %>% 
  dplyr::summarize(RXes_for_FI=n()) 
#RXFItb

RXestable<-full_join(na.omit(RXtb),na.omit(RXFItb))
RXestable<-RXestable %>% 
  mutate(`RX_for_FI%`=round((RXes_for_FI/RXes)*100))
```
```{r echo=FALSE}
#how many RXes with FI?

RXestable %>% 
  knitr::kable("html", caption="RXes written by year (2014-17)") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")

#ggplot(FullRXtable, aes(x=`year(Visitdate)`, y=RXes, color="red")) +
 # geom_line()
  #geom_line(aes(y=RXesforFI, color="blue"))+
   # theme(panel.grid.major.x = element_line(size=.1, color="black"),
    #       panel.grid.major.y = element_line( size=.1, color="black"))
```





```{r include=FALSE}
#RX redemptions by FI status by year
#redemptions by year
redempbyyear<-RXredemps %>%
  group_by(year(Visitdate)) %>% 
  dplyr::summarize(Redemptions=n())
redempbyyear

#redemptions by year with FI
redempFIbyyear<-RXredemps %>%
  group_by(year(Visitdate)) %>% 
  filter(FI=="yes") %>% 
  dplyr::summarize(Redemptions_by_FI=n())
redempFIbyyear

redempsbyyeartb<-full_join(redempbyyear,redempFIbyyear) %>% 
  mutate(`redemp_by_FI%`=round((Redemptions_by_FI/Redemptions)*100))
```

```{r echo=FALSE}
#how many redemptions with FI? 

redempsbyyeartb %>% 
  knitr::kable("html", caption="RX redemptions by year (2014-17)") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")
```