---
title: "descriptives"
output:
  html_document: default
---


```{r include=FALSE}
library(knitr)
library(kableExtra)
library(lubridate)
library(tidyverse)
library(dplyr)
purl("creating_datasets.Rmd", output = "creating_datasets.R", documentation = 2)
source(file="creating_datasets.R")
```

```{r echo=FALSE}
datasettable %>% 
  knitr::kable("html", caption="Overview of datasets used and created") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")
```

```{r include=FALSE}
##FI screening by year
#total screens by year - totals 16,297
screensbyyear<-distinctFI %>% #dataset with one line per visit per child
  group_by(year(Visitdate)) %>% #group all visits by year
  dplyr::summarize(FI_total_screens=n())  #count screens (by year group)
screensbyyear

#positive screens by year
positivesbyyear<-distinctFI %>% 
  group_by(year(Visitdate)) %>% 
  filter(FI=="yes") %>% 
  dplyr::summarize(FI_positive_screens=n())
positivesbyyear

#RXes for positive screens by year
RXforposFI<-distinctFI %>% 
  group_by(year(Visitdate)) %>% 
  filter(FI=="yes") %>% 
  filter(FreshRX=="FreshRX") %>% 
  dplyr::summarize(RX_for_positives=n()) 
 RXforposFI

 
RXforscreenstable<-suppressMessages(full_join(screensbyyear,positivesbyyear))
RXforscreenstable2<-full_join(RXforscreenstable,RXforposFI)


#negative screens by year
negativesbyyear<-distinctFI %>% 
  group_by(year(Visitdate)) %>% 
  filter(FI=="no") %>% 
  dplyr::summarize(FI_negative_screens=n())
negativesbyyear

#RXes for negative screens by year
RXfornegFI<-distinctFI %>% 
  group_by(year(Visitdate)) %>% 
  filter(FI=="no") %>% 
  filter(FreshRX=="FreshRX") %>% 
  dplyr::summarize(RX_for_negatives=n()) 
RXfornegFI


RXforscreenstable3<-suppressMessages(full_join(RXforscreenstable2,negativesbyyear))
RXforscreenstable4<-full_join(RXforscreenstable3,RXfornegFI)



#FIrate by year
screensbyyeartb<-suppressMessages(full_join(screensbyyear,positivesbyyear))
screensbyyearrate<-screensbyyeartb %>% 
  mutate(`FI_rate%`=round((FI_positive_screens/FI_total_screens)*100))
screensbyyearrate



#RXforscreenstable
m<-sum(RXforscreenstable4$FI_total_screens)
n<-sum(RXforscreenstable4$FI_positive_screens)
o<-sum(na.omit(RXforscreenstable4$RX_for_positives))
p<-sum(RXforscreenstable4$FI_negative_screens)
q<-sum(na.omit(RXforscreenstable4$RX_for_negatives))

FItabletotals<-c("totals",m,n,o,p,q)
RXforscreenstable5<-rbind(RXforscreenstable4,FItabletotals)
```

```{r echo=FALSE}
screensbyyearrate %>% 
  knitr::kable("html", caption="FI rate by year (2012-17)") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")

#ggplot(screenfamtable, aes(x=`year(Visitdate)`, y=FI_total_screens, color="red")) +
 # geom_line()
  #geom_line(aes(y=FIpositivescreens, color="blue"))+
   # theme(panel.grid.major.x = element_line(size=.1, color="black"),
    #       panel.grid.major.y = element_line( size=.1, color="black"))

```

```{r include=FALSE}
##Rxes written and redeemed by year
#RXes written by year
RXesbyyear<-distinctRXrecips %>%
  group_by(year(Visitdate)) %>%
  dplyr::summarize(Total_RX=n())
RXesbyyear<-na.omit(RXesbyyear)
#RXesbyyear

#RXes redeemed by year
Redempsbyyear<-distinctRXredemps %>% 
  group_by(year(Visitdate)) %>% 
  dplyr::summarize(Redeemed=n())
#Redempsbyyear


RXestable<-suppressMessages(full_join(RXesbyyear,Redempsbyyear))
RXestable<-RXestable %>% 
  mutate(`redemption_rate%`=round((Redeemed/Total_RX)*100))

aa<-sum(RXestable$Total_RX)
bb<-sum(RXestable$Redeemed)
cc<-sum(RXestable$`redemption_rate%`/4)

RXestabletotals<-c("totals",aa,bb,cc)
RXestable2<-rbind(RXestable,RXestabletotals)
RXestable2

##NextGen RXes by year
NGRXbyyear<-distinctRX %>%
  group_by(year(Visitdate)) %>%
  dplyr::summarize(Total_RX=n())
#NGRXbyyear<-na.omit(NGRXbyyear)
#NGRXbyyear
```

```{r echo=FALSE}
 RXestable2 %>% 
  knitr::kable("html", caption="RXes written and redeemed by year (2014-17)") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")

#ggplot(screenfamtable, aes(x=`year(Visitdate)`, y=FI_total_screens, color="red")) +
 # geom_line()
  #geom_line(aes(y=FIpositivescreens, color="blue"))+
   # theme(panel.grid.major.x = element_line(size=.1, color="black"),
    #       panel.grid.major.y = element_line( size=.1, color="black"))

```

```{r echo=FALSE}
 RXforscreenstable5 %>% 
  knitr::kable("html", caption="FI screening by year (2012-17)") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")

#ggplot(screenfamtable, aes(x=`year(Visitdate)`, y=FI_total_screens, color="red")) +
 # geom_line()
  #geom_line(aes(y=FIpositivescreens, color="blue"))+
   # theme(panel.grid.major.x = element_line(size=.1, color="black"),
    #       panel.grid.major.y = element_line( size=.1, color="black"))

```


```{r include=FALSE}
RXforscreenstable6<-RXforscreenstable4[4:6,] %>% 
  mutate(RX_for_FI_Pos_rate=round((RX_for_positives/FI_positive_screens)*100)) %>% 
  mutate(RX_for_FI_Neg_rate=round((RX_for_negatives/FI_negative_screens)*100))

RXbyresultrate<-RXforscreenstable6 %>% 
  select('year(Visitdate)',RX_for_FI_Pos_rate,RX_for_FI_Neg_rate)
RXbyresultrate
```

```{r echo=FALSE}
 RXbyresultrate %>% 
  knitr::kable("html", caption="RX rate (%) by screen type (2015-17)") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")

#ggplot(screenfamtable, aes(x=`year(Visitdate)`, y=FI_total_screens, color="red")) +
 # geom_line()
  #geom_line(aes(y=FIpositivescreens, color="blue"))+
   # theme(panel.grid.major.x = element_line(size=.1, color="black"),
    #       panel.grid.major.y = element_line( size=.1, color="black"))

```


#BMI - maybe change to how many of BMI set received/didn't receive instead of how many of RX set have a certain BMI
```{r include=FALSE}
normal<-distinctRX %>% 
  group_by(ID) %>% 
  filter(BMI<25) %>% 
  mutate(BMI_Level="normal") %>% 
  summarize(n())
nor<-dim(normal)

overweight<-distinctRX %>% 
  group_by(ID) %>% 
  filter(BMI>=25 & BMI<30) %>% 
  mutate(BMI_Level="overweight") %>% 
  summarize(n())
over<-dim(overweight)

obese<-distinctRX %>% 
  group_by(ID) %>% 
  filter(BMI>30) %>% 
  mutate(BMI_Level="obese") %>% 
  summarize(n())
ob<-dim(obese)

Level<-c("normal","overweight","obese","totals")
Counts<-c(nor[1],over[1],ob[1])
v<-sum(Counts)
Counts<-Counts<-c(nor[1],over[1],ob[1],v)
BMItable<-as.data.frame(cbind(Level,Counts))
BMItable
per1<-round((nor[1]/v),digits=3)
per2<-round((over[1]/v),digits=3)
per3<-round((ob[1]/v),digits=3)
per4<-round(sum(per1,per2,per3),digits=3)
per1<-per1*100     
per2<-per2*100  
per3<-per3*100
per4<-per4*100

            
percent<-c(per1,per2,per3,per4)
BMItb2<-cbind(BMItable,percent)
BMItb2
```


```{r echo=FALSE}
#how many RXes with BMI levels?

BMItb2 %>% 
  knitr::kable("html", caption="RX referrals by BMI (2015-17)") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")
```


```{r echo=FALSE}
plot<-table(distinctRXredemps$Called)
barplot(plot, main="is this the title?",xlab="contact method")
```

