name: ts-python37
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - tensorflow=2.0.0
  - seaborn=0.10.1
  - fbprophet=0.6
  - numpy=1.18.5
  - pandas=1.0.4
  - pandasql=0.7.3
  - SQLAlchemy=1.3.17
  - scikit-learn=0.22.1
  - matplotlib=3.2.1
  - scipy=1.4.1
  - statsmodels=0.10.2
