---
title: "Final Project-Predictors of 30-YEAR FULL CVD RISK SCORE"
author: "Alex Hanlon, EPID600 - Data Science for Biomedical Informatics"
output: 
  html_document:
  toc: false 
depth: 3 
theme: paper 
highlight: tango
---
#### Descriptive Statistics
1. CVD risk dummy and sedentary behavior summary
```{r, eval=TRUE}

rm(list=ls())
getwd()
setwd ("C:\Users\alhanlon\Box Sync\EPID 600\Final Project")

library(dplyr)
library(ggplot2)

data <- read.csv(file = "C:/Users/alhanlon/Box Sync/EPID 600/Data Files/sedentary_data_for_R", header = TRUE)
str(data)
data <- dplyr::rename (data, TOTAL_PHYS_ACTIVITY_N =  TOTAL_PHYS, BLOOD_PRESSURE_N = SYS_BP_AUTO, 
          FRUITVEG_N = FRUIT_VEG, BMI_N = BMI, BODY_FAT_N = BODY_FAT
                ) 

data <- dplyr::mutate(data, GENDER = factor(SEX, labels=c("Female", "Male")),
           RACE = factor(RACE_NEW, labels=c("Mixed/Other", "Asian","Black","White")),
           COLLEGE_C = factor(COLLEGE,labels = c("No", "Yes")),
           EMPLOYMENT_C = factor(EMPLOYMENT, labels = c("Employed",
                                                        "Unemployed",
                                                        "Retired")),
           SHIFT_WORK_C = factor(SHIFT_WORK, labels = c("No", "Yes")),
           RESIDENCE_C = factor(RESIDENCE, labels = c("Urban", "Rural")),
           DEPRESSION_C = factor(MH_STATUS, labels = c("No", "Yes")),
           SEASON_ASSESS_C = factor(SEASON_ASSESS, labels = c("Fall", 
                                                    "Winter",
                                                    "Spring",
                                                    "Summer")),
           CHRONO_C = factor(CHRONO_4_CAT, labels = c("Definitely morning", 
                                                    "More morning than evening",
                                                    "More evening than morning",
                                                    "Definitely evening")),
           SLEEP_C = factor(SLEEP, labels = c("Short", "Long", "Adequate")),
           DIABETES_C = factor(DIABETES, labels = c("No", "Yes")),
           SMOKE_C = factor(SMOKE, labels = c("No", "Yes")),
           HYPERTENSION_MEDS_C = factor(BP_MEDS_ALL, labels = c("No", "Yes")),
           PHYSICAL_ACTIVITY_C = factor(PHYSACT_REC, labels = c("No", "Yes")),
           FRUITVEG_RECOMMEND_MET_C = factor(FRUITVEG_REC, labels = c("No", "Yes")),
           ALCOHOL_INTAKE_C = factor(ALCOHOL_INTAKE, labels = c("Daily or almost daily", 
                                                    "Three or four times a week",
                                                    "Once or twice a week",
                                                    "One to three times a month",
                                                    "Special occasions only",
                                                    "Never")),
           
           CVD_RISK_C = factor(FULL_CVD_RISK >= 0.4, labels = c("Low", "High"))
           )
          


ggplot(data=data, aes(x=CVD_RISK_C)) + 
    geom_bar()
summary(data$CVD_RISK_C)




```


2. Predictors for CVD risk


```{r, eval=TRUE}

#Age
qplot(AGE, data=data, geom="histogram", binwidth=1, col=I("blue"), fill=I("blue"), alpha=I(0.5))
summary(data$AGE)

ggplot(data = data, aes(CVD_RISK_C, AGE)) +
  geom_boxplot()

t.test(AGE~CVD_RISK_C, data = data)





#Blood pressure
qplot(BLOOD_PRESSURE_N, data=data, geom="histogram", binwidth=1, col=I("blue"), fill=I("blue"), alpha=I(0.5))
summary(data$BLOOD_PRESSURE_N)

ggplot(data = data, aes(CVD_RISK_C, BLOOD_PRESSURE_N)) +
  geom_boxplot()

t.test(BLOOD_PRESSURE_N~CVD_RISK_C, data = data)





#BMI
qplot(BMI_N, data=data, geom="histogram", binwidth=1, col=I("blue"), fill=I("blue"), alpha=I(0.5))
summary(data$BMI_N)

ggplot(data = data, aes(CVD_RISK_C, BMI_N)) +
  geom_boxplot()

t.test(BMI_N~CVD_RISK_C, data = data)






#Gender

table(data$GENDER)
ggplot(data=data, aes(x=GENDER)) + 
    geom_bar()

ggplot(data = data, aes(fill = CVD_RISK_C, x = GENDER)) +
  geom_bar(position = "dodge")
chisq.test(table(data$CVD_RISK_C, data$GENDER))


#Smoking status

table(data$SMOKE_C)
ggplot(data=data, aes(x=SMOKE_C)) + 
    geom_bar()

ggplot(data = data, aes(fill = CVD_RISK_C, x = SMOKE_C)) +
  geom_bar(position = "dodge")
chisq.test(table(data$CVD_RISK_C, data$SMOKE_C))



#Diabetes
table(data$DIABETES_C)
ggplot(data=data, aes(x=DIABETES_C)) + 
    geom_bar()

ggplot(data = data, aes(fill = CVD_RISK_C, x = DIABETES_C)) +
  geom_bar(position = "dodge")
chisq.test(table(data$CVD_RISK_C, data$DIABETES_C))



# Treatment of hypertensionn


table(data$HYPERTENSION_MEDS_C)
ggplot(data=data, aes(x=HYPERTENSION_MEDS_C)) + 
    geom_bar()

ggplot(data = data, aes(fill = CVD_RISK_C, x = HYPERTENSION_MEDS_C)) +
  geom_bar(position = "dodge")
chisq.test(table(data$CVD_RISK_C, data$HYPERTENSION_MEDS_C))
















```

3. Variables of interest
```{r, eval=TRUE}
#TV hours
qplot(TV_HRS, data=data, geom="histogram", binwidth=1, col=I("blue"), fill=I("blue"), alpha=I(0.5))
summary(data$TV_HRS)

ggplot(data = data, aes(CVD_RISK_C, TV_HRS)) +
  geom_boxplot()

t.test(TV_HRS~CVD_RISK_C, data = data)







#Computer hours

qplot(COMP_HRS, data=data, geom="histogram", binwidth=1, col=I("blue"), fill=I("blue"), alpha=I(0.5))
summary(data$COMP_HRS)

ggplot(data = data, aes(CVD_RISK_C, COMP_HRS)) +
  geom_boxplot()

t.test(COMP_HRS~CVD_RISK_C, data = data)




#Drive hours

qplot(DRIVE_HRS, data=data, geom="histogram", binwidth=1, col=I("blue"), fill=I("blue"), alpha=I(0.5))
summary(data$DRIVE_HRS)

ggplot(data = data, aes(CVD_RISK_C, DRIVE_HRS)) +
  geom_boxplot()

t.test(DRIVE_HRS~CVD_RISK_C, data = data)







```


4. Covariates
```{r, eval=TRUE}

#Total physical activity (continuous)

ggplot(data = data, aes(CVD_RISK_C, TOTAL_PHYS_ACTIVITY_N)) +
  geom_boxplot()
t.test(TOTAL_PHYS_ACTIVITY_N~CVD_RISK_C, data = data)




#Total physical activity (categorical)



ggplot(data = data, aes(fill = CVD_RISK_C, x = PHYSICAL_ACTIVITY_C)) +
  geom_bar(position = "dodge") 
chisq.test(table(data$CVD_RISK_C, data$PHYSICAL_ACTIVITY_C))




#Fruit and Vegetable Intake (continuous)

ggplot(data = data, aes(CVD_RISK_C, FRUITVEG_N)) +
  geom_boxplot()
t.test(FRUITVEG_N~CVD_RISK_C, data = data)



#Fruit and Vegetable Intake (categorical)

ggplot(data = data, aes(fill = CVD_RISK_C, x = FRUITVEG_RECOMMEND_MET_C)) +
  geom_bar(position = "dodge") 
chisq.test(table(data$CVD_RISK_C, data$FRUITVEG_RECOMMEND_MET_C))



#Alcohol intake (categorical)

ggplot(data = data, aes(fill = CVD_RISK_C, x = ALCOHOL_INTAKE_C)) +
  geom_bar(position = "dodge") 
chisq.test(table(data$CVD_RISK_C, data$ALCOHOL_INTAKE_C))




#Sleep duration (categorical)

ggplot(data = data, aes(fill = CVD_RISK_C, x = SLEEP_C)) +
  geom_bar(position = "dodge") 
chisq.test(table(data$CVD_RISK_C, data$SLEEP_C))



#Sleep timing preference (categorical)

ggplot(data = data, aes(fill = CVD_RISK_C, x = CHRONO_C)) +
  geom_bar(position = "dodge") 
chisq.test(table(data$CVD_RISK_C, data$CHRONO_C))



#Body fat percentage (continuous)

ggplot(data = data, aes(CVD_RISK_C, BODY_FAT_N)) +
  geom_boxplot()
t.test(BODY_FAT_N~CVD_RISK_C, data = data)



```

4. Decision tree
```{r, eval=TRUE}

library(rpart)
library(partykit)
library(rpart.plot)
library(caret) 
set.seed(101)
train <- sample(1:nrow(data), nrow(data)*0.6)
test <- data[-train, "CVD_RISK_C"]
tree_cvd <- rpart(CVD_RISK_C~TV_HRS+COMP_HRS+DRIVE_HRS+
                    PHYSICAL_ACTIVITY_C+FRUITVEG_RECOMMEND_MET_C+
                    ALCOHOL_INTAKE_C+SLEEP_C+
                    CHRONO_C+BODY_FAT_N,  method="class", data=data, subset=train)
plot(as.party(tree_cvd), type="simple")
#plot(as.party(tree1), type="extended")
summary(tree_cvd)
yhat <- predict(tree_cvd, data[-train,], type="class")
nonmissing <- !is.na(test)
conf <- table(yhat[nonmissing], test[nonmissing])

f.conf <- confusionMatrix(conf)
print(f.conf)



```



```{r, eval=TRUE}

  mylogit1 <- glm(CVD_RISK_C~TV_HRS+COMP_HRS+DRIVE_HRS+
                    PHYSICAL_ACTIVITY_C+FRUITVEG_RECOMMEND_MET_C+
                    ALCOHOL_INTAKE_C+SLEEP_C+
                    CHRONO_C+BODY_FAT_N, data = data, family=binomial)
  summary(mylogit1)

```
