---
title: "BMIN503/EPID600 Final Project"
author: "Jenna Reece"
output: 
  html_document:
    theme: paper 
    highlight: tango
---


***
Use this template to complete your project throughout the course. Your Final Project presentation will be based on the contents of this document. Replace the title/name above and text below with your own, but keep the headers. Feel free to change the theme and other display settings, but this is not required.

### Overview
This project aims to evaluate blood product transfusion at the Hospital of the University of Pennsylvania.  I will use a dataset from 2021 that includes all transfusions performed, and the patient’s complete blood count, clotting tests, and other parameters. The goal is to assess how often patients received transfusions when they fell outside the established clinical guidelines for blood components.



### Introduction 
Blood product transfusion is a common and lifesaving intervention for patients, but despite its benefits, it also introduces risks for patients, including the risk of transfusion reaction, infectious complications, and alloimmunization. Many studies over the past few decades have demonstrated that transfusion thresholds that are more conservative, i.e. more restrictive, lead to better patient outcomes than liberal transfusion thresholds. I am examining an operational dataset which contains blood products administered to patients, and their hematologic lab values, which will be compared to established transfusion guidelines. 

Obviously, there are many complex factors that play into whether a transfusion is indicated, and transfusion thresholds may be personalized for patients, but it will be helpful to describe practices and trends to identify areas for potential intervention. There are several specific questions of particular interest to the blood bank, notably how often clinicians evaluate the corrected count increment after platelet transfusion.  Other concerns include the size of the population with certain transfusion thresholds, and identifying practice patterns for particular providers. In general, knowing how blood products are used allows the blood bank to more accurately predict blood needs in the future, which allows for better planning and inventory management.


### Methods
Describe the data used and general methodological approach. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why. 

Data cleaning:
The data that I have for this project begins in an excel file, which means that I need to do some cleaning to get it in the right format. Many of the variables are also very much not de-identified, which means that they will be de-identified for analysis.


* means that this is NOT a de-identified variable, so I need to de-identify it for this project.
KEY means that I think this column will be crucial for analysis.

Columns I have:
*KEY MRN- char
*Patient Name- char
KEY Transfusion_Date- numeric
KEY Product_type- char- may be red blood cells, single donor platelets, pathogen reduced platelets, thawed cryo, thawed plasma, whole blood
Transfused_vol- numeric, standardized, not trustworthy
Order_Name- char – not high yield, because result code is better.
Order_date- numeric- not high yield, because collect is more important
KEY Collect_date- numeric- KEY
Result_date- numeric
*Accession_nbr- char
KEY Result_code- char. Platelets, hbg, INR
KEY Result- numeric
*Order_phys- char



Analysis that should be done:

For each product:
How many patients received transfusions, and how many units did they receive- over what time period?

For those who received platelet transfusions, how many had a platelet count performed beforehand?  After?  What was the distribution of those values?

For those who received red blood cells, how many had a hemoglobin performed beforehand?  After?  What was the distribution of those values?

How many patients received a single unit of FFP? What was their INR?


Were the ordering practices different for different ordering physicians?


How would we predict the need for products given this information?



### Results
Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.
