---
title: "BMIN503/EPID600 Project Template"
author: "Your Name"
output: 
  html_document:
    toc: false 
    depth: 3 
    theme: paper 
    highlight: tango
---
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 400)
```  
***
Use this template to complete your project throughout the course. Your Final Project presentation in class will be based on the contents of this document. Replace the title/name and text below with your own, but leave the headers.

### Overview
##### Discovery of CKD patient subtypes with differential risk profiles is essential for improving health promotion strategies and precision medicine approaches in the prevention and treatment of kidney function decline and prediction of clinical outcomes.  Using baseline data from the Chronic Renal Insufficiency Cohort (CRIC) Study, including demographic, clinical history, kidney function, anthropometric/ nutritional, functional scores, vascular, medication usage, together with novel biochemical markers, we aim to create CKD subtypes with unsupervised cluster analysis algorithms.

### Introduction
##### Chronic kidney disease (CKD) affects approximately 15% of adults in the United States and is a major cause of end-stage-renal-disease (ESRD), cardiovascular disease (CVD), morbidity, and mortality. The estimated crude U.S. prevalence rate of stage 3 and 4 CKD was 7.0% in 2011-14, along with higher percentage of symptomatic and asymptomatic stage 1 and 2 CKD. The goal of CKD treatment and management is to delay disease progression, and minimize and prevent complications. Thus, it is important to address the heterogenity within CKD population and to identify the unobservable patient subgroups featured with different risk factor profiles. Discovery of the unique clusters among people with CKD will potentially provide insights to outcome prognosis, disease pathophysiology, and prevention strategies. 

##### Revealing the latent clusters within CKD patients is an interdisciplinary research question that requires input from both renal pathophysiology and bioinformatics. CKD subgroups are traditionally based on the two common existing kidney markers of estimated glomerular filtration rate (eGFR) and microalbuminuria, which classifies patients on their impaired kidney function. However, patients with the same impaired kidney function does not necessarily have the same contributing disease pathophysioloy. Thus, the use of high-dimensional data, including risk factors and early disease biomarkers, with machine learnign algorithm will allow us to construct meaningful patients clusters that discriminate disease risks and add more information to the existing patients classification. Also, the data-driven consensus clustering approach makes less assumption about the data and is hypothesis free, which is more flexible to use with complex data structure.


### Methods
##### This study used the existing data from the Chronic Renal Insufficiency Cohort (CRIC) Study, an NIDDK-funded, multi-center, longitudinal cohort of well-characterized 5,499 men and women with CKD in the U.S. By design, participants were in the age range of 21-74 years, with eGFR of 20-70 ml/min/1.73m2 at study entry. CRIC study recruited participants in two phases from seven clinical centers from 2003 to 2008 (Phase I, N=3,939), and from 2013 to 2015 (Phase III, N=1,560). Subjects in this study are from CRIC Phase I cohort.

### Results

