---
title: "determinants of liver fibrosis"
subtitle: "BMIN503/EPID600 Final Project"
author: "Samiran Mukherjee"
format: html
editor: visual
number-sections: true
embed-resources: true
---

------------------------------------------------------------------------

Use this template to complete your project throughout the course. Your Final Project presentation will be based on the contents of this document. Replace the title/name above and text below with your own, but keep the headers. Feel free to change the theme and other display settings, although this is not required.

## Overview {#sec-overview}

Using NHANES data, we aim to predict the determinants of liver fibrosis (using the publically available fibroscan data). In addition, we will also learn to train a machine learning model to identify variables that can best predict the occurence of fibrosis. .

## Introduction {#sec-introduction}

Non-alcoholic fatty liver disease (NAFLD)  is prevalent in 30% of the US population. It is strongly associated with the presence of co-morbid metabolic risk factors like obesity, type 2 DM, hypertension and hyperlipidemia. Given that 1% patients will end up developing liver cirrhosis (fibroscan liver stiffness cut off \>14.6), it is imperative to identify preventable independent variables that may influence the occurence of the same. 

## Methods {#sec-methods}

Describe the data used and general methodological approach used to address the problem described in the @sec-introduction. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why.

## Results {#sec-results}

Describe your results and include relevant tables, plots, and code/comments used to obtain them. You may refer to the @sec-methods as needed. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

## Conclusion

This the conclusion. The @sec-results can be invoked if you'd like.
