---
title: "Your_Title"
subtitle: "BMIN503/EPID600 Final Project"
author: "First_Name Last_Name"
format: html
editor: visual
number-sections: true
embed-resources: true
---

------------------------------------------------------------------------

Use this template to complete your project throughout the course. Your Final Project presentation will be based on the contents of this document. Replace the title/name above and text below with your own, but keep the headers. Feel free to change the theme and other display settings, although this is not required.

## Overview {#sec-overview}

This project seeks to explore the potential link between maternal hypertensive disorders of pregnancy and the prevalence of vascular nevi, such as port-wine stains and strawberry hemangiomas, in their offspring at different age points. These age points for the children will be at four months, one year, and seven years. My goal is to ascertain if, and to what extent, maternal hypertensive disorders can be predictive of such vascular skin manifestations in their children. The primary data source is the Collaborative Perinatal Project (CPP). The CPP was a large-scale, multi-center study conducted in the U.S. during the 1950s and 60s to investigate the environmental and biological factors affecting pregnancy outcomes and child health. For this study, I will extract data related to maternal hypertensive disorders and subsequent reports of vascular nevi in their children during the three age points.

On Monday, 10/23, I consulted with Dr. David Margolis from Dermatology. On Tuesday, 10/24, I consulted with Drs. Stefanie Hinkle and Sunni Mumford from Perinatal and Reproductive Health.

1.  Key Insights from Dr. Margolis: I learned that infantile hemangiomas (IH) typically regress by the age of 4, whereas port-wine stains (PWS) are permanent. This distinction poses a challenge because the data for children at 4 months and 1 year doesn't differentiate between hemangiomas and port-wine stains, unlike the data for age 7. We initially talked about an alternative method for a secondary outcome analysis, which would involve deducing non-PWS vascular nevi occurrences (presumed to be IH) for children at ages 4 months and 1 year, followed by directly identifying the presence of IH at age 7. This requires subtracting the number of PWS at 7 years from the total vascular nevi recorded at 4 months. Given these insights, I decided to streamline the research to focus primarily on the overall occurrence of vascular nevi in the offspring, encompassing all types with differentiated by specific type until age 7.

2.  Key Insights from Drs. Hinkle and Mumford: I gleaned that "chronic hypertension" is essentially equivalent to "pre-pregnancy hypertension." Therefore, individuals diagnosed with "pre-pregnancy hypertension" cannot be categorized under "gestational hypertension." This distinction is vital because gestational hypertension requires the condition to be a new onset. Moreover, superimposed hypertension is described to be a combination of "chronic hypertension" with the presence of protein in the urine, indicative of preeclampsia. They suggested me to refer to the American College of Obstetricians and Gynecologists (ACOG) for precise diagnostic criteria.

## Introduction {#sec-introduction}

Port-wine stains (PWS) and infantile hemangiomas (IH) are among the most prevalent vascular birthmarks with unique pathophysiological and clinical characteristics. While PWS results from congenital malformations and persists lifelong, IH emerges postnatally due to abnormal endothelial cell proliferation and usually regresses by age four. Both are believed to arise from fetal developmental disruptions, possibly due to gestational hypoxia or insufficient growth factors, which may interfere with angiogenesis and vasculogenesis.

Understanding these vascular birthmarks requires insights from several interdisciplinary domains:

1.  **Developmental Biology:** To grasp the fetal developmental disturbances and their implications.
2.  **Vascular Biology:** For insights into angiogenesis, vasculogenesis, and the very nature of the vascular birthmarks.
3.  **Obstetrics:** Since conditions related to pregnancy, like preeclampsia, might have implications for the onset of such birthmarks.
4.  **Pediatrics:** To track the birthmarks' evolution over developmental stages and address potential complications.
5.  **Dermatology:** Given the skin manifestation of these vascular birthmarks.

Abnormal spiral artery remodeling during the early pregnancy stages is crucial for optimal fetal nourishment, and any deviations here could indicate the development of these birthmarks as compensatory mechanisms to restore vascular equilibrium. Conditions like preeclampsia and placental insufficiency that correlate with in utero hypoxia could potentially trigger IH. However, no such direct link has been established for PWS yet.

Both IH and PWS come with their own set of complications. For IH, depending on its position, it could obstruct vision, hinder food intake, or even induce acute respiratory failure. PWS, too, has its complications, with children having a PWS in the ophthalmic region at risk of developing Sturge Weber Syndrome. Given these complications and gaps in understanding, the significance of this research is twofold: to delve deeper into the associations of IH and PWS with hypertensive disorders of pregnancy, and to observe the occurrence of these vascular birthmarks across various child developmental stages. With the comprehensive data from the CPP, I hope to widen our understanding about the prevalence of vascular birthmarks and their associations with hypertensive disorders of pregnancy.

## Methods {#sec-methods}

Describe the data used and general methodological approach used to address the problem described in the @sec-introduction. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why.

## Results {#sec-results}

Describe your results and include relevant tables, plots, and code/comments used to obtain them. You may refer to the @sec-methods as needed. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

## Conclusion

This the conclusion. The @sec-results can be invoked if you'd like.
