<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Annie Chen" />


<title>Blood Cultures Utilization at HUP</title>

<script src="final_project_Chen_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="final_project_Chen_files/bootstrap-3.3.5/css/paper.min.css" rel="stylesheet" />
<script src="final_project_Chen_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="final_project_Chen_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="final_project_Chen_files/bootstrap-3.3.5/shim/respond.min.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<div class="container-fluid main-container">

<!-- tabsets -->
<script src="final_project_Chen_files/navigation-1.1/tabsets.js"></script>
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Blood Cultures Utilization at HUP</h1>
<h4 class="author"><em>Annie Chen</em></h4>

</div>


<hr />
<p>Use this template to complete your project throughout the course. Your Final Project presentation in class will be based on the contents of this document. Replace the title/name and text below with your own, but leave the headers.</p>
<div id="overview" class="section level3">
<h3>Overview</h3>
<p>In this section, give a brief a description of your project and its goal, what data you are using to complete it, and what three faculty/staff in different fields you have spoken to about your project with a brief summary of what you learned from each person. Include a link to your final project GitHub repository.</p>
<p>The goal of my project is to characterize the use and effectiveness of blood cultures for detecting bloodstream infections in patients at the Hospital for the University of Pennsylvania (HUP). I will be using data from monthly reports of blood cultures at HUP for FY2015.</p>
</div>
<div id="introduction" class="section level3">
<h3>Introduction</h3>
<p>In the first paragraph, describe the problem addressed, its significance, and some background to motivate the problem.</p>
<p>In the second paragraph, explain why your problem is interdisciplinary, what fields can contribute to its understanding, and incorporate background related to what you learned from meeting with faculty/staff.</p>
<p>Blood cultures are frequently used and are important for detecting the presence of microbes in the bloodstream. However, excessive use of blood cultures can be detrimental to patients and may not significantly contribute to patient care. Furthermore, there are different guidelines for blood culture utilization, and it is unclear to what extent health professionals are aware of these guidelines. Investigating blood culture utilization is critical for improving the practice of blood cultures, their effectiveness in detecting bloodstream infections, and patient care management. In addition, analyzing blood cultures data may reveal information on the frequency of false positives due to contamination and the prevalence of bacteremia in different patient populations. In addiiton, analysis of blood cultures utilization data may result in the dentification of low-risk populations for bacteremia, which may will help reduce unnecessary use of blood cultures. Finally, analysis of high-utilizers of blood cultures may also be useful for addressing the practice of blood cultures utilization.</p>
<p>This is an interdisciplinary problem that draws knowledge from data science, clinical microbiology, statistics, and data visualization. I have been working with Dr. Irv Nachamkin, Director of the Divison of Laboratory Medicine at HUP. He has helped direct me to relevant analyses based on his domain knowledge of clinical microbiology. I have also met with Dr. Rebecca Hubbard, Associate Professor of Biostatistics. She gave me useful advice on conducting linear regressions on my data and visualizing the data.</p>
</div>
<div id="methods" class="section level3">
<h3>Methods</h3>
<p>In the first paragraph, describe the data used and general methodological approach. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why.</p>
<p>I will be using monthly reports of blood cultures utilization at HUP for FY2015. This is a record that includes information for each patient who had blood drawn for a blood culture test. The report shows the number of sets of blood cultures taken per day, the location by hospital floor, whether a phlebotomist drew the culture, and the final result (ex. no growth or the name of the microbial species isolated).</p>
<p>I will first use descriptive statistics to look at the distribution of sets of blood cultures taken per patient and by hospital floor. I will also look at the distribution of pathogens isolated. Then, I will analyze the number of follow-up cultures taken after a positive identification to test the hypothesis that the number of sets of blood cultures taken is linked to the organism identified. I will also analyze the high utilizers to see what floors they are coming from and whether there is an association.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(dplyr)</code></pre></div>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(magrittr)
<span class="kw">library</span>(gdata)</code></pre></div>
<pre><code>## gdata: read.xls support for &#39;XLS&#39; (Excel 97-2004) files ENABLED.</code></pre>
<pre><code>## </code></pre>
<pre><code>## gdata: read.xls support for &#39;XLSX&#39; (Excel 2007+) files ENABLED.</code></pre>
<pre><code>## 
## Attaching package: &#39;gdata&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:dplyr&#39;:
## 
##     combine, first, last</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     nobs</code></pre>
<pre><code>## The following object is masked from &#39;package:utils&#39;:
## 
##     object.size</code></pre>
<pre><code>## The following object is masked from &#39;package:base&#39;:
## 
##     startsWith</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(lubridate)</code></pre></div>
<pre><code>## 
## Attaching package: &#39;lubridate&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:base&#39;:
## 
##     date</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">getwd</span>()</code></pre></div>
<pre><code>## [1] &quot;/Users/Annie/scripts/EPID600_Final_Project&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">inFile &lt;-<span class="st"> &quot;FY15_deidentified_data-2015-11-22-revised.txt&quot;</span>
FY15_deID &lt;-<span class="st"> </span><span class="kw">read.table</span>(inFile,<span class="dt">header=</span>T, <span class="dt">sep=</span><span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>, <span class="dt">quote=</span><span class="st">&quot;&quot;</span>,<span class="dt">na.strings=</span><span class="st">&quot;&quot;</span>)

<span class="kw">str</span>(FY15_deID)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    45767 obs. of  7 variables:
##  $ Study_ID    : int  1 1 1 2 2 3 3 3 3 4 ...
##  $ Julian      : int  125 164 125 358 358 119 128 119 128 126 ...
##  $ Location    : Factor w/ 125 levels &quot;APHE Apheresis&quot;,..: 24 20 24 101 101 94 94 94 94 20 ...
##  $ Phleb       : Factor w/ 2 levels &quot;no&quot;,&quot;yes&quot;: 1 1 1 1 1 1 2 1 2 1 ...
##  $ Final_Report: Factor w/ 167 levels &quot;Achspe&quot;,&quot;AcibauC&quot;,..: 100 100 100 100 100 100 100 100 100 100 ...
##  $ Isolate     : Factor w/ 173 levels &quot;\&quot;Aerobic Gram Positive Rods, Not Listeria\&quot;&quot;,..: 101 101 101 101 101 101 101 101 101 101 ...
##  $ Contam      : Factor w/ 2 levels &quot;no&quot;,&quot;yes&quot;: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#change Study_ID from integers to factors</span>
FY15_deID$Study_ID &lt;-<span class="st"> </span><span class="kw">factor</span>(FY15_deID$Study_ID)

<span class="kw">sum</span>(<span class="kw">complete.cases</span>(FY15_deID))</code></pre></div>
<pre><code>## [1] 45756</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#11 not complete cases. 8 have abnormal results (ex. test reordered). 2 are missing location.</span>
<span class="co">#View(FY15_deID[!complete.cases(FY15_deID),])</span>
<span class="co">#1 is aerobic gram pos rods not listeria. Final_report should be &quot;GPR NLIS&quot;.</span>

FY15_deID[<span class="dv">10875</span>,<span class="st">&quot;Final_Report&quot;</span>] &lt;-<span class="st"> &quot;GPR NLIS&quot;</span>

<span class="co">#only use complete cases in analyses. 45757 cases</span>
FY15_deIDcomplete &lt;-<span class="st"> </span>FY15_deID[<span class="kw">complete.cases</span>(FY15_deID),]

<span class="co">#change Julian date so that day 1 is July 1st.</span>
FY15_deIDcomplete %&lt;&gt;%
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Julian =</span> <span class="kw">ifelse</span>(Julian &gt;=<span class="dv">182</span>,Julian<span class="dv">-181</span>,Julian<span class="dv">+184</span>))</code></pre></div>
<pre><code>## Warning: failed to assign NativeSymbolInfo for env since env is already defined in the &#39;lazyeval&#39; namespace</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#sort by Study_ID and then Julian so that it&#39;s in chronological order for each patient</span>
FY15_deIDcomplete %&lt;&gt;%<span class="st"> </span><span class="kw">arrange</span>(Study_ID,Julian)

<span class="co">#clean up entries for results on pathogen identification</span>
<span class="kw">length</span>(<span class="kw">unique</span>(FY15_deIDcomplete$Final_Report)) <span class="co">#168 (167 for FY15_deIDcomplete)</span></code></pre></div>
<pre><code>## [1] 167</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(<span class="kw">unique</span>(FY15_deIDcomplete$Isolate)) <span class="co">#173 (only 165 for FY15_deIDcomplete)</span></code></pre></div>
<pre><code>## [1] 165</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cultures &lt;-<span class="st"> </span>FY15_deIDcomplete %&gt;%
<span class="st">  </span><span class="kw">filter</span>(!<span class="kw">is.na</span>(Final_Report)) %&gt;%
<span class="st">  </span><span class="kw">filter</span>(Final_Report !=<span class="st"> &quot;Dead&quot;</span>) %&gt;%
<span class="st">  </span><span class="kw">filter</span>(Final_Report !=<span class="st"> &quot;See C A-BC&quot;</span>) %&gt;%
<span class="st">  </span><span class="kw">filter</span>(Final_Report !=<span class="st"> &quot;See C-NBC&quot;</span>) %&gt;%
<span class="st">  </span><span class="kw">filter</span>(Final_Report !=<span class="st"> &quot;Corr Rpt&quot;</span>) %&gt;%
<span class="st">  </span><span class="kw">filter</span>(Final_Report !=<span class="st"> &quot;Dup&quot;</span>)

<span class="kw">length</span>(<span class="kw">unique</span>(cultures$Final_Report)) <span class="co">#162</span></code></pre></div>
<pre><code>## [1] 162</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(<span class="kw">unique</span>(cultures$Isolate)) <span class="co">#160. Bacspe and Bacil are both abbreviations for &quot;Bacillus species&quot;. Nicrospe and Micro are both abbreviations for &quot;Micrococcus species&quot;.</span></code></pre></div>
<pre><code>## [1] 160</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x =<span class="st"> </span><span class="dv">1</span>:<span class="dv">162</span>
d &lt;-<span class="st"> </span><span class="kw">data.frame</span>(x,<span class="kw">unique</span>(<span class="kw">factor</span>(cultures$Final_Report)))
<span class="co">#write.table(d,&quot;finalreportvalues.txt&quot;,sep=&quot;\t&quot;)</span>

x =<span class="st"> </span><span class="dv">1</span>:<span class="dv">160</span>
d &lt;-<span class="st"> </span><span class="kw">data.frame</span>(x,<span class="kw">unique</span>(<span class="kw">factor</span>(cultures$Isolate)))
<span class="co">#write.table(d,&quot;isolate.txt&quot;,sep=&quot;\t&quot;)</span>

x=<span class="dv">1</span>:<span class="dv">173</span>
d &lt;-<span class="st"> </span><span class="kw">data.frame</span>(x,<span class="kw">unique</span>(<span class="kw">factor</span>(FY15_deID$Isolate)))
<span class="co">#write.table(d,&quot;orig_isolate.txt&quot;,sep=&quot;\t&quot;)</span>

<span class="co">#Group certain species together based on Irv&#39;s suggestions</span>
cultures$Final_Report[cultures$Final_Report==<span class="st">&quot;MRSA&quot;</span>] &lt;-<span class="st"> &quot;SA&quot;</span>
cultures$Final_Report[cultures$Final_Report==<span class="st">&quot;Acispe&quot;</span> ||<span class="st"> </span>cultures$Final_Report==<span class="st">&quot;Actodo&quot;</span> ||<span class="st"> </span>cultures$Final_Report==<span class="st">&quot;Actspe&quot;</span>] &lt;-<span class="st"> &quot;Actinomy&quot;</span>
cultures$Final_Report[cultures$Final_Report==<span class="st">&quot;Bacfra&quot;</span>] &lt;-<span class="st"> &quot;BacfraG&quot;</span>
cultures$Final_Report[cultures$Final_Report==<span class="st">&quot;Bacil&quot;</span>] &lt;-<span class="st"> &quot;Bacspe&quot;</span>
cultures$Final_Report[cultures$Final_Report==<span class="st">&quot;Gorspu&quot;</span>] &lt;-<span class="st"> &quot;Gordo&quot;</span>
cultures$Final_Report[cultures$Final_Report==<span class="st">&quot;Kocrhizo&quot;</span>] &lt;-<span class="st"> &quot;Kochrizo&quot;</span>
cultures$Final_Report[cultures$Final_Report==<span class="st">&quot;SalGD&quot;</span> ||<span class="st"> </span>cultures$Final_Report==<span class="st">&quot;SalspD&quot;</span>] &lt;-<span class="st"> &quot;Salmo&quot;</span>
cultures$Final_Report[cultures$Final_Report==<span class="st">&quot;Stahomhom&quot;</span>] &lt;-<span class="st"> &quot;Stahom&quot;</span>
cultures$Final_Report[cultures$Final_Report==<span class="st">&quot;Staintergp&quot;</span>] &lt;-<span class="st"> &quot;Staint&quot;</span>
cultures$Final_Report[cultures$Final_Report==<span class="st">&quot;Strsalsal&quot;</span>] &lt;-<span class="st"> &quot;Strsal&quot;</span>
cultures$Final_Report[cultures$Final_Report==<span class="st">&quot;Triasa&quot;</span>] &lt;-<span class="st"> &quot;Trichosp&quot;</span>
cultures$Final_Report[cultures$Final_Report==<span class="st">&quot;Veill&quot;</span>] &lt;-<span class="st"> &quot;Veillspe&quot;</span>

<span class="kw">length</span>(<span class="kw">unique</span>(cultures$Final_Report)) <span class="co">#152</span></code></pre></div>
<pre><code>## [1] 152</code></pre>
</div>
<div id="results" class="section level3">
<h3>Results</h3>
<p>Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you’d like, but this is not required.</p>
<p>I am first looking at the overall distribution of number of blood cultures taken per patient and by location. This is a highly skewed distribution. Of 45,767 sets of blood cultures taken in FY2015, there were 11,737 different patients (based on MRN). I will be using the 45,757 complete cases (11,735 patients) for subsequent analyses. The number of sets taken ranged from 1 to 90, with a median of 2 and a mean of 3.899 sets. The number of days in between sets ranged from 0 to 364, with a median of 0 and a mean of 30.82. This is because some patients had multiple hospital visits within FY2015. Of 125 locations where patients had blood cultures taken in FY2015, the number of sets ranged from 1 to 4531, with a median of 17 and a mean of 366.1.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#gives the number of sets of bc/patient and the period of time during which blood cultures were taken during the year.</span>
by_ID &lt;-<span class="st"> </span>cultures %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Study_ID) %&gt;%
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">count=</span><span class="kw">n</span>(),
            <span class="dt">Range=</span><span class="kw">diff</span>(<span class="kw">range</span>(Julian))) %&gt;%
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(count))

<span class="kw">nrow</span>(by_ID)</code></pre></div>
<pre><code>## [1] 11735</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(by_ID)</code></pre></div>
<pre><code>## # A tibble: 6 × 3
##   Study_ID count Range
##     &lt;fctr&gt; &lt;int&gt; &lt;dbl&gt;
## 1     2978    90   301
## 2     9368    90   152
## 3     4584    89   362
## 4     8029    87   195
## 5     3839    83    87
## 6     8099    79   190</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(by_ID$count)</code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.000   1.000   2.000   3.899   4.000  90.000</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(by_ID$Range)</code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.00    0.00    0.00   23.36   10.00  364.00</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(by_ID, <span class="kw">aes</span>(<span class="dt">x=</span>count)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth=</span><span class="dv">1</span>) +
<span class="st">  </span><span class="kw">theme_bw</span>() +<span class="st"> </span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">expand=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) +
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">expand=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Number of blood cultures/patient&quot;</span>, <span class="dt">y=</span><span class="st">&quot;Count&quot;</span>,
       <span class="dt">title=</span><span class="st">&quot;Total number of sets taken per patient&quot;</span>) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept=</span><span class="kw">median</span>(by_ID$count),<span class="dt">colour=</span><span class="st">&quot;red&quot;</span>)</code></pre></div>
<p><img src="final_project_Chen_files/figure-html/Descriptive%20statistics%20on%20entire%20dataset-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">by_ID20 &lt;-<span class="st"> </span>by_ID %&gt;%
<span class="st">  </span><span class="kw">filter</span>(count&gt;=<span class="dv">20</span>)

<span class="kw">ggplot</span>(by_ID20, <span class="kw">aes</span>(<span class="dt">x=</span>count)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth=</span><span class="dv">1</span>) +
<span class="st">  </span><span class="kw">theme_bw</span>() +<span class="st"> </span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">expand=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) +
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">expand=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Number of blood cultures/patient&quot;</span>, <span class="dt">y=</span><span class="st">&quot;Count&quot;</span>,
       <span class="dt">title=</span><span class="st">&quot;Total number of sets for patients with at least 20 sets&quot;</span>) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept=</span><span class="kw">median</span>(by_ID20$count),<span class="dt">colour=</span><span class="st">&quot;red&quot;</span>)</code></pre></div>
<p><img src="final_project_Chen_files/figure-html/Descriptive%20statistics%20on%20entire%20dataset-2.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Look at the distribution of total # of bc by location</span>
by_loc &lt;-<span class="st"> </span>FY15_deIDcomplete %&gt;%
<span class="st">  </span><span class="kw">filter</span>(!<span class="kw">is.na</span>(Location)) %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Location,Study_ID) %&gt;%
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">count=</span><span class="kw">n</span>()) %&gt;%
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(count))

by_loc_avg &lt;-<span class="st"> </span>by_loc %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Location) %&gt;%
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg=</span><span class="kw">sum</span>(count)/<span class="kw">nrow</span>(Location))

<span class="kw">nrow</span>(by_loc)</code></pre></div>
<pre><code>## [1] 15295</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(by_loc)</code></pre></div>
<pre><code>## Source: local data frame [6 x 3]
## Groups: Location [5]
## 
##   Location Study_ID count
##     &lt;fctr&gt;   &lt;fctr&gt; &lt;int&gt;
## 1      RP3     3839    69
## 2      RP7     8029    67
## 3      RP6     2530    66
## 4      S12    11533    62
## 5      RP7     8099    60
## 6      S10     7410    55</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(by_loc$count)</code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.000   1.000   2.000   2.992   3.000  69.000</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#I don&#39;t think this graph is informative</span>
<span class="kw">ggplot</span>(by_loc, <span class="kw">aes</span>(<span class="dt">x=</span>count)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth=</span><span class="dv">1</span>) +
<span class="st">  </span><span class="kw">theme_bw</span>() +<span class="st"> </span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">panel.grid.major=</span><span class="kw">element_line</span>(<span class="dt">colour=</span><span class="st">&quot;gray&quot;</span>)) +
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">colour=</span><span class="st">&quot;black&quot;</span>, <span class="dt">hjust=</span><span class="dv">1</span>)) +
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">expand=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) +
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">expand=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Number of blood cultures/location&quot;</span>, 
       <span class="dt">y=</span><span class="st">&quot;Count&quot;</span>,
       <span class="dt">title=</span><span class="st">&quot;Distribution of number of sets/patient by location&quot;</span>) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept=</span><span class="kw">median</span>(by_loc$count),<span class="dt">colour=</span><span class="st">&quot;red&quot;</span>)</code></pre></div>
<p><img src="final_project_Chen_files/figure-html/Descriptive%20statistics%20on%20entire%20dataset-3.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(by_loc, <span class="kw">aes</span>(<span class="kw">reorder</span>(Location,-count),count)) +
<span class="st">  </span><span class="kw">geom_boxplot</span>() +
<span class="st">  </span><span class="kw">theme_bw</span>() +<span class="st"> </span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">panel.grid.major=</span><span class="kw">element_line</span>(<span class="dt">colour=</span><span class="st">&quot;gray&quot;</span>)) +
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">colour=</span><span class="st">&quot;black&quot;</span>,<span class="dt">angle=</span><span class="dv">90</span>, <span class="dt">hjust=</span><span class="dv">1</span>)) +
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">expand=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Number of blood cultures/location&quot;</span>, 
       <span class="dt">y=</span><span class="st">&quot;Count&quot;</span>,
       <span class="dt">title=</span><span class="st">&quot;Distribution of number of sets/patient by location&quot;</span>)</code></pre></div>
<p><img src="final_project_Chen_files/figure-html/Descriptive%20statistics%20on%20entire%20dataset-4.png" width="672" /></p>
<p>Since we don’t have information on the length of each patient’s hospital encounter, I will split the bc into 30-day periods, which is a reasonable amount of time to clear an infection and probably accounts for the duration of most hospital stays. After splitting into 30-day periods, the number of bc taken ranged from 1 to 52, with a median of 2 and a mean of 3.084.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">by_Jul &lt;-<span class="st"> </span>FY15_deIDcomplete %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Study_ID,Julian,Location) %&gt;%
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">num_set=</span><span class="kw">n</span>()) 

by_Jul &lt;-<span class="st"> </span><span class="kw">droplevels</span>(by_Jul)

subsets &lt;-<span class="st"> </span><span class="kw">split</span>(by_Jul,by_Jul$Study_ID)

<span class="co">#for each Study_ID, count the number of sets in 30d periods</span>
split30days &lt;-<span class="st"> </span>function(df){
  c &lt;-<span class="st"> </span><span class="kw">cumsum</span>(<span class="kw">diff</span>(df$Julian))
  ref=<span class="dv">1</span> <span class="co">#ref index for counting 30day periods</span>
  max=<span class="dv">30</span> <span class="co">#30days from ref. initial max would be 30</span>
  vec =<span class="st"> </span><span class="kw">rep</span>(<span class="dv">0</span>,<span class="kw">length</span>(c))
  g=<span class="dv">0</span>
  if (<span class="kw">length</span>(c)&gt;=<span class="dv">1</span>){
     for (i in <span class="dv">1</span>:<span class="kw">length</span>(c)){
       if (c[i]&lt;=max) {
         vec[i] =<span class="st"> </span>g
         } else {
           ref=i<span class="dv">+1</span> <span class="co">#set reference for next 30day period</span>
           max=c[i]+<span class="dv">30</span> <span class="co">#next 30day period</span>
           g =<span class="st"> </span>g<span class="dv">+1</span>
           vec[i]=g
         }
     }
  }
  df$group_30 &lt;-<span class="st"> </span><span class="dv">1</span>+<span class="kw">c</span>(<span class="dv">0</span>,vec)
  <span class="kw">return</span>(df)
}
<span class="co">#test &lt;- subsets[4080:4085]</span>
<span class="co">#get error because Study_ID 4085 is not there. the location was missing so I removed it but somehow R still thinks this is one of the levels for Study_ID. Use droplevels() to drop factor levels in a subsetted data frame</span>
bc_30d &lt;-<span class="st"> </span><span class="kw">lapply</span>(subsets,split30days)
bc_30d &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">do.call</span>(<span class="st">&quot;rbind&quot;</span>,bc_30d)) 
bc_30d %&lt;&gt;%
<span class="st">  </span><span class="kw">arrange</span>(Study_ID,Julian)

<span class="co">#look at distribution of bc for patients after splitting up into 30d periods</span>
bc_30d_ID &lt;-<span class="st"> </span>bc_30d %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Study_ID,group_30) %&gt;%
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">count=</span><span class="kw">sum</span>(num_set),
            <span class="dt">Range=</span><span class="kw">diff</span>(<span class="kw">range</span>(Julian))) %&gt;%
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(count))

<span class="kw">summary</span>(bc_30d_ID$count)</code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.000   1.000   2.000   3.112   4.000  52.000</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(bc_30d_ID, <span class="kw">aes</span>(<span class="dt">x=</span>count)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth=</span><span class="dv">1</span>) +
<span class="st">  </span><span class="kw">theme_bw</span>() +<span class="st"> </span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">expand=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) +
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">expand=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Number of sets of blood cultures per patient&quot;</span>, <span class="dt">y=</span><span class="st">&quot;Count&quot;</span>,
       <span class="dt">title=</span><span class="st">&quot;Distriution of sets taken per patient within a 30d period&quot;</span>) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept=</span><span class="kw">median</span>(bc_30d_ID$count),<span class="dt">colour=</span><span class="st">&quot;red&quot;</span>)</code></pre></div>
<p><img src="final_project_Chen_files/figure-html/Split%20#%20of%20bc%20per%20patient%20into%2030d%20periods-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">bc_30d_ID20 &lt;-<span class="st"> </span>bc_30d_ID %&gt;%
<span class="st">  </span><span class="kw">filter</span>(count&gt;=<span class="dv">20</span>) %&gt;%
<span class="st">  </span><span class="kw">arrange</span>(Study_ID)

<span class="kw">ggplot</span>(bc_30d_ID20, <span class="kw">aes</span>(<span class="dt">x=</span>count)) +
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth=</span><span class="dv">1</span>) +
<span class="st">  </span><span class="kw">theme_bw</span>() +<span class="st"> </span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">expand=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) +
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">expand=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Number of sets of blood cultures/patient&quot;</span>, <span class="dt">y=</span><span class="st">&quot;Count&quot;</span>,
       <span class="dt">title=</span><span class="st">&quot;Distribution of sets taken for patients with at least 20 sets within a 30d period&quot;</span>) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept=</span><span class="kw">median</span>(bc_30d_ID20$count),<span class="dt">colour=</span><span class="st">&quot;red&quot;</span>)</code></pre></div>
<p><img src="final_project_Chen_files/figure-html/Split%20#%20of%20bc%20per%20patient%20into%2030d%20periods-2.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">by_Jul_isolate &lt;-<span class="st"> </span>cultures %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Study_ID,Julian,Location,Final_Report) %&gt;%
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">num_set=</span><span class="kw">n</span>()) 

by_Jul_isolate &lt;-<span class="st"> </span><span class="kw">droplevels</span>(by_Jul_isolate)

subsets_isolate &lt;-<span class="st"> </span><span class="kw">split</span>(by_Jul_isolate,by_Jul_isolate$Study_ID)

bc_30d_isolate &lt;-<span class="st"> </span><span class="kw">lapply</span>(subsets_isolate,split30days)
bc_30d_isolate &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">do.call</span>(<span class="st">&quot;rbind&quot;</span>,bc_30d_isolate)) 
bc_30d_isolate %&lt;&gt;%
<span class="st">  </span><span class="kw">arrange</span>(Study_ID,Julian)

by_loc_isolate &lt;-<span class="st"> </span>bc_30d_isolate %&gt;%
<span class="st">  </span><span class="kw">filter</span>(!<span class="kw">is.na</span>(Location)) %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Location,Study_ID,group_30) %&gt;%
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">count=</span><span class="kw">sum</span>(num_set)) %&gt;%
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(count))

by_loc_avg_isolate &lt;-<span class="st"> </span>by_loc_isolate %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Location) %&gt;%
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">min=</span><span class="kw">min</span>(count),
            <span class="dt">avg=</span><span class="kw">sum</span>(count)/<span class="kw">n</span>(),
            <span class="dt">max=</span><span class="kw">max</span>(count))

<span class="kw">ggplot</span>(by_loc_isolate,<span class="kw">aes</span>(<span class="kw">reorder</span>(Location,-count),count)) +
<span class="st">  </span><span class="kw">geom_boxplot</span>() +
<span class="st">  </span><span class="kw">theme_bw</span>() +
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">panel.grid.major=</span><span class="kw">element_line</span>(<span class="dt">colour=</span><span class="st">&quot;gray&quot;</span>)) +
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">colour=</span><span class="st">&quot;black&quot;</span>,<span class="dt">angle=</span><span class="dv">90</span>, <span class="dt">hjust=</span><span class="dv">1</span>)) +
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">expand=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Location&quot;</span>, 
       <span class="dt">y=</span><span class="st">&quot;Number of sets of blood cultures per patient in a 30-day period&quot;</span>,
       <span class="dt">title=</span><span class="st">&quot;Distribution of sets/patient in a 30-day period by location&quot;</span>)</code></pre></div>
<p><img src="final_project_Chen_files/figure-html/Split%20#%20of%20bc%20per%20patient%20into%2030d%20periods-3.png" width="672" /></p>
<p>Next, I will use descriptive statistics to characterize the rate of contamination and of positive identification. I will also look at the distribution of pathogens isolated.</p>
<p>Of 45,767 sets taken, there are 45,752 sets included in this analysis after cleaning up the data. 426 sets were contaminated, which gives a contamination rate of 0.93%. 3,484 cultures yielded a positive identification, which gives a rate of 7.6%. There were 151 different pathogens identified (after grouping some species). The number of times a pathogen was identified ranged from 1 to 763, with a median of 3 and a mean of 22.65.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Look at the frequency of contamination and of positive identification. Look at distribution of pathogens isolated.</span>
<span class="co">#I will be using the dataframe cultures, since that has been cleaned up. I will be using the Final_Report column for ease of readability, since this contains abbreviations of the isolates, and some of the species have been grouped together for ease of analysis.</span>
<span class="kw">table</span>(cultures$Contam)</code></pre></div>
<pre><code>## 
##    no   yes 
## 45324   426</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#rate of positive identification.</span>
<span class="kw">sum</span>(cultures$Final_Report!=<span class="st">&quot;Ng&quot;</span>)/<span class="kw">length</span>(cultures$Final_Report)</code></pre></div>
<pre><code>## [1] 0.07615301</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#df of positive cultures only that are not contamination</span>
cultures.pos &lt;-<span class="st"> </span>cultures %&gt;%
<span class="st">  </span><span class="kw">filter</span>(Final_Report!=<span class="st">&quot;Ng&quot;</span>) %&gt;%
<span class="st">  </span><span class="kw">filter</span>(Contam==<span class="st">&quot;no&quot;</span>)

<span class="co">#135 unique cultures</span>
<span class="kw">length</span>(<span class="kw">unique</span>(cultures.pos$Final_Report))</code></pre></div>
<pre><code>## [1] 135</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">by_isolate &lt;-<span class="st"> </span>cultures.pos %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Final_Report) %&gt;%
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">count=</span><span class="kw">n</span>()) %&gt;%
<span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(count))

<span class="kw">head</span>(by_isolate$count)</code></pre></div>
<pre><code>## [1] 763 360 272 237 226 196</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(by_isolate$count)</code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1.00    1.00    3.00   22.65    8.50  763.00</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#geom_histogram is for continuous data, geom_bar is for discrete data</span>
<span class="kw">ggplot</span>(by_isolate, <span class="kw">aes</span>(<span class="kw">reorder</span>(Final_Report,-count),count)) +
<span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">stat=</span><span class="st">&quot;identity&quot;</span>) +
<span class="st">  </span><span class="kw">theme_bw</span>() +<span class="st"> </span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">expand=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) +
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">text=</span><span class="kw">element_text</span>(<span class="dt">size=</span><span class="dv">10</span>),
        <span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">colour=</span><span class="st">&quot;black&quot;</span>,
                                   <span class="dt">angle=</span><span class="dv">90</span>,<span class="dt">hjust=</span><span class="dv">1</span>)) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Isolate&quot;</span>, 
       <span class="dt">y=</span><span class="st">&quot;Count&quot;</span>,
       <span class="dt">title=</span><span class="st">&quot;Frequency distribution of pathogen identification&quot;</span>) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept=</span><span class="kw">median</span>(by_isolate$count),<span class="dt">colour=</span><span class="st">&quot;red&quot;</span>)</code></pre></div>
<p><img src="final_project_Chen_files/figure-html/Descriptive%20statistics%20on%20isolation%20of%20pathogens-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#only 20 pathogens were isolated at least 20 times.</span>
by_isolate20 &lt;-<span class="st"> </span>by_isolate %&gt;%
<span class="st">  </span><span class="kw">filter</span>(count&gt;=<span class="dv">20</span>)

<span class="kw">ggplot</span>(by_isolate20, <span class="kw">aes</span>(<span class="kw">reorder</span>(Final_Report,-count),count)) +
<span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">stat=</span><span class="st">&quot;identity&quot;</span>) +
<span class="st">  </span><span class="kw">theme_bw</span>() +<span class="st"> </span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">expand=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) +
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">text=</span><span class="kw">element_text</span>(<span class="dt">size=</span><span class="dv">10</span>),
        <span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">colour=</span><span class="st">&quot;black&quot;</span>,
                                   <span class="dt">angle=</span><span class="dv">90</span>,<span class="dt">hjust=</span><span class="dv">1</span>)) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Isolate&quot;</span>, 
       <span class="dt">y=</span><span class="st">&quot;Count&quot;</span>,
       <span class="dt">title=</span><span class="st">&quot;Pathogens that were isolated at least 20 times&quot;</span>) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept=</span><span class="kw">median</span>(by_isolate20$count),<span class="dt">colour=</span><span class="st">&quot;red&quot;</span>)</code></pre></div>
<p><img src="final_project_Chen_files/figure-html/Descriptive%20statistics%20on%20isolation%20of%20pathogens-2.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cultures.pos.loc &lt;-<span class="st"> </span>cultures.pos %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Study_ID,Julian,Location,Final_Report) %&gt;%
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">count=</span><span class="kw">n</span>()) %&gt;%
<span class="st">  </span><span class="kw">ungroup</span>()

cultures.pos.loc &lt;-<span class="st"> </span><span class="kw">droplevels</span>(cultures.pos.loc)

cultures.pos.loc_subsets &lt;-<span class="st"> </span><span class="kw">split</span>(cultures.pos.loc,
                                  cultures.pos.loc$Study_ID)

<span class="co">#use split30days to group sets taken within 30d of each other</span>

cultures.pos.loc_30d &lt;-<span class="st"> </span><span class="kw">lapply</span>(cultures.pos.loc_subsets,split30days)
cultures.pos.loc_30d &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">do.call</span>(<span class="st">&quot;rbind&quot;</span>,cultures.pos.loc_30d))
cultures.pos.loc_30d %&lt;&gt;%
<span class="st">  </span><span class="kw">arrange</span>(Study_ID,Julian)

<span class="co">#get full record of bc taken for the Study_ID&#39;s with pos ID</span>
bc_30d_posID &lt;-<span class="st"> </span>bc_30d %&gt;%
<span class="st">  </span><span class="kw">filter</span>(Study_ID %in%<span class="st"> </span>cultures.pos.loc_30d$Study_ID)

bc_30d_posID &lt;-<span class="st"> </span><span class="kw">droplevels</span>(bc_30d_posID)

for (i in <span class="dv">1</span>:<span class="kw">nrow</span>(cultures.pos.loc_30d)){
  <span class="co">#subset by_Jul_posID so I only get the rows associated with Study_ID for the i-th row</span>
  x&lt;-bc_30d_posID[bc_30d_posID$Study_ID==cultures.pos.loc_30d[i,<span class="st">&quot;Study_ID&quot;</span>],]
  <span class="co">#get Julian date associated with pos ID</span>
  date &lt;-<span class="st"> </span>cultures.pos.loc_30d[i,<span class="st">&quot;Julian&quot;</span>]
  <span class="co">#get group associated with the Julian date assoc with pos ID</span>
  <span class="co">#get rows where Julian dates are greater than the specified Julian date within the grouping made by splitDates</span>
  y &lt;-<span class="st"> </span>x[x$Julian&gt;date,]
  g &lt;-<span class="st"> </span>x[x$Julian==date,<span class="st">&quot;group_30&quot;</span>][<span class="dv">1</span>] <span class="co">#there are multiple entries if it&#39;s polymicrobial but the group should be the same</span>
  z &lt;-<span class="st"> </span>y[y$group_30==g,]
  <span class="co">#add up the number of bc taken during that period</span>
  s &lt;-<span class="st"> </span><span class="kw">sum</span>(z$num_set)
  cultures.pos.loc_30d[i,<span class="st">&quot;num_set_postPosID&quot;</span>] &lt;-<span class="st"> </span>s
}
<span class="co">#test &lt;- culturesbyLoc_30d[1:6,]</span>


<span class="co">#make new df so I see number of cultures after 1st pos ID within a 30d period rather than for each subsequent day.</span>
cultures.pos.loc_30d_subsets &lt;-<span class="st"> </span><span class="kw">split</span>(cultures.pos.loc_30d,
                                   cultures.pos.loc_30d$Study_ID)


getFollowUpSets &lt;-<span class="st"> </span>function(df){
  <span class="co">#make sure data is sorted by Study_ID and Julian day</span>
  df %&lt;&gt;%<span class="st"> </span><span class="kw">arrange</span>(Study_ID,Julian)
  df_sub &lt;-<span class="st"> </span><span class="kw">split</span>(df,df$group_30)
  df_sub &lt;-<span class="st"> </span><span class="kw">lapply</span>(df_sub,function(df){
    minDate &lt;-<span class="st"> </span><span class="kw">min</span>(df$Julian)
    <span class="kw">return</span>(df[df$Julian==minDate,]) <span class="co">#get row with min Julian date for that grouping</span>
    <span class="co">#may be 2 rows if there was a polymicrobial infection</span>
  })
  newDF &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">do.call</span>(<span class="st">&quot;rbind&quot;</span>,df_sub))
  <span class="kw">return</span>(newDF)
}

numFollowUpCultures &lt;-<span class="st"> </span><span class="kw">lapply</span>(cultures.pos.loc_30d_subsets,
                              getFollowUpSets)
numFollowUpCultures &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">do.call</span>(<span class="st">&quot;rbind&quot;</span>,numFollowUpCultures)) 
numFollowUpCultures %&lt;&gt;%
<span class="st">  </span><span class="kw">arrange</span>(Study_ID,Julian)

<span class="co">#test whether number of follow-up cultures is linked to pathogen identified.</span>
numCulturesbyOrg &lt;-<span class="st"> </span>numFollowUpCultures %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Final_Report) %&gt;%
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">min=</span><span class="kw">min</span>(num_set_postPosID),
            <span class="dt">avg=</span><span class="kw">mean</span>(num_set_postPosID),
            <span class="dt">max=</span><span class="kw">max</span>(num_set_postPosID),
            <span class="dt">sd=</span><span class="kw">sd</span>(num_set_postPosID))

fit_bc &lt;-<span class="st"> </span><span class="kw">glm</span>(num_set_postPosID ~<span class="st"> </span>Final_Report +<span class="st"> </span>Location,<span class="dt">data=</span>numFollowUpCultures)
<span class="kw">summary</span>(fit_bc)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = num_set_postPosID ~ Final_Report + Location, data = numFollowUpCultures)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -9.291  -2.679  -0.696   1.535  41.095  
## 
## Coefficients: (2 not defined because of singularities)
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)               2.82746    7.23073   0.391 0.695843    
## Final_ReportAcispe       10.52746    3.90664   2.695 0.007145 ** 
## Final_ReportActinomy      1.48954    5.99994   0.248 0.803978    
## Final_ReportActodo       -1.44876    3.33549  -0.434 0.664116    
## Final_ReportActspe       -0.84763    3.92354  -0.216 0.828996    
## Final_ReportAna GNR(NP)  -2.88469    5.45693  -0.529 0.597163    
## Final_ReportAnaerob       0.46532    3.90809   0.119 0.905244    
## Final_ReportBaccergp     -3.03848    5.34522  -0.568 0.569839    
## Final_ReportBacfraG       2.52351    2.29775   1.098 0.272319    
## Final_ReportBacova       10.01306    3.96747   2.524 0.011741 *  
## Final_ReportBacspe       -1.29130    3.00413  -0.430 0.667389    
## Final_ReportBacthe        1.41001    3.35492   0.420 0.674357    
## Final_ReportCanalb        1.95124    1.97310   0.989 0.322905    
## Final_ReportCandub        2.84442    3.35294   0.848 0.396424    
## Final_ReportCangla        1.95713    2.07618   0.943 0.346050    
## Final_ReportCangui       -0.86989    3.06313  -0.284 0.776470    
## Final_ReportCankru       12.51378    5.38178   2.325 0.020231 *  
## Final_ReportCanlus        6.27826    5.25560   1.195 0.232490    
## Final_ReportCanparap      2.42501    2.20910   1.098 0.272546    
## Final_ReportCantro        7.39793    2.23584   3.309 0.000965 ***
## Final_ReportCapspe        3.48954    5.99994   0.582 0.560951    
## Final_ReportChrmen       -1.34763    5.26148  -0.256 0.797894    
## Final_ReportCitama        5.53995    4.01200   1.381 0.167590    
## Final_ReportCitFcomp      5.06733    4.02596   1.259 0.208402    
## Final_ReportCitkos       -0.23393    3.36638  -0.069 0.944610    
## Final_ReportCitro         0.27826    5.25560   0.053 0.957784    
## Final_ReportClodif       -3.41174    5.26614  -0.648 0.517200    
## Final_ReportClonps       -1.34763    5.26148  -0.256 0.797894    
## Final_ReportCloper       -1.40121    5.26795  -0.266 0.790295    
## Final_ReportCloram       -5.03848    5.34522  -0.943 0.346072    
## Final_ReportClosep        0.42902    3.37130   0.127 0.898759    
## Final_ReportClospe aerot  4.77666    5.26495   0.907 0.364458    
## Final_ReportCloter        2.58826    5.26614   0.491 0.623172    
## Final_ReportCns           1.62269    2.57369   0.630 0.528496    
## Final_ReportCorjei        0.27826    5.25560   0.053 0.957784    
## Final_ReportCryneo       -1.20138    4.21335  -0.285 0.775590    
## Final_ReportEC            0.47430    1.73122   0.274 0.784156    
## Final_ReportEc1          -0.72174    5.25560  -0.137 0.890796    
## Final_ReportEikcor        1.59879    5.26795   0.303 0.761568    
## Final_ReportEntaer       -0.57043    2.66047  -0.214 0.830266    
## Final_ReportEntavi       -0.22174    3.91564  -0.057 0.954851    
## Final_ReportEntcas       -2.82746    8.76707  -0.323 0.747125    
## Final_ReportEntcloasb     0.75124    1.85090   0.406 0.684905    
## Final_ReportEntfaeca      3.08434    1.79204   1.721 0.085490 .  
## Final_ReportEntfaeci      2.67749    1.79846   1.489 0.136817    
## Final_ReportEntgal       -1.91052    5.43771  -0.351 0.725391    
## Final_ReportFackl        -1.82746    5.26359  -0.347 0.728512    
## Final_ReportFinmag       -1.00338    5.32663  -0.188 0.850619    
## Final_ReportFusnuc       -1.60764    2.55120  -0.630 0.528719    
## Final_ReportFusob         0.96152    5.34522   0.180 0.857275    
## Final_ReportFusvar        0.66036    5.40163   0.122 0.902720    
## Final_ReportGNR           1.36054    3.00843   0.452 0.651179    
## Final_ReportGordo         1.15064    3.94267   0.292 0.770458    
## Final_ReportGpc           7.58826    5.26614   1.441 0.149865    
## Final_ReportGpcb          3.45942    4.02304   0.860 0.390020    
## Final_ReportGraadi        1.87250    3.40238   0.550 0.582185    
## Final_ReportHaeinf        0.47495    3.02139   0.157 0.875118    
## Final_ReportHaemas        4.98383    6.30835   0.790 0.429666    
## Final_ReportKleoxy        0.81549    2.07195   0.394 0.693958    
## Final_ReportKlepne        1.78829    1.74989   1.022 0.307020    
## Final_ReportKlepnepne     0.15510    3.33531   0.047 0.962917    
## Final_ReportKochrizo      2.65237    5.26148   0.504 0.614278    
## Final_ReportLaclactis    -2.40121    5.26795  -0.456 0.648608    
## Final_ReportLacto         2.61829    3.18055   0.823 0.410551    
## Final_ReportLismon        0.11531    5.45693   0.021 0.983145    
## Final_ReportMicfla        2.28885    6.31254   0.363 0.716978    
## Final_ReportMicmic       -1.55743    5.33354  -0.292 0.770333    
## Final_ReportMorcat        5.58826    5.26614   1.061 0.288832    
## Final_ReportMorlin       -1.72174    5.25560  -0.328 0.743272    
## Final_ReportMormor       -1.75563    5.31767  -0.330 0.741345    
## Final_ReportMycabs        2.17254    8.76707   0.248 0.804327    
## Final_ReportMycche        2.77666    5.26495   0.527 0.598026    
## Final_ReportNocfar       -4.41174    5.26614  -0.838 0.402338    
## Final_ReportPA            1.78121    1.83080   0.973 0.330797    
## Final_ReportPamuc         1.44469    5.29712   0.273 0.785108    
## Final_ReportPanagg       -2.15260    5.41174  -0.398 0.690875    
## Final_ReportPanspe        5.33809    4.09790   1.303 0.192953    
## Final_ReportPasmul       -1.09855    5.25971  -0.209 0.834593    
## Final_ReportPepasa        3.65237    5.26148   0.694 0.487712    
## Final_ReportPeptos       -0.52277    3.36414  -0.155 0.876537    
## Final_ReportPPPV         -3.03848    5.34522  -0.568 0.569839    
## Final_ReportPrebiv        4.50365    5.79656   0.777 0.437344    
## Final_ReportProacn       -2.82746    8.76707  -0.323 0.747125    
## Final_ReportPromir        0.28757    2.18303   0.132 0.895220    
## Final_ReportProstu        0.77666    5.26495   0.148 0.882751    
## Final_ReportProvpn       -0.77182    3.97233  -0.194 0.845976    
## Final_ReportPseflu        2.74448    5.31962   0.516 0.606010    
## Final_ReportPseput        2.71806    3.05473   0.890 0.373763    
## Final_ReportPsestu       -1.72174    5.25560  -0.328 0.743272    
## Final_ReportRaoorn       12.27826    5.25560   2.336 0.019647 *  
## Final_ReportRaoul        -2.03848    5.34522  -0.381 0.703001    
## Final_ReportRhoequ       12.59879    5.26795   2.392 0.016932 *  
## Final_ReportRhomus        0.93853    3.90759   0.240 0.810232    
## Final_ReportRotmuc        0.51710    2.65658   0.195 0.845703    
## Final_ReportRumgna        0.77666    5.26495   0.148 0.882751    
## Final_ReportSA            4.49336    1.72601   2.603 0.009349 ** 
## Final_ReportSalGD         2.17254    5.26359   0.413 0.679866    
## Final_ReportSalmo        -0.72174    5.25560  -0.137 0.890796    
## Final_ReportSalspD       -0.29051    3.82194  -0.076 0.939424    
## Final_ReportSerliq       10.06568    4.06112   2.479 0.013332 *  
## Final_ReportSerliqg      -3.03848    5.34522  -0.568 0.569839    
## Final_ReportSermar        0.66496    2.07528   0.320 0.748706    
## Final_ReportShewa         0.27826    5.25560   0.053 0.957784    
## Final_ReportStaaur        1.17254    5.26359   0.223 0.823758    
## Final_ReportStacapi       7.22190    2.65289   2.722 0.006579 ** 
## Final_ReportStaepi        3.11775    1.78436   1.747 0.080854 .  
## Final_ReportStahom        2.87656    2.34786   1.225 0.220752    
## Final_ReportStaint        2.55809    4.45370   0.574 0.565825    
## Final_ReportStalug        5.67291    3.04918   1.860 0.063070 .  
## Final_ReportStasim        0.96152    5.34522   0.180 0.857275    
## Final_ReportStawar        7.43503    3.39294   2.191 0.028625 *  
## Final_ReportStemal        2.46454    2.55762   0.964 0.335442    
## Final_ReportStrang        1.44723    3.35985   0.431 0.666734    
## Final_ReportStrcon        1.20239    2.66227   0.452 0.651611    
## Final_ReportStrdys        0.40476    2.80988   0.144 0.885487    
## Final_ReportStrep A       1.90350    2.44357   0.779 0.436148    
## Final_ReportStrep B       1.87978    1.94388   0.967 0.333732    
## Final_ReportStrep C       3.08948    5.43771   0.568 0.570037    
## Final_ReportStrgal        0.87179    3.02253   0.288 0.773068    
## Final_ReportStrinf       -5.23805    4.15020  -1.262 0.207156    
## Final_ReportStrint        0.57636    3.34357   0.172 0.863171    
## Final_ReportStrmitora     2.35017    2.28249   1.030 0.303386    
## Final_ReportStrpne        1.35020    2.05254   0.658 0.510784    
## Final_ReportStrsal       -1.72321    3.01721  -0.571 0.568023    
## Final_ReportStrsan        6.17254    5.26359   1.173 0.241160    
## Final_ReportSv            7.26660    3.01964   2.406 0.016262 *  
## Final_ReportTrichosp      1.95734    3.37937   0.579 0.562564    
## Final_ReportVeillspe     -0.54777    3.99385  -0.137 0.890934    
## LocationCCU               0.08306    7.17512   0.012 0.990765    
## LocationCICU             -0.85696    7.12071  -0.120 0.904228    
## LocationCRKP Internal    -3.32082    7.85938  -0.423 0.672716    
## LocationD6S               0.56991    7.10251   0.080 0.936059    
## LocationDIAY Dialysis 2   0.21403    7.37783   0.029 0.976862    
## LocationEDIP             -4.51342    7.88818  -0.572 0.567313    
## LocationER               -1.10572    7.03820  -0.157 0.875191    
## LocationFND4 Foundrs4OR  -1.98213    8.13273  -0.244 0.807489    
## LocationFP11              1.05723    7.18992   0.147 0.883123    
## LocationFP12             -1.47983    7.04291  -0.210 0.833613    
## LocationFP14             -1.00000    7.01115  -0.143 0.886607    
## LocationHCDS HUP Centr    1.50206    7.33259   0.205 0.837727    
## LocationHVCF Heart Fail  -7.32082    8.60575  -0.851 0.395116    
## LocationHVCS Cardiac Su        NA         NA      NA       NA    
## LocationHVCT Cardiac Tr  -4.78459    8.68534  -0.551 0.581820    
## LocationHVVD Heart Fail  -1.11631    7.85903  -0.142 0.887071    
## LocationIGRP 3701Mkt640  -1.91180    8.61837  -0.222 0.824486    
## LocationINCU              0.18871    7.85558   0.024 0.980839    
## LocationISRB              0.85383    7.17795   0.119 0.905334    
## LocationMICA              0.97099    7.07488   0.137 0.890861    
## LocationMICB              0.27109    7.07355   0.038 0.969435    
## LocationOPS TEMPORARY    -4.70724    8.64963  -0.544 0.586399    
## LocationPAT              -4.25247    8.71550  -0.488 0.625698    
## LocationPCC2 Chemo2       2.00269    7.30091   0.274 0.783897    
## LocationPCC4 Chemo4      -0.60678    7.85874  -0.077 0.938469    
## LocationPCH2 HemOnc2      2.21102    7.10485   0.311 0.755705    
## LocationPCH3 HemOnc3      0.69824    8.60578   0.081 0.935348    
## LocationPCH4 HemOnc4     -0.67486    7.15520  -0.094 0.924874    
## LocationPGIM GenIntMedP  -3.30176    7.85941  -0.420 0.674487    
## LocationPHIT HomeInfuse  -1.18546    7.29928  -0.162 0.871013    
## LocationPPAL Palliative        NA         NA      NA       NA    
## LocationR6               -1.57194    7.08664  -0.222 0.824495    
## LocationR6NE Ravdin6NE   -3.96857    7.45615  -0.532 0.594651    
## LocationR9               -1.27003    7.11740  -0.178 0.858409    
## LocationRADT Perelman    -2.73096    8.77505  -0.311 0.755690    
## LocationRENP Renal Pere  -4.39739    7.59691  -0.579 0.562808    
## LocationRIT3             -4.08949    7.60784  -0.538 0.590999    
## LocationRIT5             -2.27215    7.10537  -0.320 0.749193    
## LocationRP1              -2.48782    7.14687  -0.348 0.727828    
## LocationRP2A - Intensiv   0.66289    7.59718   0.087 0.930484    
## LocationRP2B - Intensiv   3.85356    7.71078   0.500 0.617336    
## LocationRP2C - Intensiv   5.24743    7.56739   0.693 0.488179    
## LocationRP2D - Intensiv  -3.55491    7.37891  -0.482 0.630062    
## LocationRP3               1.58428    7.05290   0.225 0.822307    
## LocationRP4               0.17592    7.09218   0.025 0.980215    
## LocationRP6               2.39588    7.05157   0.340 0.734094    
## LocationRP7               1.83278    7.05165   0.260 0.794981    
## LocationS10               3.37653    7.07379   0.477 0.633216    
## LocationS11              -0.42625    7.05349  -0.060 0.951823    
## LocationS12               0.92817    7.08572   0.131 0.895804    
## LocationS4S Silver 4      6.69824    7.85941   0.852 0.394246    
## LocationS7               -1.19097    7.11596  -0.167 0.867111    
## LocationS8               -5.33111    7.44579  -0.716 0.474141    
## LocationS9               -0.54696    7.46482  -0.073 0.941602    
## LocationSICA             -2.14367    7.23011  -0.296 0.766907    
## LocationSICB             -1.67618    7.12501  -0.235 0.814054    
## LocationSINA              1.80688    7.28074   0.248 0.804045    
## LocationSINB              3.95395    7.22380   0.547 0.584242    
## LocationSIRA              2.37090    7.27208   0.326 0.744461    
## LocationSIRB              1.65876    7.13417   0.233 0.816183    
## LocationTRNL LiverTrnsp  -0.61575    8.61113  -0.072 0.943007    
## LocationTU Transitional  -4.31700    7.60819  -0.567 0.570541    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for gaussian family taken to be 24.57808)
## 
##     Null deviance: 37820  on 1359  degrees of freedom
## Residual deviance: 28806  on 1172  degrees of freedom
## AIC: 8389.7
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit_isolate &lt;-<span class="st"> </span><span class="kw">aov</span>(num_set_postPosID ~<span class="st"> </span>Final_Report,
                   <span class="dt">data=</span>numFollowUpCultures)
<span class="kw">summary</span>(fit_isolate)</code></pre></div>
<pre><code>##                Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Final_Report  127   5452   42.93   1.634 2.97e-05 ***
## Residuals    1232  32369   26.27                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#look at avg # follow-up cultures based on pathogen</span>
<span class="kw">ggplot</span>(numFollowUpCultures,<span class="kw">aes</span>(<span class="kw">reorder</span>(Final_Report,-num_set_postPosID),num_set_postPosID)) +
<span class="st">  </span><span class="kw">geom_boxplot</span>() +
<span class="st">  </span><span class="kw">theme_bw</span>() +
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">text=</span><span class="kw">element_text</span>(<span class="dt">size=</span><span class="dv">10</span>),
        <span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">colour=</span><span class="st">&quot;black&quot;</span>,
                                   <span class="dt">angle=</span><span class="dv">90</span>,<span class="dt">hjust=</span><span class="dv">1</span>)) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Isolate&quot;</span>, 
       <span class="dt">y=</span><span class="st">&quot;Number of follow-up cultures&quot;</span>,
       <span class="dt">title=</span><span class="st">&quot;Distribution of follow-up cultures by isolate&quot;</span>)</code></pre></div>
<p><img src="final_project_Chen_files/figure-html/Look%20at%20number%20of%20bc%20after%20positive%20identification-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit_loc &lt;-<span class="st"> </span><span class="kw">glm</span>(count ~<span class="st"> </span>Location,<span class="dt">data=</span>by_loc)
<span class="kw">summary</span>(fit_loc)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = count ~ Location, data = by_loc)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -8.000  -1.489  -0.669   0.331  63.676  
## 
## Coefficients:
##                           Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              1.750e+00  1.815e+00   0.964 0.334917    
## LocationBKDS Penn Medic -2.500e-01  3.143e+00  -0.080 0.936610    
## LocationCCU              2.778e+00  1.840e+00   1.510 0.131137    
## LocationCICU             1.081e+00  1.824e+00   0.593 0.553356    
## LocationCIRG Dr Cirigli -5.000e-01  2.029e+00  -0.246 0.805357    
## LocationCR6             -7.500e-01  4.058e+00  -0.185 0.853374    
## LocationCRKP Internal   -4.167e-01  2.772e+00  -0.150 0.880527    
## LocationCTEO Cath EPS    3.250e+00  2.567e+00   1.266 0.205425    
## LocationCTEP Cath EPS   -3.500e-01  2.435e+00  -0.144 0.885702    
## LocationD1               2.500e-01  4.058e+00   0.062 0.950877    
## LocationD6S              1.522e+00  1.827e+00   0.833 0.404917    
## LocationDERP Dermatolog -7.500e-01  3.143e+00  -0.239 0.811419    
## LocationDIAL OP Dial2Wh -4.167e-01  2.772e+00  -0.150 0.880527    
## LocationDIAY Dialysis 2  2.368e+00  2.017e+00   1.174 0.240487    
## LocationDL4N Dulles 4 N -8.333e-02  2.772e+00  -0.030 0.976019    
## LocationDL4S Dulles 4 S  2.500e-01  3.143e+00   0.080 0.936610    
## LocationDUL4 Dulles 4OR  2.250e+00  4.058e+00   0.554 0.579276    
## LocationEDIP            -2.852e-01  1.865e+00  -0.153 0.878472    
## LocationENDO Endoscopy  -7.500e-01  4.058e+00  -0.185 0.853374    
## LocationER              -8.112e-02  1.816e+00  -0.045 0.964373    
## LocationFND4 Foundrs4OR  3.625e+00  2.223e+00   1.631 0.102929    
## LocationFP11             1.045e+00  1.829e+00   0.571 0.567678    
## LocationFP12             7.725e-01  1.817e+00   0.425 0.670824    
## LocationFP14             7.390e-01  1.817e+00   0.407 0.684285    
## LocationGDIO IR Ground   2.500e+00  2.567e+00   0.974 0.330033    
## LocationGDIP IR Ground  -5.000e-01  2.567e+00  -0.195 0.845540    
## LocationGEHV Geriatrics -7.500e-01  4.058e+00  -0.185 0.853374    
## LocationGFIO IR Neuro G  4.250e+00  4.058e+00   1.047 0.294976    
## LocationGFIP IR Neuro G  2.500e-01  4.058e+00   0.062 0.950877    
## LocationGI Gastro3Dul   -5.500e-01  2.435e+00  -0.226 0.821291    
## LocationGIMR General In  2.500e-01  4.058e+00   0.062 0.950877    
## LocationGWOU Ground  Wh -7.500e-01  4.058e+00  -0.185 0.853374    
## LocationHCDS HUP Centr   2.250e-01  1.903e+00   0.118 0.905903    
## LocationHVCA ADULT CONG -5.000e-01  2.567e+00  -0.195 0.845540    
## LocationHVCC Cardiology -7.500e-01  2.772e+00  -0.271 0.786744    
## LocationHVCE EP         -7.500e-01  4.058e+00  -0.185 0.853374    
## LocationHVCF Heart Fail  5.833e-01  2.343e+00   0.249 0.803381    
## LocationHVCK Consultati -5.962e-01  2.075e+00  -0.287 0.773918    
## LocationHVCO PRE-OP     -7.500e-01  3.143e+00  -0.239 0.811419    
## LocationHVCS Cardiac Su -7.500e-01  4.058e+00  -0.185 0.853374    
## LocationHVCT Cardiac Tr -1.293e-01  1.936e+00  -0.067 0.946746    
## LocationHVCV Vascular S  2.500e-01  4.058e+00   0.062 0.950877    
## LocationHVVD Heart Fail  2.500e-01  2.017e+00   0.124 0.901362    
## LocationIDSP Infectious -2.071e-01  1.916e+00  -0.108 0.913895    
## LocationIGRP 3701Mkt640 -4.062e-01  1.925e+00  -0.211 0.832851    
## LocationIMPT PennIntMed -2.167e-01  2.043e+00  -0.106 0.915521    
## LocationINCU             1.698e+00  1.837e+00   0.924 0.355354    
## LocationINUR Radnor Inf -3.750e-01  2.223e+00  -0.169 0.866023    
## LocationISRA             1.750e+00  3.143e+00   0.557 0.577719    
## LocationISRB             3.331e+00  1.872e+00   1.779 0.075297 .  
## LocationLNGP Pulmonary  -5.000e-01  2.096e+00  -0.239 0.811419    
## LocationLNGT Transplant -5.000e-01  2.223e+00  -0.225 0.822018    
## LocationMCDS HUP MicDS  -4.167e-01  2.772e+00  -0.150 0.880527    
## LocationMICA             3.175e+00  1.829e+00   1.736 0.082625 .  
## LocationMICB             3.533e+00  1.829e+00   1.931 0.053452 .  
## LocationNEUS Neurology   2.500e-01  4.058e+00   0.062 0.950877    
## LocationOAPU OPAmbuProc -7.000e-02  1.955e+00  -0.036 0.971432    
## LocationONCR Radnor Onc -2.500e-01  2.147e+00  -0.116 0.907318    
## LocationONRL Radnor Onc -7.500e-01  4.058e+00  -0.185 0.853374    
## LocationOPEC Paranatal  -2.500e-01  3.143e+00  -0.080 0.936610    
## LocationOPS TEMPORARY   -2.609e-01  1.841e+00  -0.142 0.887292    
## LocationOUT OutsidePhys  9.615e-02  2.075e+00   0.046 0.963046    
## LocationOXIR XrayIntrvn  2.500e-01  2.772e+00   0.090 0.928144    
## LocationP1DS PCAM 1 Eas  2.500e-01  4.058e+00   0.062 0.950877    
## LocationP2DS PCAM2 West -7.500e-01  4.058e+00  -0.185 0.853374    
## LocationPACU             1.750e+00  2.343e+00   0.747 0.455115    
## LocationPAT             -2.500e-01  2.343e+00  -0.107 0.915025    
## LocationPCC2 Chemo2     -3.465e-01  1.877e+00  -0.185 0.853578    
## LocationPCC3 Chemo3     -5.962e-01  2.075e+00  -0.287 0.773918    
## LocationPCC4 Chemo4     -3.100e-01  1.955e+00  -0.159 0.873987    
## LocationPCER Prlmn4Endo  2.500e-01  4.058e+00   0.062 0.950877    
## LocationPCGO GynOnc3    -8.333e-02  2.343e+00  -0.036 0.971627    
## LocationPCH2 HemOnc2     8.007e-03  1.828e+00   0.004 0.996505    
## LocationPCH3 HemOnc3    -2.763e-01  1.877e+00  -0.147 0.882992    
## LocationPCH4 HemOnc4    -1.221e-01  1.857e+00  -0.066 0.947567    
## LocationPCHP Heme Onc 3 -5.000e-01  2.567e+00  -0.195 0.845540    
## LocationPCNO NeurOnc    -7.500e-01  3.143e+00  -0.239 0.811419    
## LocationPCS4 SurgEOS4    2.500e-01  4.058e+00   0.062 0.950877    
## LocationPCSR Perelman 3 -7.500e-01  3.143e+00  -0.239 0.811419    
## LocationPEC             -8.333e-02  2.772e+00  -0.030 0.976019    
## LocationPGIM GenIntMedP -3.500e-01  2.435e+00  -0.144 0.885702    
## LocationPHIT HomeInfuse  2.727e-01  1.896e+00   0.144 0.885596    
## LocationPPAL Palliative  2.500e-01  4.058e+00   0.062 0.950877    
## LocationR6               1.099e+00  1.824e+00   0.602 0.546903    
## LocationR6NE Ravdin6NE   4.778e-01  1.860e+00   0.257 0.797274    
## LocationR9               8.910e-01  1.826e+00   0.488 0.625658    
## LocationRAD 1 Silverste -5.000e-01  2.567e+00  -0.195 0.845540    
## LocationRADT Perelman   -8.333e-02  2.343e+00  -0.036 0.971627    
## LocationRAV4 Ravdin 4OR  2.500e-01  4.058e+00   0.062 0.950877    
## LocationRENP Renal Pere  1.277e-10  2.096e+00   0.000 1.000000    
## LocationRHEP Rheumatolo -4.423e-01  2.075e+00  -0.213 0.831230    
## LocationRIT3            -3.070e-01  1.860e+00  -0.165 0.868933    
## LocationRIT4             1.196e-01  1.966e+00   0.061 0.951513    
## LocationRIT5             1.565e+00  1.826e+00   0.857 0.391343    
## LocationRP1              9.314e-01  1.831e+00   0.509 0.610936    
## LocationRP2A - Intensiv  2.719e+00  1.925e+00   1.412 0.157849    
## LocationRP2B - Intensiv  1.995e+00  1.890e+00   1.055 0.291383    
## LocationRP2C - Intensiv  1.622e+00  1.897e+00   0.855 0.392604    
## LocationRP2D - Intensiv  1.807e+00  1.873e+00   0.965 0.334673    
## LocationRP3              3.574e+00  1.822e+00   1.962 0.049773 *  
## LocationRP4              1.552e+00  1.823e+00   0.851 0.394634    
## LocationRP6              4.160e+00  1.822e+00   2.283 0.022432 *  
## LocationRP7              5.001e+00  1.823e+00   2.743 0.006103 ** 
## LocationRVPR Ravdin 4 P  1.250e+00  3.143e+00   0.398 0.690882    
## LocationS10              2.438e+00  1.822e+00   1.338 0.180799    
## LocationS11              1.098e+00  1.818e+00   0.604 0.545914    
## LocationS12              1.141e+00  1.822e+00   0.626 0.531232    
## LocationS4S Silver 4    -5.500e-01  2.147e+00  -0.256 0.797851    
## LocationS7               5.654e-01  1.830e+00   0.309 0.757350    
## LocationS8              -5.769e-02  1.906e+00  -0.030 0.975848    
## LocationS9               9.207e-01  1.829e+00   0.503 0.614768    
## LocationSGYN SpecGyn    -7.500e-01  4.058e+00  -0.185 0.853374    
## LocationSICA             4.099e+00  1.864e+00   2.199 0.027867 *  
## LocationSICB             4.111e+00  1.865e+00   2.205 0.027477 *  
## LocationSINA             4.955e+00  1.873e+00   2.645 0.008179 ** 
## LocationSINB             7.250e+00  1.960e+00   3.699 0.000218 ***
## LocationSIRA             4.164e+00  1.876e+00   2.219 0.026495 *  
## LocationSIRB             4.594e+00  1.871e+00   2.456 0.014073 *  
## LocationSOB SpecOB 3701 -7.500e-01  4.058e+00  -0.185 0.853374    
## LocationSTD Suite D     -1.346e-01  1.883e+00  -0.071 0.943018    
## LocationTRNL LiverTrnsp -8.333e-02  2.772e+00  -0.030 0.976019    
## LocationTRNM LivKidPan  -6.250e-01  2.223e+00  -0.281 0.778567    
## LocationTSGN Transplant -7.500e-01  4.058e+00  -0.185 0.853374    
## LocationTSLP Transplant -8.333e-02  2.772e+00  -0.030 0.976019    
## LocationTU Transitional -1.865e-01  1.829e+00  -0.102 0.918787    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for gaussian family taken to be 13.17415)
## 
##     Null deviance: 230197  on 15294  degrees of freedom
## Residual deviance: 199852  on 15170  degrees of freedom
## AIC: 82966
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit_loc_aov &lt;-<span class="st"> </span><span class="kw">aov</span>(count ~<span class="st"> </span>Location,<span class="dt">data=</span>by_loc)
<span class="kw">summary</span>(fit_loc_aov)</code></pre></div>
<pre><code>##                Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Location      124  30345  244.72   18.58 &lt;2e-16 ***
## Residuals   15170 199852   13.17                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Based on a linear regression, the following pathogens are statistically significant in the model: Sv, Stawar,STACAPI, Serliq, SA, Rhoequ, Raoorn, CANTRO, Cankru, Bacova,ACISPE.</p>
<p>Based on a linear regression, the following locations are statistically significant in a model for predicting number of bc in a 30-day period: MICB, RP6, RP7, SICA, SICB, SINA, SINB, SIRA, SIRB</p>
<p>Look at just the pathogens that were statistically significantly associated with number of follow-up cultures.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sigIsolate &lt;-<span class="st"> </span>numFollowUpCultures %&gt;%
<span class="st">  </span><span class="kw">filter</span>(Final_Report==<span class="st">&quot;Sv&quot;</span> |<span class="st"> </span>Final_Report==<span class="st">&quot;Stawar&quot;</span> |<span class="st"> </span>Final_Report==<span class="st">&quot;Stacapi&quot;</span> |<span class="st"> </span>Final_Report==<span class="st">&quot;Serliq&quot;</span> |<span class="st"> </span>Final_Report==<span class="st">&quot;SA&quot;</span> |<span class="st"> </span>Final_Report==<span class="st">&quot;Rhoequ&quot;</span> |<span class="st"> </span>Final_Report==<span class="st">&quot;Raoorn&quot;</span> |<span class="st"> </span>Final_Report==<span class="st">&quot;Cantro&quot;</span> |<span class="st"> </span>Final_Report==<span class="st">&quot;Cankru&quot;</span> |<span class="st"> </span>Final_Report==<span class="st">&quot;Bacova&quot;</span> |<span class="st"> </span>Final_Report==<span class="st">&quot;Acispe&quot;</span>)

<span class="kw">ggplot</span>(sigIsolate,<span class="kw">aes</span>(<span class="kw">reorder</span>(Final_Report,-num_set_postPosID),num_set_postPosID)) +
<span class="st">  </span><span class="kw">geom_boxplot</span>() +
<span class="st">  </span><span class="kw">theme_bw</span>() +
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">text=</span><span class="kw">element_text</span>(<span class="dt">size=</span><span class="dv">10</span>),
        <span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">colour=</span><span class="st">&quot;black&quot;</span>,
                                   <span class="dt">angle=</span><span class="dv">90</span>,<span class="dt">hjust=</span><span class="dv">1</span>)) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Isolate&quot;</span>, 
       <span class="dt">y=</span><span class="st">&quot;Number of follow-up cultures&quot;</span>,
       <span class="dt">title=</span><span class="st">&quot;Distribution of follow-up cultures for significant pathogens in model&quot;</span>)</code></pre></div>
<p><img src="final_project_Chen_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">top20 &lt;-<span class="st"> </span>cultures.pos.loc_30d %&gt;%
<span class="st">  </span><span class="kw">filter</span>(Final_Report %in%<span class="st"> </span>by_isolate20$Final_Report)

fit_top20_aov &lt;-<span class="st"> </span><span class="kw">aov</span>(num_set_postPosID ~<span class="st"> </span>Final_Report,<span class="dt">data=</span>top20)
<span class="kw">summary</span>(fit_top20_aov)</code></pre></div>
<pre><code>##                Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Final_Report   19   6506   342.4   9.964 &lt;2e-16 ***
## Residuals    1804  61992    34.4                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#Only EC is statistically significant but it doesn&#39;t have the highest average or the highest max...is this giving me what I think it is??</span>
fit_top20 &lt;-<span class="st"> </span><span class="kw">glm</span>(num_set_postPosID ~<span class="st"> </span>Final_Report,<span class="dt">data=</span>top20)
<span class="kw">summary</span>(fit_top20)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = num_set_postPosID ~ Final_Report, data = top20)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -10.939   -3.758   -1.288    2.174   42.174  
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)            6.46667    1.51357   4.272 2.03e-05 ***
## Final_ReportCanalb    -1.52072    1.79434  -0.848   0.3968    
## Final_ReportCangla    -1.50000    1.85374  -0.809   0.4185    
## Final_ReportCanparap  -0.96667    1.87568  -0.515   0.6064    
## Final_ReportCantro     4.47273    1.82544   2.450   0.0144 *  
## Final_ReportEC        -3.17828    1.55551  -2.043   0.0412 *  
## Final_ReportEntcloasb -2.54359    1.71806  -1.480   0.1389    
## Final_ReportEntfaeca   0.19259    1.59545   0.121   0.9039    
## Final_ReportEntfaeci   1.87023    1.57311   1.189   0.2346    
## Final_ReportKleoxy    -3.37576    1.96288  -1.720   0.0856 .  
## Final_ReportKlepne    -1.27992    1.58048  -0.810   0.4181    
## Final_ReportPA        -1.43889    1.66378  -0.865   0.3872    
## Final_ReportSA         1.35908    1.53589   0.885   0.3763    
## Final_ReportSermar    -2.30877    2.02473  -1.140   0.2543    
## Final_ReportStaepi     0.02366    1.58512   0.015   0.9881    
## Final_ReportStahom    -0.15897    2.22132  -0.072   0.9430    
## Final_ReportStemal     1.13333    2.00227   0.566   0.5714    
## Final_ReportStrep B   -2.70909    1.82544  -1.484   0.1380    
## Final_ReportStrmitora -1.06667    2.14052  -0.498   0.6183    
## Final_ReportStrpne    -2.21667    2.00227  -1.107   0.2684    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for gaussian family taken to be 34.3636)
## 
##     Null deviance: 68498  on 1823  degrees of freedom
## Residual deviance: 61992  on 1804  degrees of freedom
## AIC: 11650
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(top20,<span class="kw">aes</span>(<span class="kw">reorder</span>(Final_Report,-num_set_postPosID),num_set_postPosID)) +
<span class="st">  </span><span class="kw">geom_boxplot</span>() +
<span class="st">  </span><span class="kw">theme_bw</span>() +
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">text=</span><span class="kw">element_text</span>(<span class="dt">size=</span><span class="dv">10</span>),
        <span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">colour=</span><span class="st">&quot;black&quot;</span>,
                                   <span class="dt">angle=</span><span class="dv">90</span>,<span class="dt">hjust=</span><span class="dv">1</span>)) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Isolate&quot;</span>, 
       <span class="dt">y=</span><span class="st">&quot;Number of follow-up cultures&quot;</span>,
       <span class="dt">title=</span><span class="st">&quot;Distribution of follow-up cultures for top 20 pathogens&quot;</span>)</code></pre></div>
<p><img src="final_project_Chen_files/figure-html/unnamed-chunk-1-2.png" width="672" /></p>
<p>289 out of 11,737 patients had at least 20 blood cultures taken, which is 2.46% of the population. For this subpopulation, the number of sets taken ranged from 20 to 90, with a median of 26 and a mean of 30.86.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#get ID&#39;s for patients with more than 20 bc for FY2015</span>
ID_highuse &lt;-<span class="st"> </span>by_ID %&gt;%
<span class="st">  </span><span class="kw">filter</span>(count&gt;=<span class="dv">20</span>)

<span class="co">#289 patients with more than 20 bc taken.</span>
<span class="kw">nrow</span>(ID_highuse$Study_ID)</code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(ID_highuse$count)</code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   20.00   22.00   26.00   30.86   34.00   90.00</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#subset FY15_deID by these ID&#39;s so that I have the Julian information</span>
by_ID_highuse &lt;-<span class="st"> </span>FY15_deID[FY15_deID$Study_ID %in%<span class="st"> </span>ID_highuse$Study_ID,]
  
by_ID_highuse %&lt;&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Study_ID,Julian) %&gt;%
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">count=</span><span class="kw">n</span>())

<span class="co">#randomly sample 10 at a time from high utilisers and plot days when bc were taken</span>
s &lt;-<span class="st"> </span><span class="kw">sample</span>(by_ID_highuse$Study_ID,<span class="dv">10</span>,<span class="dt">replace=</span>F)
df &lt;-<span class="st"> </span>by_ID_highuse[by_ID_highuse$Study_ID %in%<span class="st"> </span>s,]

<span class="kw">ggplot</span>(df,<span class="kw">aes</span>(Julian,Study_ID)) +
<span class="st">  </span><span class="kw">theme_bw</span>() +<span class="st"> </span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Julian day&quot;</span>, 
       <span class="dt">y=</span><span class="st">&quot;Study_ID&quot;</span>,
       <span class="dt">title=</span><span class="st">&quot;Sets of bc taken per day for high utilizers&quot;</span>) +
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">alpha=</span>count)) +
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">50</span>,<span class="dv">100</span>,<span class="dv">150</span>,<span class="dv">200</span>,<span class="dv">250</span>,<span class="dv">300</span>,<span class="dv">350</span>,<span class="dv">400</span>))</code></pre></div>
<p><img src="final_project_Chen_files/figure-html/Identify%20high%20utilisers-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#look at high utilizers for those with at least 20 bc in a 30day period</span>
<span class="co">#use bc_30d_ID20</span>
<span class="co">#108 different Study_IDs, 116 entries total.</span>
bc_30d_ID20 &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(bc_30d_ID20)

List &lt;-<span class="st"> </span><span class="kw">list</span>()
<span class="co">#Listy &lt;- list()</span>
<span class="co">#get entries within 30d for highuse patients</span>
<span class="co">#NEED TO FIX. Missing Study_ID 4163 in bc_30d_ID20_highuse and maybe others.</span>
<span class="co">#bc_30d_ID20[43, &quot;Study_ID&quot;] gives 4163.</span>
<span class="co">#which(bc_30d[,&quot;Study_ID&quot;] %in% bc_30d_ID20[i, &quot;Study_ID&quot;]) gives 9786</span>
<span class="co">#bc_30d[9786,&quot;Study_ID&quot;] gives 4162...I don&#39;t get it.</span>
<span class="co">#somehow this got fixed after I converted bc_30d_ID20 to a dataframe rather than a grouped_df, tbl_df, tbl, and data.frame (output of using dplyr)</span>
for (i in <span class="dv">1</span>:<span class="kw">nrow</span>(bc_30d_ID20)){
  <span class="co">#which() gives which indices are true</span>
  x &lt;-<span class="st"> </span>bc_30d[bc_30d$Study_ID %in%<span class="st"> </span>bc_30d_ID20[i,<span class="st">&quot;Study_ID&quot;</span>],]
 <span class="co"># x &lt;- bc_30d[which(bc_30d[,&quot;Study_ID&quot;] %in% bc_30d_ID20[i, &quot;Study_ID&quot;]),]</span>
 <span class="co"># Listx[[i]] &lt;- x</span>
 <span class="co"># print(x)</span>
  <span class="co">#get only the rows within the same 30d grouping</span>
  y &lt;-<span class="st"> </span>x[<span class="kw">which</span>(x[,<span class="st">&quot;group_30&quot;</span>] %in%<span class="st"> </span>bc_30d_ID20[i,<span class="st">&quot;group_30&quot;</span>]),]
  List[[i]] &lt;-<span class="st"> </span>y
}

bc_30d_ID20_highuse =<span class="st"> </span><span class="kw">do.call</span>(rbind, List)

<span class="co"># x &lt;- do.call(rbind,Listx)</span>
<span class="co"># y &lt;- do.call(rbind,Listy)</span>


<span class="co">#randomly sample 10 at a time from high utilisers and plot days when bc were taken</span>
s &lt;-<span class="st"> </span><span class="kw">sample</span>(bc_30d_ID20_highuse$Study_ID,<span class="dv">10</span>,<span class="dt">replace=</span>F)
df &lt;-<span class="st"> </span>bc_30d_ID20_highuse[bc_30d_ID20_highuse$Study_ID %in%<span class="st"> </span>s,]
<span class="kw">ggplot</span>(df,<span class="kw">aes</span>(Julian,Study_ID)) +
<span class="st">  </span><span class="kw">theme_bw</span>() +
<span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">alpha=</span>num_set)) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Julian day&quot;</span>, 
       <span class="dt">y=</span><span class="st">&quot;Study_ID&quot;</span>,
       <span class="dt">title=</span><span class="st">&quot;Sets of bc taken within 30-day period for high utilizers&quot;</span>) +
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">50</span>,<span class="dv">100</span>,<span class="dv">150</span>,<span class="dv">200</span>,<span class="dv">250</span>,<span class="dv">300</span>,<span class="dv">350</span>,<span class="dv">400</span>))</code></pre></div>
<p><img src="final_project_Chen_files/figure-html/Identify%20high%20utilisers-2.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#look at distribution of locations for high utilizers to determine whether they are clustered on a certain floor. Divide by the total number of patients on that floor.</span>
<span class="co">#by_loc has number of patients by location</span>
<span class="co">#bc_30d_ID20_highuse shows the location for each high utilizer</span>

<span class="co">#get total number of patients per location</span>
by_loc_numpat &lt;-<span class="st"> </span>by_loc %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Location) %&gt;%
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">num_pat=</span><span class="kw">n</span>())

<span class="co">#locations of high utilizers</span>
<span class="co">#total count 176...</span>
highuse_loc &lt;-<span class="st"> </span>bc_30d_ID20_highuse %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Location) %&gt;%
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">count=</span><span class="kw">n_distinct</span>(Study_ID,group_30))

a &lt;-<span class="st"> </span>bc_30d_ID20_highuse %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Study_ID,group_30) %&gt;%
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">a=</span><span class="kw">n</span>())
<span class="kw">nrow</span>(a) <span class="co">#120</span></code></pre></div>
<pre><code>## [1] 120</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">b &lt;-<span class="st"> </span>bc_30d_ID20 %&gt;%
<span class="st">  </span><span class="kw">group_by</span>(Study_ID,group_30) %&gt;%
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">a=</span><span class="kw">n</span>())

<span class="kw">nrow</span>(b) <span class="co">#120 rows. 7 had multiple entries for group_30 (mostly 2, 1 had 3)</span></code></pre></div>
<pre><code>## [1] 120</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">c &lt;-<span class="st"> </span><span class="kw">anti_join</span>(b,a,<span class="dt">by=</span><span class="kw">c</span>(<span class="st">&quot;Study_ID&quot;</span>,<span class="st">&quot;group_30&quot;</span>))

<span class="co">#calculate proportion of high utilizers/total for each location</span>
highuse_loc &lt;-<span class="st"> </span><span class="kw">inner_join</span>(highuse_loc,by_loc_numpat) </code></pre></div>
<pre><code>## Joining, by = &quot;Location&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">highuse_loc %&lt;&gt;%
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">prop_highuse =</span> count/num_pat)

<span class="kw">ggplot</span>(highuse_loc,<span class="kw">aes</span>(<span class="kw">reorder</span>(Location,-prop_highuse),
                       prop_highuse)) +
<span class="st">  </span><span class="kw">geom_bar</span>(<span class="dt">stat=</span><span class="st">&quot;identity&quot;</span>) +
<span class="st">  </span><span class="kw">theme_bw</span>() +
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">text=</span><span class="kw">element_text</span>(<span class="dt">size=</span><span class="dv">10</span>),
        <span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">colour=</span><span class="st">&quot;black&quot;</span>,
                                   <span class="dt">angle=</span><span class="dv">90</span>,<span class="dt">hjust=</span><span class="dv">1</span>)) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;Location&quot;</span>, 
       <span class="dt">y=</span><span class="st">&quot;Propotion of high utilizers&quot;</span>,
       <span class="dt">title=</span><span class="st">&quot;Distribution of high utilizers&quot;</span>) </code></pre></div>
<p><img src="final_project_Chen_files/figure-html/Identify%20high%20utilisers-3.png" width="672" /></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
