---
title: "BMIN503/EPID600 Project"
author: "Katrina Bazemore"
output: 
  html_document:
    theme: paper 
    highlight: tango
---


***
Use this template to complete your project throughout the course. Your Final Project presentation will be based on the contents of this document. Replace the title/name above and text below with your own, but keep the headers. Feel free to change the theme and other display settings, but this is not required.

### Overview
Give a brief a description of your project and its goal(s), what data you are using to complete it, and what two faculty/staff in different fields you have spoken to about your project with a brief summary of what you learned from each person. Include a link to your final project GitHub repository.

>I plan to explore the relationship between adverse childhood experiences / stressful life events and risk of mild cognitive impairment and Alzheimer’s Disease (MCI/AD). These events may act as an effect modifier in between cognitive resilience and AD outcomes. I will assess both presence of MCI/AD and age of MCI/AD onset across levels of adverse/stressful experiences and proxy measures of cognitive resilience. The results of our research may inform management of stressful events to reduce risk of cognitive decline.

>[https://github.com/KSBazemore/BMIN503_Final_Project]


### Introduction 
Describe the problem addressed, its significance, and some background to motivate the problem.

Explain why your problem is interdisciplinary, what fields can contribute to its understanding, and incorporate background related to what you learned from meeting with faculty/staff.

> An estimated 5.8 million people had Alzheimer’s Dementia in the US in 20201. This condition presents a significant public health, economic, and emotional burden for those affected and their communities2. Many older adults do not exhibit clinical symptoms of dementia, despite substantial pathology3. Cognitive resilience is thought to explain variations in functioning between those with similar levels of pathology, with greater reserve protecting against cognitive decline4. Measures of cognitive resilience have been associated with reduced susceptibility to cognitive insults, including dementia, and traumatic brain injury5,6. However, cognitive resilience is difficult to measure and define with key proxies including education level and participation in mentally engaging activities in later life7,8. In contrast, negative life experiences such as depression and affective loss have been associated with earlier age of AD onset9. Stressful life events, particularly early stressful life events have previously been associated with greater susceptibility to poor mental health10. In mouse models, exposure to stress in early life was linked to decreased adult cognitive ability11. This evidence suggests a possible relationship between early childhood / lifetime stressors and increased risk of dementia.
	To approach this problem, I will use background knowledge and techniques from multiple fields. Research in the fields of neuroscience and psychology aid in understanding the mechanisms of MCI/AD and the role of stressful life events in future health. We know that individuals with similar MCI/AD pathology can have vastly difference cognitive performance, and that demographic, education, and behavioral factors explain some of the variation across pathology and cognitive performance. Psychology and medicine have identified long term mental and physical health consequences of adverse childhood experiences / stressful life events, and which events in particular lead to substantial stress. Knowledge of epidemiology can be used to design a study that explores the relationship between these three factors in a human population, calling also upon biostatistics to formally assess and test hypotheses. Finally, I can use bioinformatics tools to work with large datasets and create compelling visual displays of my results. 


### Methods
Describe the data used and general methodological approach. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why. 


### Results
Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

###References
>1.	Matthews KA, Xu W, Gaglioti AH, et al. Racial and ethnic estimates of alzheimer's disease and related dementias in the united states (2015-2060) in adults aged ≥65 years. Alzheimers Dement. 2019;15(1):17-24. Accessed Oct 6, 2022. doi: 10.1016/j.jalz.2018.06.3063.
2.	Wimo A, Guerchet M, Ali G, et al. The worldwide costs of dementia 2015 and comparisons with 2010. Alzheimers Dement. 2017;13(1):1-7. Accessed Oct 6, 2022. doi: 10.1016/j.jalz.2016.07.150.
3.	Schneider JA, Aggarwal NT, Barnes L, Boyle P, Bennett DA. The neuropathology of older persons with and without dementia from community versus clinic cohorts. J Alzheimers Dis. 2009;18(3):691-701. Accessed Oct 5, 2022. doi: 10.3233/JAD-2009-1227.
4.	Stern Y. Cognitive reserve. Neuropsychologia. 2009;47(10):2015-2028. Accessed Oct 6, 2022. doi: 10.1016/j.neuropsychologia.2009.03.004.
5.	Fay TB, Yeates KO, Taylor HG, et al. Cognitive reserve as a moderator of postconcussive symptoms in children with complicated and uncomplicated mild traumatic brain injury. J Int Neuropsychol Soc. 2010;16(1):94-105. Accessed Oct 6, 2022. doi: 10.1017/S1355617709991007.
6.	Poletti M, Emre M, Bonuccelli U. Mild cognitive impairment and cognitive reserve in parkinson's disease. Parkinsonism Relat Disord. 2011;17(8):579-586. Accessed Oct 6, 2022. doi: 10.1016/j.parkreldis.2011.03.013.
7.	 Wilson RS, Scherr PA, Schneider JA, Tang Y, Bennett DA. Relation of cognitive activity to risk of developing alzheimer disease. Neurology. 2007;69(20):1911-1920. Accessed Oct 5, 2022. doi: 10.1212/01.wnl.0000271087.67782.cb.
8.	Bennett DA, Wilson RS, Schneider JA, et al. Education modifies the relation of AD pathology to level of cognitive function in older persons. Neurology. 2003;60(12):1909-1915. Accessed Oct 5, 2022. doi: 10.1212/01.wnl.0000069923.64550.9f.
9.	Mejía S, Giraldo M, Pineda D, Ardila A, Lopera F. Nongenetic factors as modifiers of the age of onset of familial alzheimer's disease. Int Psychogeriatr. 2003;15(4):337-349. Accessed Oct 5, 2022. doi: 10.1017/s1041610203009591.
10.	Bale TL, Baram TZ, Brown AS, et al. Early life programming and neurodevelopmental disorders. Biol Psychiatry. 2010;68(4):314-319. Accessed Oct 5, 2022. doi: 10.1016/j.biopsych.2010.05.028.
11.	Sierksma ASR, Prickaerts J, Chouliaras L, et al. Behavioral and neurobiological effects of prenatal stress exposure in male and female APPswe/PS1dE9 mice. Neurobiol Aging. 2013;34(1):319-337. Accessed Oct 5, 2022. doi: 10.1016/j.neurobiolaging.2012.05.012.
