---
title: "BMIN503/EPID600 Project Madeleine"
author: "Madeleine Salwen"
output: 
  html_document:
    theme: paper 
    highlight: tango
---


***
Use this template to complete your project throughout the course. Your Final Project presentation will be based on the contents of this document. Replace the title/name above and text below with your own, but keep the headers. Feel free to change the theme and other display settings, but this is not required.

### Overview
Give a brief a description of your project and its goal(s), what data you are using to complete it, and what two faculty/staff in different fields you have spoken to about your project with a brief summary of what you learned from each person. Include a link to your final project GitHub repository.

The purpose of this project is to explore the relationship between dental health and Type 1 diabetes diagnosis in compairison to other factors affecting dental health. To do so, I will be using NHANES data from multiple years to gather enough data. My two advisors are Blanca Himes, PhD, Epidemiology, and Kira Nightingale from the epidemiology department who works in the dental school. Dr Himes has been very helpful in figuring out the question and how to use the NHANES data.  

### Introduction 
Describe the problem addressed, its significance, and some background to motivate the problem.

Explain why your problem is interdisciplinary, what fields can contribute to its understanding, and incorporate background related to what you learned from meeting with faculty/staff.

Diet is a vital tool in type 1 diabetes management in order to keep blood glucose levels near normal. Technological advancements in insulin therapies such as insulin pumps and flexible injection regiments have drastically improved the lifestyle of children and adults with diabetes. It is still necessary to calculate carbohydrate intake at each meal to account for the appropriate amount of insulin. A review by Rovner suggests that children with diabetes eat more processed foods because packaged items are appealing to facilitate carbohydrate counting. (1) In instances of hypoglycemia, fast acting carbohydrates are required to quickly raise glucose levels. Often, simple sugars like glucose tablets or skittles and other candy are used because they provide fast acting relief. (2) Overall, these dietary practices may affect dental health. Countless studies have shown the relationship between sugar intake and an increased risk of dental caries. Processed foods also tend to contain more sugar, or additives that can damage oral health. Lastly, the higher glucose levels in blood, is also true in saliva, creating an ideal breeding ground for bacteria in the mouth. (3) There is precedent for the relationship between diabetes and dental health, however, my research has only seen instances of Type 2 diabetes investigated. I am interested in specifically isolated Type 1 cases. 

This issue can be understood through an interdisciplinary approach. The issue must be investigated through a broader public health lens to account for factors such as access to dental care, or smoking status in addition to the clinical factors of dental outcomes. I will use the NHANES data set over multiple years, and practices of statistical models to investigate the data. Fields that can contribute to this understanding are epidemiological, statistical, dental, and endocrine. 

### Methods
Describe the data used and general methodological approach. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why. 


### Results
Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

###References

(1) Rovner AJ, Nansel TR. Are children with type 1 diabetes consuming a healthful diet?: a review of the current evidence and strategies for dietary change. Diabetes Educ. 2009 Jan-Feb;35(1):97-107. doi: 10.1177/0145721708326699. PMID: 19244565; PMCID: PMC2772111.

(2) Husband AC, Crawford S, McCoy LA, Pacaud D. The effectiveness of glucose, sucrose, and fructose in treating hypoglycemia in children with type 1 diabetes. Pediatr Diabetes. 2010 May;11(3):154-8. doi: 10.1111/j.1399-5448.2009.00558.x. Epub 2009 Aug 3. PMID: 19663922.

(3) Centers for Disease Control and Prevention. (2021, May 7). Diabetes and Oral Health. Centers for Disease Control and Prevention. Retrieved November 1, 2022, from https://www.cdc.gov/diabetes/managing/diabetes-oral-health.html 

