---
title: "BMIN503/EPID600 Project Template"
author: "Jessica Meeker"
output: 
  html_document:
    toc: false 
    depth: 3 
    theme: paper 
    highlight: tango
---
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 400)
```  
***
Use this template to complete your project throughout the course. Your Final Project presentation in class will be based on the contents of this document. Replace the title/name and text below with your own, but keep the headers.

### Overview
In this section, give a brief a description of your project and its goal, what data you are using to complete it, and what three faculty/staff in different fields you have spoken to about your project with a brief summary of what you learned from each person. Include a link to your final project GitHub repository.

Maternal mortality and morbidity rates have seen a decline globally; however, in the United States these numbers continue to rise, in particular among women of color. I will use Electronic Medical Record (EMR) data from a cohort of women in the University of Pennsylvania Health System (UPHS). The goal of this project is to perform exploratory statistical methods to describe the exposure and outcome variables in the data set and machine learning methods (Lasso) to create a model of neighborhood level stress in Philadelphia that predicts maternal mortality and morbidity. 

I spoke with Drs. Trevor Penning, Ray Bai & Mary Regina Boland about my project. With Dr. Penning I discussed the project from a more broad lens of environmental exposures, both natural and social. Dr. Bai was able to provide much needed insight into the methodology of logistic regression with a lasso penalty on the predictors. Dr. Boland and I discussed overall project context and some of the considerations necessary for which machine learning method to choose. 

[Github Repository](https://github.com/jemeeker10/BMIN503_Final_Project)

### Introduction 
In the first paragraph, describe the problem addressed, its significance, and some background to motivate the problem.

In the second paragraph, explain why your problem is interdisciplinary, what fields can contribute to its understanding, and incorporate background related to what you learned from meeting with faculty/staff.


### Methods
In the first paragraph, describe the data used and general methodological approach. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why. 


### Results
Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.
