---
title: "BMIN503 Project: Predicting Viable Stem Cells after Freeze-Thaw"
author: "Stephan Kadauke"
output: 
  html_document:
    theme: paper 
    highlight: tango
---
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 400)
```  

### Overview

Hematopoietic stem cells (HSCs) are generally thought of as resistant to freeze-thaw cycles, however we found that post-thaw viability of stem cells varies widely. The goal of this project is to use machine learning techniques to predict post-thaw HSC viability.


### Introduction 

Hematopoietic stem cell transplant is life-saving therapy for various malignant and non-malignant diseases. In autologous stem cell transplants, cells are collected from a patient prior to high-dose chemotherapy and reinfused at a later date. Therefore, stem cell products for autologous transplantation need to be cryopreserved and thawed before infusion. 

In the CHOP Cell and Gene Therapy Lab (CGTL), we found that the viability of stem cells after a freeze-thaw cycle varies widely. The question that the final project will address is whether a low post-thaw viability can be predicted from clinical and lab parameters that are available prior to cryopreservation. This could change management for patients at the time their stem cells are collected. 

I will use data from CHOP patients who have had autologous stem cell products collected in the CGTL since 2016. I will also use clinical parameters abstracted from patient charts. Thus, the project spans the disciplines of Pathology and Lab Medicine as well as Oncology. 

### Methods



Describe the data used and general methodological approach. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why. 


### Results

Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.
