---
title: "Using Childhood and Adulthood Stress Factors as Predictors for Tobacco/Nicotine Use"
subtitle: "BMIN503/EPID600 Final Project"
author: "Katie Cardone"
format: html
editor: visual
embed-resources: true
---

------------------------------------------------------------------------

Use this template to complete your project throughout the course. Your Final Project presentation will be based on the contents of this document. Replace the title/name above and text below with your own, but keep the headers. Feel free to change the theme and other display settings, although this is not required.

### Overview

Cigarette smoking is a major health problem in the United States, as it is the leading cause of preventable death. Many family-related problems/stress have been associated with increased smoking individually, but this study considers whether the combination of these risk factors in a machine learning approach can better predict smoking. This study will leverage data from the Behavioral Risk Factor Surveillance System 2022 survey, as this provides data on both family risk factors and tobacco use.

Link to github repository: [Github Repository](https://github.com/katiecardone26/BMIN503_Final_Project)

*Give a brief a description of your project and its goal(s), what data you are using to complete it, and what two faculty/staff in different fields you have spoken to about your project with a brief summary of what you learned from each person. Include a link to your final project GitHub repository.*

### Introduction

Cigarette smoking is the leading cause of preventable mortality^1^. 480,000 deaths per year in the United States are due to smoking^2^ and smokers die on average 10 years earlier compared to non-smokers^3^. Stress is a risk factor for smoking, as greater stress is associated with a higher odds of persistent smoking^4^. This includes family problems in the past year, which is particularly important as family problems doubles the odds of quitting failure^4^. Many studies have shown that a variety of family problems/stress factors in the home are associated with an increased prevalence of smoking. In one study, 81% of tobacco users had a family history of tobacco use^5^. Additionally, individuals with a history of child abuse are more likely to become smokers as adults^6^. More specifically, child sexual abuse predicted adolescent smoking frequency^7^. Maltreatment in childhood, including neglect and failure of caregivers to provide for child, is associated with smoking in adulthood^8^. Another study showed that substance use, including tobacco, was associated with past and present parental incarceration^9^. Parental divorce or separation in childhood was also associated with smoking in adulthood^10^.

Evidently, smoking is a major health problem and family issues individually seem to predict it. However, the project assesses whether the combination of these factors can better predict smoking. To properly create a model that answers this question, an interdisciplinary approach is most beneficial. This is a public health issue, so epidemiologists will provide insight on factors to consider when answering this question. Additionally, the outcome of interest is substance use, so psychiatrists can also provide useful knowledge. Last, this project will use a machine learning method, so computational biologists can provide insight on how to optimize the model.

*Describe the problem addressed, its significance, and some background to motivate the problem.*

*Explain why your problem is interdisciplinary, what fields can contribute to its understanding, and incorporate background related to what you learned from meeting with faculty/staff.*

### Methods

Describe the data used and general methodological approach. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why.

### Results

Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

### References

1.  Diseases and death. *Centers for Disease Control and Prevention* (2022). Available at: https://www.cdc.gov/tobacco/data_statistics/fact_sheets/fast_facts/diseases-and-death.html#:\~:text=Smoking%20is%20the%20leading%20cause%20of%20preventable%20death.&text=This%20is%20about%20one%20in,or%201%2C300%20deaths%20every%20day. (Accessed: 30th October 2023)

2.  U.S. Department of Health and Human Services. *The Health Consequences of Smoking-50 Years of Progress: A Report of the Surgeon General* (Department of Health and Human Services, Centers for Disease Control and Prevention, National Center for Chronic Disease Prevention and Health Promotion, Office on Smoking and Health, 2014).

3.  Jha, P. *et al.* 21st-century hazards of smoking and benefits of cessation in the United States. *New England Journal of Medicine* **368,** 341--350 (2013).

4.  Slopen, N. *et al.* Psychosocial stress and cigarette smoking persistence, cessation, and relapse over 9--10 years: A prospective study of middle-aged adults in the United States. *Cancer Causes & Control* **24,** 1849--1863 (2013).

5.  Pathak, R., Dwivedi, S., Agarwalla, R. & Ali, W. The intergenerational transmission of tobacco habit: Role of parents and the family. *Journal of Family Medicine and Primary Care* **5,** 373--377 (2016).

6.  Eve, S. G. *et al.* Relationship between child abuse and adult smoking. *Int J Psychiatry Med* **39,** 417--426 (2009).

7.  Kristman-Valente, A. N., Brown, E. C. & Herrenkohl, T. I. Child physical and sexual abuse and cigarette smoking in adolescence and adulthood. *Journal of Adolescent Health* **53,** 533--538 (2013).

8.  Taha, F., Galea, S., Hien, D. & Goodwin, R. D. Childhood maltreatment and the persistence of smoking: A longitudinal study among adults in the US. *Child Abuse & Neglect* **38,** 1995--2006 (2014).

9.  Davis, L. & Shlafer, R. J. Substance use among youth with currently and formerly incarcerated parents. *Children of Incarcerated Parents* **87,** 42--57 (2018).

10. Lindström, M. & Rosvall, M. Parental separation/divorce in childhood and tobacco smoking in adulthood: A population-based study. *Scandinavian Journal of Public Health* **48,** 657--666 (2019).

11. 
