---
title: "Identifying Patients in the Hospital with Mental Health Conditions"
author: "Christopher Snider"
output: 
  html_document:
    toc: false 
    depth: 3 
    theme: paper 
    highlight: tango
---
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 400)
```  

### Overview

> Mental health conditions are prevalent among patients admitted the hospital, but recognizing the symptoms can be challenging for members of the care team (Hansen et al., 2001). Undiagnosed mental health conditions can lead to disruptions in a patient's care and worse outcomes. This project intends to provide support to an ongoing program, Mental Health Engagement, Navigation, and Delivery (MEND), by using data from the electronic health records to better identify patients who could benefit from the intervention and enable them to begin receiving treatment earlier in their stay.


### Introduction 

> Mental health disorders account for substantial social and economic costs, representing 30% of the non-fatal disease burden and 10% of the overall disease burden, globally (Marquez & Saxena, 2016). In the United States, approximately 18% of adults experienced mental illness in the previous year (NIMH, 2016). An analysis by Greenberg et al. (2015) calculated that the economic burden of individuals with Major Depressive Disorder in the United States in 2010 was over $210 billion, with 47% attributed to direct medical and pharmaceutical costs and 48% attributed to workplace costs including absenteeism and reduced productivity at work.
The prevalence of depression, anxiety, and other mental health disorders is higher among those with chronic physical conditions (APMS, 2014). Mental health disorders can also exacerbate physical health conditions, thus raising total health care costs (APMS, 2014).  

> The MEND program is focusing on identifying patients in the inpatient setting, providing psychiatric consults and behavioral interventions, and connecting patients with treatment pathways after discharge. The team verifies patient eligibility mostly through chart review, which is inefficient and prevents them from reaching some patients needing treatment. Extracting data from the electronic health records could identify some patients needing to be seen by the psychiatric team immediately if they have high PHQ-9 scores indicating severe depression or if they have previously diagnosed suicidal ideation. However, other patients may have conditions that are harder to recognize. A machine learning approach could identify patterns in the data more quickly, reducing the burden of performing chart reviews on a large population and enabling the psychiatric care team to reach patients faster. The MEND program relies on individuals across multiple disciplines. An innovation and design team performed contextual inquiry to better understand the scope of the problem. The psychiatric care team works closely with the clinicians on the medicine service. Data analysts and econometricians are also supporting the evaluation of the program's impact.

### Methods
In the first paragraph, describe the data used and general methodological approach. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why. 


### Results
Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.
