---
title: "BMIN503/EPID600 Project"
author: Neil Dhopeshwarkar
output: 
  html_document:
    toc: false 
    depth: 3 
    theme: paper 
    highlight: tango
---
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 400)
```  
***
Use this template to complete your project throughout the course. Your Final Project presentation in class will be based on the contents of this document. Replace the title/name and text below with your own, but keep the headers.

### Overview
In this section, give a brief a description of your project and its goal, what data you are using to complete it, and what three faculty/staff in different fields you have spoken to about your project with a brief summary of what you learned from each person. Include a link to your final project GitHub repository.

This project will investigate factors associated with decreased effectiveness of immune checkpoint inhibitors in the treatment of metastatic melanoma.  Using Flatiron Health oncology EHR-derived data, I will evaluate the association of different types of factors (medical conditions, drugs, cancer characteristics, etc.) with decreased survival in metastatic melanoma patients being treated with immune checkpoint inhibitors, with an emphasis on immune-related factors.


### Introduction 
In the first paragraph, describe the problem addressed, its significance, and some background to motivate the problem.

In the second paragraph, explain why your problem is interdisciplinary, what fields can contribute to its understanding, and incorporate background related to what you learned from meeting with faculty/staff.

Immune checkpoint inhibitors, drugs that inhibit PD-1 and PD-L1 to reinvigorate the body's immune antitumor response, have drastically changed the treatment landscape of several types of cancers including advanced melanoma.  Though these treatments have demonstrated marked increases in cancer outcomes such as progression-free survival (PFS) and overall survival (OS), studies have suggested that certain patient factors hinder the clinical benefit of immune checkpoint inhibitors in the treatment of cancers.  For example, concomitant use of glucocorticoids (due to immunosuppresive effects) or antibiotics (due to disruption of gut microbia) was shown to decrease survival outcomes in patients treated with immune checkpoint inhibitors.  This project will explore the association of a variety of immune-related patient factors with decreased OS in advanced melanoma patients treated with immune checkpoint inhibitors.

Multiple disciplines can contribute to addressing this research question.  The data science/informatics data exploration and visualization techniques learned in this class will help to efficiently and simultaneously assess the effect of different patient factors on survival.  Concepts from epidemiology will help with the interpretation of results and their potential implications.  Finally, clinical medicine can link these results to possible biological explanations in order to assess the value in further assessment of one or several of these factors in a causal-aimed study.  Overall, this project could elucidate other potential factors associated with decreased effectiveness of immune checkpoint inhibitors which may be worth exploring further in the future.


### Methods
In the first paragraph, describe the data used and general methodological approach. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why. 


### Results
Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.
