---
title: "The Adult Impact of Childhood VCUGs"
subtitle: "BMIN503/EPID600 Final Project"
author: "Andrea McDonald"
format: html
editor: visual
number-sections: true
embed-resources: true
---

------------------------------------------------------------------------

## Overview {#sec-overview}

*Citations and references available upon request*

**An exploratory study on the adult impact of childhood VCUGs**

A Voiding Cystourethrogram (VCUG) is a diagnostic test that allows physicians to examine the urinary system, specifically the bladder and urethra. VCUGs are commonly performed in childhood to evaluate issues such as frequent urinary tract infections (UTIs), investigate abnormalities of the urinary system, or detect vesicoureteral reflux (a condition where urine flows backward from the bladder into the ureters).

The VCUG experience has been poorly documented in children; however, even less is known about the long-term impacts of the procedure. This project explores the prevalence and understanding of various sequelae among adults who underwent VCUG in childhood, while gaining insights into the lived experience of the procedure from the patient perspective.

To explore and understand these relationships, I use data collected from my own study "2023 VCUG Survey" (IRB Protocol #852632), in which responses were collected over nine months (January 2023 - September 2023). Respondents completed a 15-minute survey about their physical and mental health, and were categorized into two groups ("VCUG" and "control") based on whether they did or did not report undergoing at least one VCUG in childhood (\<18 years). I worked with Dr Bonnie Offit, MD and Scott Appel, Co-Director at the University of Pennsylvania Biostatistics Analysis Center, for this project. The preliminary findings from this project will inform next steps I will take in Spring 2024 as I look to publish my findings. For example, I must decide whether or not to incorporate findings from the control group in my published deliverable, or move this project forward as an exploratory research study focusing only on the VCUG group. This will depend on the presence of confounders, sample size, data collection methods, and physician input. Dr. Offit is serving as a physician consultant, advising on the nuances of VCUG ordering and the clinical perspective. Scott has opined on various ways to analyze the data, what might be criticized, and which statistical tests (if any) would be most appropriate for the variables collected.

[**Link to final project GitHub repository**](https://github.com/dremcdonald/DSFinalProject2023)

## Introduction {#sec-introduction}

**Introduction**

Urinary tract infections (UTIs) are one of the most common bacterial infections in childhood, affecting approximately 7.8% of children \<19 years with urinary symptoms and/or fever (16). Over 30% of children with UTI will have recurrent UTI (15). A common risk factor for recurrence is vesicoureteral reflux (VUR), a pediatric condition in which urine flows backward from the bladder back into the ureters and/or kidneys (16). VUR is important to identify as it leads to an increased risk of persistent and/or recurrent UTIs, and if left untreated, in some cases can cause kidney damage (6), though most children don\'t have long-term problems from VUR as the condition frequently resolves on its own (17).

The Voiding Cystourethrogram (VCUG) is the primary diagnostic test used to diagnose VUR. As of 2021, there were approximately 73 million children under 18 in the United States (14). From these figures, we can estimate conservatively that around 2 million children in the United States per year with recurrent UTIs will undergo at least one VCUG. This estimate does not consider a) cases where multiple VCUGs are performed on the same child within the year, and b) cases where a child undergoes VCUG after only one UTI. More broadly, between 2 and 5 million children per year in the United States may become candidates for VCUG.

**Lack of standardized VCUG protocols**

VCUGs are ordered by many specialists and primary care providers, including pediatricians, family practitioners, nephrologists, hospitalists, emergency department physicians, and urologists (18), but protocols and standards for this test vary widely. In 2016, the AAP attempted to publish a consensus on how to perform and interpret the VCUG, acknowledging that an official protocol has not been updated since 1985 (18). Still, no evidence-based or enforced protocol for VCUG exists (18). The AAP acknowledged in 2016 that VCUG is one of the only imaging studies in existence that is regularly performed without national or international consensuses on process, raising concerns about patient safety and proper data/outcomes comparisons. It also notes that the VCUG can be traumatizing for patients and parents alike, though it does not detail to what extent (18).

**The Marketing of VCUG**

*I include in the appendix a transcript of two judges\' factual description of the VCUG after viewing a medical videotape of a standard VCUG procedure (20).*

Most institutions describe VCUG as minimally invasive, painless, and without risks outside of standard imaging radiation exposure. However, as early as 1998, VCUGs were identified as potentially highly traumatic experiences. In 2004, VCUG patients were recruited as proxies for childhood sexual abuse victims (4) because \"even doctors administering the procedure admit that in many ways the VCUG procedure is similar to sexual assault on a child" (5). An increasing volume of literature warns that the potential psychological trauma resulting from VCUG is analogous with that of a violent rape (19). A growing number of adults (both male and female) are advocating against the procedure and begging for alternatives, citing that, years or even decades later, they refuse to seek healthcare, experience broken relationships, and battle thoughts of suicide as a direct result of having undergone VCUG as children (8).

Until now, no study has ever examined adults who underwent VCUG in childhood to assess whether the procedure has materially affected their lives.

## Methods {#sec-methods}

To preserve respondent confidentiality, I will not be uploading the raw data file to GitHub. I will, however, include the data dictionary, as well as the recruitment flyer. The raw (de-identified) data file is available upon request, only to those who require access for the purposes of validating the project and/or study.

**The main goals of this project are to:**

a\) Define two cohorts -- VCUG and control;

b\) Perform exploratory data analysis to inform whether the sample collected allows for statistical analysis between the VCUG and control groups;

c\) Perform chosen analyses on VCUG and/or control group(s).

##### [*Describe the data used and general methodological approach used to address the problem described in the @sec-introduction. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why.*]{.underline}

## Results {#sec-results}

Describe your results and include relevant tables, plots, and code/comments used to obtain them. You may refer to the @sec-methods as needed. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

## Conclusion

This the conclusion. The @sec-results can be invoked if you'd like.
