---
title: "Efficient Translation of Autism Genetics Research for Clinical Decision Support""
author: "Olivia J. Veatch"
output: 
  html_document:
    toc: false 
    depth: 3 
    theme: paper 
    highlight: tango
---
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 400)
```  
***
Use this template to complete your project throughout the course. Your Final Project presentation in class will be based on the contents of this document. Replace the title/name and text below with your own, but leave the headers.

### Overview
This project will develop an automated method for prioritizing clinically actionable results from genetic studies of autism spectrum disorders (ASD). The goal is to rapidly deliver important information in such a manner that the clinician can be more informed when making key decisions regarding the benefits of ordering genetic testing for a patient.
There are currently hundreds of genetic variants implicated in risk for complex human disease and the list is continually growing. In order to understand how genetic information can be useful to informing treatment, it is important to identify efficient ways to sort through the sea of association study results to determine clinically-actionable genes. I will use data form DisGeNET, Genotype-Tissue Expression database, International Mouse Phenotyping Consortium, and Pharos Drug Ontology to automate a gene prioritization pipeline useful to identification of clinically-actionable candidate genes for Autism Spectrum Disorders. Clinically-actionable genetic information will be defined as any functionally relevant (e.g., expressed in brain, causes an ASD-related phenotype when knocked-out in mice), ASD-associated gene with evidence indicating that variation in the gene may influence how a patient will respond to a drug. After speaking with Ben Voight, Associate Professor of Genetics, I was able to refine the specific challenges I am interested in addressing. As there are numerous challenges limiting the ability of clinicians to begin incorporating genetic information into treatment, he helped me identify that I want to address 2 specific challenges, the "immediacy" gap and the "knowledge"" gap. Following discussions with Allan Pack, Professor of Medicine in the Center for Sleep and Circadian Neurobiology, I was able to identify the specific clinical decision I want to support with the development of the approach (i.e., help clinicians to determine if genetic testing will be useful to informing their decisions when planning treatment). Furthermore, Jason Moore, Professor of Biostatistics and Director of the Institute for Informatics, helped me to identify the databases that would be useful to the automation of the approach and offered advice on how to validate the approach. Include a link to your final project GitHub repository.


### Introduction 
It is well-established that genomic factors influence risk for ASD. Rapid advancements in genomics technologies have helped generate massive amounts of new knowledge on the genetic factors contributing to ASD. Although discovery continues to be important, it is crucial to understand how currently implicated genes can help immediately inform diagnosis and treatment. While integration of genetics and genomics into precision medicine has been successful in cancer prediction and therapy, the need to incorporate these data into non-oncological practice of medicine has been noted as an area that requires particular attention. Further, much of the focus regarding identification of clinically actionable genetic information is on interpreting results from previously generated data. Although the cost of generating new data is steadily decreasing, there remain barriers. These include limited access to necessary resources and knowledge gaps among clinicians regarding the benefits/limitations of genetic testing for many complex disorders. As incorporating genomic technology into patient care is largely dependent on clinicians’ perspectives of its utility, it is important to identify ways to better inform clinicians about relevant genetic findings beneficial to optimizing treatment.
There are excellent resources available that allow for identifying clinically useful ways to interpret information from genetic studies; however, many clinicians have limited opportunity to spend time processing the extensive amounts of data available, and rapidly being generated. While there are numerous challenges limiting the clinical utility of information from genetic studies in ASD, the proposed project addresses two key issues: 1) the 'immediacy' gap which will be bridged by developing an efficient way to sort through genetic data to identify information about known and potentially clinically actionable genes, and 2) the 'processing' gap which will be bridged by working to validate and automate the prioritization method so that the validated approach can be adapted for future applications in other complex disorders and diseases.


### Methods
In the first paragraph, describe the data used and general methodological approach. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why. 


### Results
Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.
