---
title: "BMIN503/EPID600 Project"
author: "Margalit Haber"
output: 
  html_document:
    toc: false 
    depth: 3 
    theme: paper 
    highlight: tango
---
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 400)
```  
***
###Overview 
An abnormality on a head computed tomography scan (CT) is commonly used as an indication that a traumatic brain injury (TBI) event occurred for clinical studies, however, the diagnostic utility of a head CT abnormality for a TBI is not well understood. This project aims to identify whether a head CT abnormality is useful as a prognostic biomarker or whether other factors are more relevant for prognosis.

###Introduction
There are over 2 million occurrences of traumatic brain injury (TBI) in the united states every year. Of those 2 million cases, there is currently no means of predicting who will recover and who will develop chronic long-lasting symptoms. The inability to determine who will recover without intervention makes designing clinical research studies sensitive to patient selection. The inclusion and exclusion criteria selected for a TBI study is crucial to the success or failure of that study. A common inclusion criteria for TBI studies is the presence of a tissue abnormality on a head computed tomography scan (CT). It is utilized since it ensures that the underlying brain tissue is damaged after the impact, however, the diagnostic utility of head CT abnormalities has not been well characterized. This project aims to determine the diagnostic and prognostic utility of a head CT abnormality for TBI.
	
The analysis from this project will not only focus on head CT abnormalities as a biomarker for TBI, but will also investigate socioeconomic status and age as factors contributing to TBI outcome. The knowledge learned from this project will inform the medical field as to factors that make an individual susceptible to poor outcome after a TBI. This project is also aimed at taking a critical look at clinical research study design, and whether more informed decisions about subject selection is needed for future studies. Initial study design and subject selection criteria is important for the success of clinical research studies as well as epidemiological studies of secondary datasets.



### Methods
In the first paragraph, describe the data used and general methodological approach. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why. 


### Results
Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.
