---
title: "BMIN503/EPID600 FINAL PROJECT: ARDS Subphenotypes"
author: "Heather Giannini"
output: 
  html_document:
    theme: paper 
    highlight: tango
---
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 400)
```  
***
### Overview
Acute respiratory distress syndrome (ARDS) is a high morbid condition of respiratory failure, resulting from a myriad of insults, including infection (most notably recently, COVID19), trauma, and other underlying etiologies. We are investigating a recently described parsimonious model for identifying subphenotypes in this disease, as ARDS patients can be highly divergent clinically, and yet we do not have a clear understanding of the biological basis for vastly different outcomes and clinical trajectories. This project will compare the results of applying two similar but slightly different biomarker-based algorithms. We will investigate clinical features and outcomes and test for protein associations.
This work was done in consultation with Dr. Nuala Meyer and Dr. Pratik Sinha, both Pulmonary and Critical Care and Dr. John Reilly.

three faculty/staff in different fields you have spoken to about your project with a brief summary of what you learned from each person. Include a link to your final project GitHub repository.

Final Project GitHub Repository: <https://github.com/gianninh/BMIN503_Final_Project>

### Introduction 
Acute respiratory distress syndrome (ARDS) is a devastating pulmonary condition with high patient-level variability that has extremely high mortality and long-term morbidity in survivors. In clinical trials and observational studies for ARDS, two clinical subphenotypes - distinguished by plasma levels of inflammatory proteins and correlating with 30-d mortality - have been consistently identified by latent class analysis (LCA). These two classes are termed “Hyperinflammatory” and “Hypoinflammatory”. These phenotypes demonstrate heterogeneous treatment response to multiple ARDS therapies. Although iterations of parsimonious models for assigning these LCA classes based on biomarker combinations have similar operating characteristics, their agreement at the patient level has not been directly compared. We hypothesized that the performance of these models may vary in the context of clinical factors that disproportionately affect expression of the plasma proteins used for subphenoytype assignment

This project will evaluate these biomarker-based Parsimonious Models for ARDS subphenotypes. We will apply the models to our ARDS cohort, a subcohort of the Molecular Epidemiology of Sepsis in the ICU (MESSI) sepsis cohort. We will then test associations of these class assignments with various clinical characteristics, including medical comorbidities, biomarker protein levels, laboratory values (ie. white blood cell count). Importantly, we will compare the assignments of two different models, which may vary based on the biomarker used, either IL6 or IL8, two similar cytokines that are typically congruent but may be proportionally different in certain clinical circumstances.


### Methods
Describe the data used and general methodological approach. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why. 


### Results
Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.
