---
title: "Examining Pregnancy Prevention Methods among Adolescents AFAB"
subtitle: "BMIN503/EPID600 Final Project"
author: "Gabrielle Zuckerman"
format: html
editor: visual
number-sections: true
embed-resources: true
---

------------------------------------------------------------------------

## Overview {#sec-overview}

Preventing unintended teenage pregnancy is a public health priority that can be mitigated by individual uptake of effective contraception in sexually active teens. The Centers for Disease Control and Prevention publishes a publicly available dataset called the National High School Youth Risk Behavior Survey (YRBS) that contains information on important health behaviors and experiences in American high school students. Thus, the goal of this project is to use data from the YRBS to see what proportion of sexually active adolescents that were assigned female at birth (AFAB) utilize pregnancy prevention methods, which pregnancy methods are most popular among them, and whether these outcomes vary by sexual minority status

## Introduction {#sec-introduction}

Describe the problem addressed, its significance, and some background to motivate the problem. This should extend what is in the @sec-overview.

Explain why your problem is interdisciplinary, what fields can contribute to its understanding, and incorporate background related to what you learned from meeting with faculty/staff.

## Methods {#sec-methods}

Describe the data used and general methodological approach used to address the problem described in the @sec-introduction. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why.

## Results {#sec-results}

Describe your results and include relevant tables, plots, and code/comments used to obtain them. You may refer to the @sec-methods as needed. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

## Conclusion

This the conclusion. The @sec-results can be invoked if you'd like.
