#---
title: "Load & Clean"
output:
  html_document: default
---



```{r}
library(tidyverse)
library(stringr)

#read in files
FIreg <- read_csv("C:/Users/Kelly Courts/fakeFIregistry.csv")
FR<-dim(FIreg)
RXreg <- read_csv("C:/Users/Kelly Courts/fakeRXregistry.csv")
RR<-dim(RXreg)
FullRX <- read_csv("C:/Users/Kelly Courts/fakeRXtracking.csv")
FRX<-dim(FullRX)
```


```{r}
#data cleanup - FIReg

#inspect file varible types
#str(FIreg)

#change column names
FIreg<-plyr::rename(FIreg,c(
      "Person #"="ID",
      "Patient Last Name"="Plast",
      "Patient First Name"="PfirstFI",
      "Patient DOB"="DOB",
      "Caregiver Last Name"="ClastFI",
      "Caregiver First Name"="CfirstFI",
      "Patient Gender"="Gender",
      "Patient Race"="Race",
      "Screening Date"="FISdate",
      "Screen Result -worried"= "FIworry",
      "Screen Result -food did not last"="FInotlast",
      "Provider"="FIProvider",
      "Location"="FIDept",
      "BMI calculate"="BMI",
      "BMI %"="BMI%",
      "Edinburgh Score"= "Edinburgh",
      "Same Day Dental Referral"="DentalRX",
      "lead screening"="LSdate",
      "Dx Code"="DxCode",
      "Dx Code Desc"="DxDesc"))
                           
#create new columns
FIreg<-FIreg %>% 
  dplyr::mutate(Visitdate=FISdate)
  
#FIreg<-FIreg %>% # returns 79,286
 # filter(FreshRX=="FreshRX") %>% 
  #dplyr::mutate(RXdate=Visitdate)

#convert fields to dates 
makedatesFI<-c("DOB","FISdate","DentalRX","LSdate","Visitdate")
FIreg[makedatesFI] <- lapply(FIreg[makedatesFI], as.Date, "%m/%d/%Y")

#convert fields to factors
makefactors<-c("FIworry","FInotlast","FI","SNAP","WIC","TANF","Payer")
FIreg[makefactors] <- lapply(FIreg[makefactors], factor)

#convert fields to integers
FIreg$Edinburgh<-as.numeric(FIreg$Edinburgh)

#convert fields to character
FIreg$Payer<-as.character(FIreg$Payer)

#capitalization
FIreg<-FIreg %>% 
  mutate(FIworry=str_to_title(as.character(FIworry)),
         FInotlast=str_to_title(as.character(FInotlast)),
         Race=str_to_title(as.character(Race)))

#simplify Zip
FIreg<-FIreg %>%
  mutate(cleanzip=word(Zip,sep=fixed("-")))

#answer normalization
FIreg<-FIreg %>% 
  mutate(FIDept = str_replace(FIDept, "FAKE location","Fake")) %>%
  mutate(FIDept = str_replace(FIDept, "faek location","Fake"))

```

```{r}
#data cleanup - RXReg

#inspect file varible types
#str(FIreg)

#change column names
RXreg<-plyr::rename(RXreg,c(
      "Person #"="ID",
      "Patient Last Name"="Plast",
      "Patient First Name"="PfirstFI",
      "Patient DOB"="DOB",
      "Caregiver Last Name"="ClastFI",
      "Caregiver First Name"="CfirstFI",
      "Patient Gender"="Gender",
      "Patient Race"="Race",
      "Screening Date"="FISdate",
      "Screen Result -worried"= "FIworry",
      "Screen Result -food did not last"="FInotlast",
      "Provider"="FIProvider",
      "Location"="FIDept",
      "BMI calculate"="BMI",
      "BMI %"="BMI%",
      "Edinburgh Score"= "Edinburgh",
      "Dental Referral"="DentalRX",
      "Lead Screen"="LSdate",
      "Dx Code"="DxCode",
      "Dx Code Desc"="DxDesc"))
                           
#create new columns
RXreg<-RXreg %>% 
  dplyr::mutate(Visitdate=FISdate,RXdate=".") %>% 
  filter(FreshRX=="FreshRX") %>% 
  dplyr::mutate(RXdate=Visitdate)

#convert fields to dates 
makedatesFI<-c("DOB","FISdate", "RXdate", "DentalRX","LSdate","Visitdate")
RXreg[makedatesFI] <- lapply(RXreg[makedatesFI], as.Date, "%m/%d/%Y")

#convert fields to factors
makefactors<-c("FIworry","FInotlast","FI","SNAP","WIC","TANF","Payer")
RXreg[makefactors] <- lapply(RXreg[makefactors], factor)

#convert fields to character
RXreg<-RXreg %>% 
  mutate(Payer=as.character(Payer),
         FIworry=as.character(FIworry),
          FInotlast=as.character(FInotlast)
          )

#simplify Zip
RXreg<-RXreg %>%
  mutate(cleanzip=word(Zip,sep=fixed("-")))

#answer normalization
RXreg<-RXreg %>% 
  mutate(FIDept = str_replace(FIDept, "FAKE location","Fake")) %>%
  mutate(FIDept = str_replace(FIDept, "faek location","Fake"))
```


```{r}
#data cleanup - FullRX

#inspect file varible types
#str(FullRX)
```
```{r}
#change column names
FullRX<-plyr::rename(FullRX,c(
  "Date"="Visitdate",
  "Phone Number"="Phone",
  "Patient LAST Name"="Plast",
  "Patient FIRST Name"="PfirstRX",
  "Caregiver LAST Name"="ClastRX",
  "Caregiver FIRST Name"="CfirstRX",
  "Department"="RXDept",
  "Provider"="RXProvider",
  "Called Back?"="Called",
  "Callback Date"="Calldate",
  "Phone Issue"="Issue",
  "Left Message"="Message?",
  "Order Status"="Status",
  "Date of first purchase"="firstpurchdate",
  "RX to purchase"="RX2purch",
  "call to purchase"="call2purch",
  "Farm Stand"="stand",
  "total purchases"="totpurch"))

#convert fields to dates
makedatesRX<-c("Visitdate", "Calldate","firstpurchdate","stand")
FullRX[makedatesRX] <- lapply(FullRX[makedatesRX], as.Date, "%m/%d/%Y")

#convert fields to numeric
makenumeric<-c("RX2purch","call2purch","totpurch")
FullRX[makenumeric] <- lapply(FullRX[makenumeric],as.numeric)


#answer normalization

#capitalization
FullRX<-FullRX %>% 
  mutate(RXDept=str_to_title(RXDept),
        RXProvider=str_to_title(RXProvider),
        Rx_Type=str_to_title(Rx_Type),
        Status=str_to_title(Status),
        Called=str_to_title(Called),
        Issue=str_to_title(Issue)
        )

FullRX<-FullRX %>% 
  mutate(RXDept = str_replace(RXDept, "FAKE location","Fake")) %>%
  mutate(RXDept = str_replace(RXDept, "faek location","Fake")) %>%
  mutate(RXProvider = str_replace(RXProvider, "faekdoctor","Fakedoctor"))
```