---
title: "Overview"
output:
  html_document: default
---


```{r include=FALSE}
library(knitr)
library(kableExtra)
library(lubridate)
library(tidyverse)
library(dplyr)
library(ggplot2)
purl("creating_datasets.Rmd", output = "creating_datasets.R", documentation = 2)
source(file="creating_datasets.R")
```

```{r echo=FALSE}
datasettable %>% 
  knitr::kable("html", caption="Overview of datasets used and created") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")
```

```{r include=FALSE}
Gender<-fulluniquefams %>% 
  filter((`Gender.x`=="M")) %>% 
  summarize(`Gender(male)`= n())

Race_Black<-fulluniquefams %>% 
  filter((`Race.x`=="Black Or African American")) %>% 
  summarize(`Race(Black)`= n())

Race_White<-fulluniquefams %>% 
  filter((`Race.x`=="Caucasian Or White")) %>% 
  summarize(`Race(White)`= n())

Race_Hispanic<-fulluniquefams %>% 
  filter((`Race.x`=="Hispanic Or Latino")) %>% 
  summarize(`Race(Hispanic)`= n())

Mean_Age<-fulluniquefams %>% 
  summarize(Mean_Age= mean(na.omit(age)))
Mean_Age<-round(Mean_Age,digits=1)

Mean_BMI<-fulluniquefams %>% 
  summarize(Mean_BMI=mean(na.omit(BMI.x)))
Mean_BMI<-round(Mean_BMI,digits=2)

cohortstats<-cbind(Gender,Race_Black,Race_White,Race_Hispanic)
percentofcohort<-cbind(Gender/10048,Race_Black/10048,Race_White/10048,Race_Hispanic/10048)
percentofcohort<-round(percentofcohort,digits=2)*100
Table1<-rbind(cohortstats,percentofcohort)
row.names(Table1)<-c("families", "percent")
Table1<-as.data.frame(Table1)
Table2<-cbind(Mean_Age,Mean_BMI)
Table2
```


```{r echo=FALSE}
Table1 %>% 
  knitr::kable("html", caption="Cohort characteristics - Gender/Race (n=10,048)") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")

Table2 %>% 
  knitr::kable("html", caption="Cohort characteristics - Age (n=11,242), BMI (n=5577)") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")
```