---
title: "Sociodemographic Disparities in Pediatric Emergency Department Revisit Rates"
subtitle: "BMIN503/EPID600 Final Project"
author: "Casey Pitts"
format: html
editor: visual
number-sections: true
embed-resources: true
---

------------------------------------------------------------------------

## Overview {#sec-overview}

**Area of Interest:\
**Are there sociodemographic disparities in the rate of pediatric emergency room short-term revisits (re-presenting to the ED within 72 hours)?

**Mentors:**\
Joseph Zorc, MD, MSCE. Professor of Pediatrics, Mark Fishman Endowed Chair in Genomics and Computational Science, and Director of Emergency Information Systems. Division of Emergency Medicine, Department of Pediatrics, Children's Hospital of Philadelphia.

-   Reviewed key factors of interest, including demographics, language proficiency, acuity, admission status, as well as clearly defining the "revisit" variable

Brandon C. Ku, MD. Associate Professor of Pediatrics, Associate Medical Director of Clinical Pathways Program, and Associate Director of Quality Improvement. Divison of Emergency Medicine, Department of Pediatrics, Children's Hospital of Philadelphia.

-   Discussed primary and secondary outcome measures of the project as well as the optimal visualizations of the variables of interest.

## Introduction {#sec-introduction}

Pediatric emergency care (PEC) is a complex and fast-paced environment that treats patients across the healthcare and socio-demographic spectrums. Recently, there has been increasing focus on overall care quality and disparities in PEC. Disparities are known to exist in timely pain management by patient race and that those with non-English language proficiency have an increased risk of adverse medical events. Revisits, or returning to the emergency department within 72 hours, are an important marker of care quality and performance indicator of a department. While patients represent to the emergency room following a visit for various reasons, including progression of disease or repeat medication administration, it may signal incomplete ED care or insufficient anticipatory guidance. Revisits are also associated with increased healthcare costs, over-crowding and system stress, and decreased satisfaction of both families and staff.

Understanding the disparities associated with increased revisit rates and discovering modifiable factors is needed to offer solutions. This study will examine the association of sociodemographic and visit-specific factors that are associated with revisits that result either in a repeat discharge or hospitalization.

## Methods {#sec-methods}

This is a retrospective study of patients, between 0-18 years old, presenting to a urban, tertiary, academic pediatric emergency department between November 01, 2018 to November 01, 2023. We calculated rates of 72 hour revisits resulting in repeat discharge or hospital admission. Both patient and visit-level factors were included for exploratory analysis. Visit-level factors include daily volume, daily average acuity, daily average wait time, and ED location. Patient-level factors include age, sex, race, ethnicity, preferred language, individual triage acuity, history of complex medical conditions, chief complaint, insurance status, COI, distance from the ED, and green space access.

Data was accessed through the institutional data warehouse, extracted from patient and encounter-level tables and downloaded as a CSV file.

*Describe the data used and general methodological approach used to address the problem described in the @sec-introduction. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why.*

## Results {#sec-results}

*Describe your results and include relevant tables, plots, and code/comments used to obtain them. You may refer to the @sec-methods as needed.*

## Conclusion

*End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required. This the conclusion. The @sec-results can be invoked if you'd like.*
