---
title: "The effects of COVID-19 on rabies dynamics in Arequipa, Peru"
author: "Brinkley Raynor"
output: 
  html_document:
    toc: false 
    depth: 3 
    theme: paper 
    highlight: tango
---
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 400)
```  
***

### Overview

+ Give a brief a description of your project and its goal(s), what data you are using to complete it, and what three faculty/staff in different fields you have spoken to about your project with a brief summary of what you learned from each person. Include a link to your final project GitHub repository.

Over the summer of 2020, I worked to create a compartmental SEIR model of rabies in Arequipa, Peru investigating how COVID-19 control measures effected canine rabies dynamics. As an extension of the project, I am implementing a stochastic model as well as streamlining my old code using dplyr. 


Data was collected from several sources. Information on positive cases comes from collaboration with the Peru Ministry of Health. Demographic data used to paramaterize the model comes from 5 years worth of survey data collected after the vaccination campaign by the Castillo team. 

Ricardo Castillo-Neyra is a veterinarian and epidemiologist who is an expert in canine rabies in Peru. From Ricardo, I learned a lot about the social context of rabies in Arequipa, about the types of restrictions that occured due to COVID and about rabies dynamics.

Mike Levy is an epidemiologist who has worked in Arequipa for years. From Mike, I learned a lot about Arequipa. He is also an expert in mathematical modelling and I have worked closely with him to create the models. 

Julianna Shinnick is a nurse and staff member in the Castillo lab. Julianna has been investigating how public health emergency (such as SARS-CoV-1, SARS-CoV-2, Ebola, Zika) has disrupted established disease control efforts. 

Final project link: 

### Introduction 

+Explain why your problem is interdisciplinary, what fields can contribute to its understanding, and incorporate background related to what you learned from meeting with faculty/staff.

COVID-19 has been devestating world-wide; the media has extensively covered case counts, death rates, the lagging economy, and peoples fears and low morals. However, less understood and explored are how measures to fight COVID-19 are effecting other public health initiatives. One example is canine rabies in Arequipa, Peru. When SARS-CoV-2 arrived to Peru in early March, 2020 mandates including orders to social distance, curfews and work from home were implemented. Due to this, several vital canine rabies control measures were impacted.  

To understand how rabies dynamics may be impacted, several social and biological factors must be considered. We identified 2 main areas were COVID-19 measures have effected rabies control programs. First, every summer annually a mass vaccination campaign is held city wide to offer free rabies vaccinations to peoples pets. With COVID-19,t the campaign was delayed and there were even talks of cancelling it. Second, many surveillance activities were halted as public health officials were unable to leave home.

Peru, and the rest of Latin America, has made enormous strides towards the OIE goal of eliminating canine mediated human rabies by 2030. However, we are worried that COVID-19 and the resulting control measures may disrupt and endanger the progress towards this goal. To explore, possible effects we create a mathematical model to examine rabies dynamics with surveillance and vaccination coverage impacted. 

### Methods
Describe the data used and general methodological approach. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why. 

#### Data
Data files are not submitted to f

### Results
Describe your results and include relevant tables, plots, and code/comments used to obtain them. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.
