---
title: "referrals"
output:
  html_document: default
---


```{r include=FALSE}
library(knitr)
library(kableExtra)
library(lubridate)
library(tidyverse)
library(dplyr)
purl("creating_datasets.Rmd", output = "creating_datasets.R", documentation = 2)
source(file="creating_datasets.R")
```

```{r include=FALSE}
##Rxes written and redeemed by year by type
RXesbyyear<-distinctRXrecips %>%
  group_by(year(Visitdate)) %>%
  dplyr::summarize(Total_referrals=n())
RXesbyyear<-na.omit(RXesbyyear)

#paperRX
PRXbyyear<-distinctRXrecips %>%
  group_by(year(Visitdate)) %>%
  filter(Rx_Type=="Paper") %>% 
  dplyr::summarize(Paper_referrals=n())
PRXbyyear<-na.omit(PRXbyyear)

#ERXes written by year
ERXbyyear<-distinctRXrecips %>%
  group_by(year(Visitdate)) %>%
  filter(Rx_Type=="Electronic") %>% 
  dplyr::summarize(Electronic_referrals=n())

RXtypebyyeartb<-full_join(PRXbyyear,ERXbyyear)
RXtypebyyeartb2<-full_join(RXesbyyear,RXtypebyyeartb)

#paper redeemed
PRedbyyear<-distinctRXredemps %>%
  group_by(year(Visitdate)) %>%
  filter(Rx_Type=="Paper") %>% 
  dplyr::summarize(Paper_redemptions=n())
PRedbyyear<-na.omit(PRedbyyear)

#electronic redeemed
ERedbyyear<-distinctRXredemps %>%
  group_by(year(Visitdate)) %>%
  filter(Rx_Type=="Electronic") %>% 
  dplyr::summarize(Electronic_redemptions=n())

RXRedbyyeartb<-full_join(PRedbyyear,ERedbyyear)

fullRXtypebyyeartb<-full_join(RXtypebyyeartb2,RXRedbyyeartb)
```


```{r echo=FALSE}
 fullRXtypebyyeartb %>% 
  knitr::kable("html", caption="Referrals written and redeemed by year by type (2014-17)") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")
```
```{r}
#paper referral redemption 2017
paperredemps2017<-fullRXtypebyyeartb %>% 
  filter(`year(Visitdate)`==2017) %>% 
  mutate(paper_redemption_rate=round((Paper_redemptions/Paper_referrals)*100)) %>% 
  select(paper_redemption_rate) %>% 
  print()

#electronic referral redemption 2017
electronicredemps2017<-fullRXtypebyyeartb %>% 
  filter(`year(Visitdate)`==2017) %>% 
  mutate(electronic_redemption_rate=round((Electronic_redemptions/Electronic_referrals)*100)) %>% 
  select(electronic_redemption_rate) %>% 
  print()
```


```{r include=FALSE}
##Rxes written and redeemed by year
#RXes written by year
RXesbyyear<-distinctRXrecips %>%
  group_by(year(Visitdate)) %>%
  dplyr::summarize(Total_referrals=n())
RXesbyyear<-na.omit(RXesbyyear)

#RXes redeemed by year
Redempsbyyear<-distinctRXredemps %>% 
  group_by(year(Visitdate)) %>% 
  dplyr::summarize(Redeemed=n())


RXestable<-suppressMessages(full_join(RXesbyyear,Redempsbyyear))
RXestable<-RXestable %>% 
  mutate(`redemption_rate%`=round((Redeemed/Total_referrals)*100))

aa<-sum(RXestable$Total_referrals)
bb<-sum(RXestable$Redeemed)
cc<-sum(RXestable$`redemption_rate%`/4)

RXestabletotals<-c("totals",aa,bb,cc)
RXestable2<-rbind(RXestable,RXestabletotals)
```

```{r echo=FALSE}
 RXestable2 %>% 
  knitr::kable("html", caption="Referrals written and redeemed by year (2014-17)") %>%
  kable_styling(bootstrap_options = c("bordered","striped"),
                full_width = FALSE,
                position="left")
```