---
title: "Regression"
output:
  html_document: default
---


```{r include=FALSE}
library(knitr)
library(kableExtra)
library(lubridate)
library(tidyverse)
library(dplyr)
library(gee)
library(geepack)
purl("creating_datasets.Rmd", output = "creating_datasets.R", documentation = 2)
source(file="creating_datasets.R")
```

```{r include=FALSE}
#quick fix of a zip code error
fullmerge<-fullmerge %>% 
  mutate(`cleanzip.x` = str_replace(`cleanzip.x`, "19111 570","19111"))
```


```{r eval=TRUE}
#participation by family characteristics
#summary(glm(participation~FI.x,data=fullmerge))
#summary(glm(participation~BMI.x,data=fullmerge))
#summary(glm(participation ~ `Race.x` ,data=fullmerge))
#summary(glm(participation ~ age ,data=fullmerge))
#summary(glm(participation ~ `Gender.x` ,data=fullmerge))
#summary(glm(participation ~ `cleanzip.x` ,data=fullmerge))
summary(glm(participation~FI.x+BMI.x+`Race.x`+age+`Gender.x`+`cleanzip.x`,data=fullmerge))
```



```{r}
#participation by RX characteristics
summary(glm(participation~Called,data=fullmerge))
#summary(glm(participation~FIDept.x,data=fullmerge))
summary(glm(participation~Called+FIDept.x,data=fullmerge))
#summary(glm(participation~Called+FIDept.x+age+Race.x,data=fullmerge))
summary(glm(participation~Called+FIDept.x+age+Race.x+cleanzip.x,data=fullmerge))
```