#label all columns
#label(data$redcap_id)="REDCap ID"
label(data$redcap_event_name)="Event Name"
#label(data$start_here_timestamp)="Survey Timestamp"
label(data$start_here_complete)="Complete?"
#label(data$borinquen_info_release_timestamp)="Survey Timestamp"
#label(data$today_date)="Todays Date:La Fecha de Hoy"
label(data$participating)="Are you interested in participating in this study?"
#label(data$first_date)="This consent is granted for:  A  Continuing disclosure  (expires 12 month form the date I sign this form) or upon termination of treatment, whichever occurs first.  Todays Date:"
label(data$borinquen_info_release_complete)="Complete?"
#label(data$consent_timestamp)="Survey Timestamp"
label(data$parent_or_guardian___1)=" (choice=Parent)"
label(data$parent_or_guardian___2)=" (choice=Individual legally authorized to consent to the childs general medical care)"
label(data$consent_complete)="Complete?"
#label(data$assent_timestamp)="Survey Timestamp"
label(data$assent_complete)="Complete?"
#label(data$consent_2_timestamp)="Survey Timestamp"
label(data$parent_or_guardian_v2___1)=" (choice=Parent)"
label(data$parent_or_guardian_v2___2)=" (choice=Individual legally authorized to consent to the childs general medical care)"
label(data$consent_2_complete)="Complete?"
#label(data$consent2_timestamp)="Survey Timestamp"
label(data$consent2_complete)="Complete?"
#label(data$perception_timestamp)="Survey Timestamp"
label(data$worthtime)="Did you feel the FitTech program was worth your time?"
label(data$tablet_v_drvisit___1)="Did you prefer the tablet session to a regular doctors office visit? (choice=Yes)"
label(data$tablet_v_drvisit___0)="Did you prefer the tablet session to a regular doctors office visit? (choice=No)"
label(data$tablet_v_telephone)="Do you think telephone calls would be better than video conferencing?"
label(data$parentchild)="Do you think it would have worked better if we conducted part of the session with you (parent) and part with your child?"
label(data$frequency)="How often do you think the online sessions should be?"
label(data$easy_tablet)="How easy was the tablet to use?"
label(data$wifi)=" Does your family have access to wifi?"
label(data$fuze)="Would you recommend Fuze (the video conferencing app) for other studies like this one?"
label(data$appssites)="Which apps/websites did you like or find useful?"
label(data$acad_accom)=" Does your child receive any academic accommodations?"
label(data$perception_complete)="Complete?"
#label(data$demographics_patient_timestamp)="Survey Timestamp"
label(data$dem_gender)="What is your gender?"
label(data$dem_ethnicity)="What is your ethnic group or race?"
label(data$dem_language_home)="What language is spoken at home?"
label(data$dem_language_pref)="What language do you prefer to speak?"
label(data$dem_grade)="What grade are you in this year?"
label(data$demographics_patient_complete)="Complete?"
#label(data$tech_patient_timestamp)="Survey Timestamp"
label(data$tech_kid_smart_device)="Do you have a smart phone or tablet? (e.g. iPhone/iPad, Samsung Galaxy, etc)?"
label(data$tech_kid_brand___1)="What brand of smart phone or tablet do you have? (Select all that apply)(choice=iPhone or iPad)"
label(data$tech_kid_brand___2)="What brand of smart phone or tablet do you have? (Select all that apply)(choice=Samsung)"
label(data$tech_kid_brand___3)="What brand of smart phone or tablet do you have? (Select all that apply)(choice=LG)"
label(data$tech_kid_brand___4)="What brand of smart phone or tablet do you have? (Select all that apply)(choice=HTC)"
label(data$tech_kid_brand___5)="What brand of smart phone or tablet do you have? (Select all that apply)(choice=Motorola)"
label(data$tech_kid_brand___6)="What brand of smart phone or tablet do you have? (Select all that apply)(choice=OtherOtro)"
label(data$tech_kid_brand___7)="What brand of smart phone or tablet do you have? (Select all that apply)(choice=UnsureNo estoy serguro)"
label(data$tech_kid_os___1)="What type of smart phone or tablet do you have? (Select all that apply)(choice=iPhone or iPadiPhone o iPad)"
label(data$tech_kid_os___2)="What type of smart phone or tablet do you have? (Select all that apply)  (choice=Android/Google)"
label(data$tech_kid_os___3)="What type of smart phone or tablet do you have? (Select all that apply)  (choice=Windows)"
label(data$tech_kid_os___4)="What type of smart phone or tablet do you have? (Select all that apply)  (choice=Blackberry)"
label(data$tech_kid_os___5)="What type of smart phone or tablet do you have? (Select all that apply)  (choice=OtherOtro)"
label(data$tech_kid_os___6)="What type of smart phone or tablet do you have? (Select all that apply)  (choice=Unsure)"
label(data$tech_kid_phone_service)="Does your smart phone ever get disconnected (turned off) because the monthly bill has not been paid?)"
label(data$tech_kid_disconnect)="How many times per year does your smart phone get disconnected (turned off) because the monthly bill has not been paid?)"
label(data$tech_kid_apps)="Do you use any applications (app) or websites on your smart phone or tablet to help you with your health (e.g., exercise, eating)?)"
label(data$tech_kid_function___1)="What do the health apps or websites help you do? (choice=Keep track of your exercise)"
label(data$tech_kid_function___2)="What do the health apps or websites help you do? (choice=Keep track of what you eat)"
label(data$tech_kid_function___3)="What do the health apps or websites help you do? (choice=Keep track of your weight)"
label(data$tech_kid_function___4)="What do the health apps or websites help you do? (choice=Look up information about exercise)"
label(data$tech_kid_function___5)="What do the health apps or websites help you do? (choice=Look up information about healthy eating)"
label(data$tech_kid_privileges)="How often do you lose your technology privileges (e.g., have your smart phone or tablet taken away as punishment)?"
label(data$tech_kid_device_time)="How much time do you usually spend in total on your smart phone or tablet each day?"
label(data$tech_kid_given_device)="If you were provided a tablet, would you use the tablet to help you be healthier?"
label(data$tech_patient_complete)="Complete?"
#label(data$pedsql_patient_timestamp)="Survey Timestamp"
label(data$pedsqlkids_01)="It is hard for me to walk more than one block"
label(data$pedsqlkids_02)="It is hard for me to run"
label(data$pedsqlkids_03)="It is hard for me to do sports activity or exercise"
label(data$pedsqlkids_04)="It is hard for me to lift something heavy"
label(data$pedsqlkids_05)="It is hard for me to take a bath or shower by myself"
label(data$pedsqlkids_06)="It is hard for me to do chores around the house"
label(data$pedsqlkids_07)="I hurt or ache"
label(data$pedsqlkids_08)="I have low energy"
label(data$pedsqlkids_09)="I feel afraid or scared"
label(data$pedsqlkids_10)="I feel sad or blue"
label(data$pedsqlkids_11)="I feel angry"
label(data$pedsqlkids_12)="I have trouble sleeping"
label(data$pedsqlkids_13)="I worry about what will happen to me"
label(data$pedsqlkids_14)="I have trouble getting along with other kids"
label(data$pedsqlkids_15)="Other kids do not want to be my friend"
label(data$pedsqlkids_16)="Other kids tease me"
label(data$pedsqlkids_17)="I cannot do things that other kids my age can do"
label(data$pedsqlkids_18)="It is hard to keep up when I play with other kids"
label(data$pedsqlkids_19)="It is hard to pay attention in class"
label(data$pedsqlkids_20)="I forget things"
label(data$pedsqlkids_21)="I have trouble keeping up with my schoolwork"
label(data$pedsqlkids_22)="I miss school because of not feeling well"
label(data$pedsqlkids_23)="I miss school to go to the doctor or hospital"
label(data$pedsql_patient_complete)="Complete?"
#label(data$physical_activity_nutrition_patient_timestamp)="Survey Timestamp"
label(data$act_nutri_kids01)="During the past 7 days, on how many days were you physically active for a total of at least 60 minutes per day?  (Add up all the time you spent in any kind of physical activity that increased your heart rate and made you breathe hard some of the time.)"
label(data$act_nutri_kids02)="On how many of the past 7 days did you exercise or participate in physical activity for at least 20 minutes that made you sweat and breathe hard, such as basketball, soccer, running, swimming laps, fast bicycling, fast dancing, or similar aerobic activities?"
label(data$act_nutri_kids03)="On how many of the past 7 days did you do exercises to strengthen or tone your muscles, such as push-ups, sit-ups, or weight lifting?"
label(data$act_nutri_kids04)="On an average school day, how many hours do you play video or computer games or use a computer for something that is not school work? (Include activities such as Nintendo, Game Boy, PlayStation, Xbox, computer games, and the Internet.)"
label(data$act_nutri_kids05)="On an average school day, how many hours do you spend watching DVDs or videos? Include DVDs or videos you watch on a TV, computer, iPod, or other portable device."
label(data$act_nutri_kids06)="On an average school day, how many hours do you watch TV?"
label(data$act_nutri_kids07)="Encourage you to do physical activities or play sports?"
label(data$act_nutri_kids08)="Do a physical activity or play sports with you?"
label(data$act_nutri_kids09)="Provide transportation to a place where you can do physical activities or play sports?"
label(data$act_nutri_kids10)="Watch you participate in physical activities or play sports?"
label(data$act_nutri_kids11)="During the past 7 days, how many times did you eat fruit? (Do not count fruit juice.)"
label(data$act_nutri_kids12)="During the past 7 days, how many times did you eat green salad?"
label(data$act_nutri_kids13)="During the past 7 days, how many times did you eat French fries or other fried potatoes, such as home fries, hash browns or tater tots? (Do not count potato chips.)"
label(data$act_nutri_kids14)="During the past 7 days, how many times did you eat carrots?"
label(data$act_nutri_kids15)="During the past 7 days, how many times did you eat other vegetables? (Do not count green salad, potatoes, or carrots.)"
label(data$act_nutri_kids16)="During the past 7 days, how many times did you eat pizza?"
label(data$act_nutri_kids17)="During the past 7 days, how many times did you drink 100% fruit juices such as orange juice, apple juice, or grape juice? (Do not count punch, Kool-Aid, sports drinks, or other fruit-flavored drinks.)"
label(data$act_nutri_kids18)="During the past 7 days, how many times did you drink a can, bottle, or glass of soda, such as Coke, Pepsi, or Sprite? (Do not count diet soda)"
label(data$act_nutri_kids19)="During the past 7 days, how many times did you drink a can, bottle, or glass of a sugar-sweetened beverage such as lemonade, sweetened tea or coffee drinks, flavored milk, Snapple, or Sunny Delight? (Do not count soda or pop, sports drinks, energy drinks, or 100% fruit juice.)"
label(data$act_nutri_kids20)="During the past 7 days, how many times did you drink a bottle or glass of plain water? Count tap, bottled, and unflavored sparkling water."
label(data$act_nutri_kids21)="About how many cups of fruit (including frozen, canned, and dried fruit and 100% fruit juice) do you eat or drink each day?"
label(data$act_nutri_kids22)="About how many cups of vegetables (including frozen and canned vegetables and 100% vegetable juice) do you eat or drink each day?"
label(data$act_nutri_kids23)="During the past 7 days, on how many days did you eat breakfast or a morning meal?"
label(data$act_nutri_kids24)="During the past 7 days, on how many days did you eat dinner at home with at least one of your parents or guardians?"
label(data$act_nutri_kids25)="During the past 7 days, on how many days did you eat at least one meal or snack from a fast food restaurant such as McDonalds, Taco Bell, or KFC?"
label(data$act_nutri_kids26)="How often are there fruits or vegetables to snack on in your home, such as carrots, celery, apples, bananas, or melon?"
label(data$act_nutri_kids27)="How often are there foods such as chips, cookies, or cakes to snack on in your home?"
label(data$physical_activity_nutrition_patient_complete)="Complete?"
#label(data$weight_patient_timestamp)="Survey Timestamp"
label(data$weight_01)="I think I am pretty good at managing my weight."
label(data$weight_02)="Compared to other kids, I think I do pretty well when it comes to managing my weight."
label(data$weight_03)="I am satisfied with my ability to manage my weight."
label(data$weight_04)="I am pretty skilled at managing my weight."
label(data$weight_05)="Managing my diet is something that I cant do well."
label(data$weight_06)="I put a lot of effort into managing my weight."
label(data$weight_07)="I try very hard to manage my weight by having healthy eating habits."
label(data$weight_08)="I try very hard to manage my weight by being physically activity."
label(data$weight_09)="It is important for me to do well at managing my weight."
label(data$weight_10)="Overall, having a healthy diet is very important to me, a priority in my life."
label(data$weight_11)="Overall, I feel confident in being able to manage my diet so that my weight will be healthy."
label(data$weight_12)="Overall, I feel confident in being physically active so that my weight will be healthy."
label(data$weight_13)="Overall, doing physical activity is very important to me, a priority in my life."
label(data$weight_14)="I put a lot of effort into managing my diet and eating right."
label(data$weight_15)="I put a lot of effort into not being inactive and being more physically active."
label(data$weight_16)="Compared to other kids, I think I do pretty well when it comes to being physically active."
label(data$has_asthma)="Does [first_name] [last_name] have asthma?"
label(data$weight_patient_complete)="Complete?"
#label(data$asthma_knowledge_patient_timestamp)="Survey Timestamp"
label(data$asthma01___0)="What are the 3 main symptoms of asthma? (choice= sneezing)"
label(data$asthma01___1)="What are the 3 main symptoms of asthma? (choice= shortness of breath)"
label(data$asthma01___11)="What are the 3 main symptoms of asthma? (choice= coughing)"
label(data$asthma01___00)="What are the 3 main symptoms of asthma? (choice= skin rash)"
label(data$asthma01___000)="What are the 3 main symptoms of asthma? (choice= fever)"
label(data$asthma01___111)="What are the 3 main symptoms of asthma? (choice= wheezing)"
label(data$asthma01___0000)="What are the 3 main symptoms of asthma? (choice= nausea/vomiting)"
label(data$asthma01___00000)="What are the 3 main symptoms of asthma? (choice= runny nose)"
label(data$asthma01___000000)="What are the 3 main symptoms of asthma? (choice= headache)"
label(data$asthma01___1111)="What are the 3 main symptoms of asthma? (choice= chest tightness)"
label(data$asthma02)=" More than 1 in 10 children will have asthma at some time during their childhood."
label(data$asthma03)="Children with asthma have overly sensitive air passages in their lungs."
label(data$asthma04)="If one child in a family has asthma, then all his/her brothers and sisters are almost certain to have asthma."
label(data$asthma05)=" 5. Most children with asthma have an increase in mucus when they drink cows milk."
label(data$asthma07)="Wheezing from asthma can be caused by muscle tightening in the wall of the air passages in the lungs."
label(data$asthma08)="Wheezing from asthma can be caused by swelling in the lining of the air passages in the lungs."
label(data$asthma09)=" 9. Asthma damages the heart."
label(data$asthma10___0)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Albuterol)"
label(data$asthma10___00)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Ventolin)"
label(data$asthma10___1)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Pulmicort)"
label(data$asthma10___000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Decadron)"
label(data$asthma10___0000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Abilify)"
label(data$asthma10___11)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Montelukast)"
label(data$asthma10___00000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Lexapro)"
label(data$asthma10___000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Benadryl)"
label(data$asthma10___0000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Claritin)"
label(data$asthma10___00000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Amoxicillin)"
label(data$asthma10___111)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Singulair)"
label(data$asthma10___000000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Zoloft)"
label(data$asthma10___1111)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Budesonide)"
label(data$asthma10___0000000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Effexor)"
label(data$asthma10___00000000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Atrovent)"
label(data$asthma10___11111)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Flovent)"
label(data$asthma10___000000000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Metformin)"
label(data$asthma10___0000000000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Zithromax)"
label(data$asthma10___000000000000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Zyrtec)"
label(data$asthma10___0000000000000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Prednisone)"
label(data$asthma10___111111)="Select two asthma treatments (medicines) that are taken every day on a regular basis to PREVENT attacks of asthma from occurring. (choice=Qvar)"
label(data$asthma11___1)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Albuterol)"
label(data$asthma11___11)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Ventolin)"
label(data$asthma11___0)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Pulmicort)"
label(data$asthma11___111)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Decadron)"
label(data$asthma11___00)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Abilify)"
label(data$asthma11___000)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Montelukast)"
label(data$asthma11___0000)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Lexapro)"
label(data$asthma11___00000)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Benadryl)"
label(data$asthma11___000000)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Claritin)"
label(data$asthma11___0000000)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Amoxicillin)"
label(data$asthma11___00000000)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Singulair)"
label(data$asthma11___000000000)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Zoloft)"
label(data$asthma11___0000000000)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Budesonide)"
label(data$asthma11___00000000000)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Effexor)"
label(data$asthma11___1111)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Atrovent)"
label(data$asthma11___000000000000)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Flovent)"
label(data$asthma11___0000000000000)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Metformin)"
label(data$asthma11___00000000000000)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Zithromax)"
label(data$asthma11___000000000000000)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Zyrtec)"
label(data$asthma11___11111)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Prednisone)"
label(data$asthma11___0000000000000000)="What are the three asthma treatments (medicines) that are useful DURING an attack of asthma?  (choice=Qvar)"
label(data$asthma12)="Antibiotics are an important part of treatment for most children with asthma."
label(data$asthma13)="Most children with asthma should not eat dairy products."
label(data$asthma15)="If a child dies from an asthma attack, this usually means that there was no time to start any treatment."
label(data$asthma16)="Children with asthma usually have emotional problems."
label(data$asthma17)="You can catch asthma from another person."
label(data$asthma18)="Inhaled medications for asthma (for example, Ventolin puffers, Rotacaps) have fewer side effects than tablets."
label(data$asthma19)="Short courses of oral steroids (such as prednisone) usually cause significant side effects."
label(data$asthma20)="Some asthma treatments (such as Ventolin) damage the heart."
label(data$asthma22)="During an attack of asthma at home, you need your  nebulizer (mask) every 2 hours. You gain benefit but are very out of breath after 2 hours. Provided that you dont get any worse, its fine to continue with 2-hourly treatments."
label(data$asthma24)="Children with asthma become addicted to their asthma drugs."
label(data$asthma25)="Swimming is the only good exercise for children with asthma."
label(data$asthma26)="A parents smoking in the home may make the childs asthma worse."
label(data$asthma27)="With the right treatment most children with asthma live a normal life with no restriction on activity."
label(data$asthma28)="The best way to measure how bad a childs asthma is is for the doctor to listen to his/her chest."
label(data$asthma29)="Asthma symptoms usually occur more frequently at night than during the day."
label(data$asthma30)="Most children with asthma will have stunted growth."
label(data$asthma31)="Children who frequently have asthma symptoms should have preventative drugs."
label(data$asthma_knowledge_patient_complete)="Complete?"
#label(data$demographics_parent_timestamp)="Survey Timestamp"
label(data$dem_parent_sex)="What is your gender?"
label(data$dem_parent_ethnicity)="What is your ethnic group or race?"
label(data$dem_parent_language_pref)="What language do you prefer to speak?"
label(data$dem_parent_school)="What is the highest grade or level of education you have completed?"
label(data$dem_parent_nationality)="What is your country of origin/birth?"
label(data$dem_parent_us)="How long have you lived in the United States?"
label(data$dem_kid_nationality)="What is your childs country of origin/birth?"
label(data$dem_kid_us)="If not born in the United States, how long has your child been in the United States?"
label(data$dem_parent_job)="What is your current employment status?"
label(data$dem_parent_income)="What is your household yearly income (before taxes)?"
label(data$dem_parent_marital)="What is your marital status?"
label(data$dem_parent_habitants)="How many people live in the primary house of the youth (including the youth)?"
label(data$dem_kid_pmhx___1)="Does your child have a history of any medical or mental health conditions? (check all that apply) (choice=Asthma)"
label(data$dem_kid_pmhx___2)="Does your child have a history of any medical or mental health conditions? (check all that apply) (choice=Sleep Apnea)"
label(data$dem_kid_pmhx___3)="Does your child have a history of any medical or mental health conditions? (check all that apply) (choice=Anxiety)"
label(data$dem_kid_pmhx___4)="Does your child have a history of any medical or mental health conditions? (check all that apply) (choice=Cancer)"
label(data$dem_kid_pmhx___5)="Does your child have a history of any medical or mental health conditions? (check all that apply) (choice=Learning Disorder)"
label(data$dem_kid_pmhx___6)="Does your child have a history of any medical or mental health conditions? (check all that apply) (choice=Depression)"
label(data$dem_kid_pmhx___7)="Does your child have a history of any medical or mental health conditions? (check all that apply) (choice=Heart Disease)"
label(data$dem_kid_pmhx___8)="Does your child have a history of any medical or mental health conditions? (check all that apply) (choice=ADHD/ADD)"
label(data$dem_kid_pmhx___9)="Does your child have a history of any medical or mental health conditions? (check all that apply) (choice=Other)"
label(data$dem_kid_famhx___1)="Does anyone in your childs family have a history of any medical or mental health conditions? (check all that apply)nda) (choice=Asthma)"
label(data$dem_kid_famhx___2)="Does anyone in your childs family have a history of any medical or mental health conditions? (check all that apply)nda) (choice=Sleep Apnea)"
label(data$dem_kid_famhx___3)="Does anyone in your childs family have a history of any medical or mental health conditions? (check all that apply)nda) (choice=Anxiety)"
label(data$dem_kid_famhx___4)="Does anyone in your childs family have a history of any medical or mental health conditions? (check all that apply)nda) (choice=Cancer)"
label(data$dem_kid_famhx___5)="Does anyone in your childs family have a history of any medical or mental health conditions? (check all that apply)nda) (choice=Learning Disorder)"
label(data$dem_kid_famhx___6)="Does anyone in your childs family have a history of any medical or mental health conditions? (check all that apply)nda) (choice=Depression)"
label(data$dem_kid_famhx___7)="Does anyone in your childs family have a history of any medical or mental health conditions? (check all that apply)nda) (choice=Heart Disease)"
label(data$dem_kid_famhx___8)="Does anyone in your childs family have a history of any medical or mental health conditions? (check all that apply)nda) (choice=ADHD/ADD)"
label(data$dem_kid_famhx___9)="Does anyone in your childs family have a history of any medical or mental health conditions? (check all that apply)nda) (choice=Other)"
label(data$demographics_parent_complete)="Complete?"
#label(data$tech_parent_timestamp)="Survey Timestamp"
label(data$tech_parent_device)="Do you have a smart phone or tablet? (e.g. iPhone/iPad, Samsung Galaxy, etc)?"
label(data$tech_parent_brand___1)="What brand of smart phone or tablet do you have? (Select all that apply)(choice=iPhone or iPad)"
label(data$tech_parent_brand___2)="What brand of smart phone or tablet do you have? (Select all that apply)(choice=Samsung)"
label(data$tech_parent_brand___3)="What brand of smart phone or tablet do you have? (Select all that apply)(choice=LG)"
label(data$tech_parent_brand___4)="What brand of smart phone or tablet do you have? (Select all that apply)(choice=HTC)"
label(data$tech_parent_brand___5)="What brand of smart phone or tablet do you have? (Select all that apply)(choice=Motorola)"
label(data$tech_parent_brand___6)="What brand of smart phone or tablet do you have? (Select all that apply)(choice=OtherOtro)"
label(data$tech_parent_brand___7)="What brand of smart phone or tablet do you have? (Select all that apply)(choice=Unsure)"
label(data$tech_parent_os___1)="What type of smart phone or tablet do you have? (Select all that apply)  (choice=iPhone or iPad)"
label(data$tech_parent_os___2)="What type of smart phone or tablet do you have? (Select all that apply)  (choice=Android/Google)"
label(data$tech_parent_os___3)="What type of smart phone or tablet do you have? (Select all that apply)  (choice=Windows)"
label(data$tech_parent_os___4)="What type of smart phone or tablet do you have? (Select all that apply)  (choice=Blackberry)"
label(data$tech_parent_os___6)="What type of smart phone or tablet do you have? (Select all that apply)  (choice=OtherOtro)"
label(data$tech_parent_os___7)="What type of smart phone or tablet do you have? (Select all that apply)  (choice=Unsure)"
label(data$tech_parent_phone_service)="Does your smart phone ever get disconnected (turned off) because the monthly bill has not been paid?"
label(data$tech_parent_disconnect)="How many times per year does your smart phone get disconnected (turned off) because the monthly bill has not been paid?"
label(data$tech_parent_apps)="Do you use any applications (app) or websites on your smart phone or tablet to help you with your health (e.g., exercise, eating)?"
label(data$tech_parent_function___1)="What do the health apps or websites help you do?(choice=Keep track of your exercise"
label(data$tech_parent_function___2)="What do the health apps or websites help you do?(choice=Keep track of what you eat"
label(data$tech_parent_function___3)="What do the health apps or websites help you do?(choice=Keep track of your weight"
label(data$tech_parent_function___4)="What do the health apps or websites help you do?(choice=Look up information about exercise"
label(data$tech_parent_function___5)="What do the health apps or websites help you do?(choice=Look up information about healthy eating"
label(data$tech_parent_info___1)="Where do you get health information (e.g., eating/dieting, exercise, diseases/disorders/conditions)?es)? (choice=Friends or Family"
label(data$tech_parent_info___2)="Where do you get health information (e.g., eating/dieting, exercise, diseases/disorders/conditions)?es)? (choice= Doctor or other health professional"
label(data$tech_parent_info___3)="Where do you get health information (e.g., eating/dieting, exercise, diseases/disorders/conditions)?es)? (choice= Health app or website"
label(data$tech_parent_info___4)="Where do you get health information (e.g., eating/dieting, exercise, diseases/disorders/conditions)?es)? (choice=General or personal website (e.g., blog, Pinterest, social media such as Facebook or Twitter)"
label(data$tech_parent_info___5)="Where do you get health information (e.g., eating/dieting, exercise, diseases/disorders/conditions)?es)? (choice=Health-related printed material (e.g., book, health magazine)"
label(data$tech_parent_info___6)="Where do you get health information (e.g., eating/dieting, exercise, diseases/disorders/conditions)?es)? (choice=General printed material (e.g., magazine, newspaper)"
label(data$tech_parent_info___7)="Where do you get health information (e.g., eating/dieting, exercise, diseases/disorders/conditions)?es)? (choice= Television (news, afternoon program, talk show)"
label(data$tech_parent_info___8)="Where do you get health information (e.g., eating/dieting, exercise, diseases/disorders/conditions)?"
label(data$tech_kid_par_device)="Does your youth have a smart phone or tablet? (e.g. iPhone/iPad, Samsung Galaxy, etc)?"
label(data$tech_kid_par_brand___1)="What brand of smart phone or tablet does your youth have? (Select all that apply)  (choice=iPhone or iPadiPhone o iPad )"
label(data$tech_kid_par_brand___2)="What brand of smart phone or tablet does your youth have? (Select all that apply)  (choice=Samsung)"
label(data$tech_kid_par_brand___3)="What brand of smart phone or tablet does your youth have? (Select all that apply)  (choice=LG)"
label(data$tech_kid_par_brand___4)="What brand of smart phone or tablet does your youth have? (Select all that apply)  (choice=HTC)"
label(data$tech_kid_par_brand___5)="What brand of smart phone or tablet does your youth have? (Select all that apply)  (choice=Motorola)"
label(data$tech_kid_par_brand___6)="What brand of smart phone or tablet does your youth have? (Select all that apply)  (choice=OtherOtro)"
label(data$tech_kid_par_brand___7)="What brand of smart phone or tablet does your youth have? (Select all that apply)  (choice=UnsureNo estoy serguro)"
label(data$tech_kid_par_os___1)="What type of smart phone or tablet does your youth have? (Select all that apply)(choice=iPhone or iPad)"
label(data$tech_kid_par_os___2)="What type of smart phone or tablet does your youth have? (Select all that apply)(choice=Android/Google)"
label(data$tech_kid_par_os___3)="What type of smart phone or tablet does your youth have? (Select all that apply)(choice=Windows)"
label(data$tech_kid_par_os___4)="What type of smart phone or tablet does your youth have? (Select all that apply)(choice=Blackberry)"
label(data$tech_kid_par_os___6)="What type of smart phone or tablet does your youth have? (Select all that apply)(choice=OtherOtro)"
label(data$tech_kid_par_os___7)="What type of smart phone or tablet does your youth have? (Select all that apply)(choice=Unsure)"
label(data$tech_kid_par_service)="Does your youths smart phone ever get disconnected (turned off) because the monthly bill has not been paid?"
label(data$tech_kid_par_disconnected)="How many times per year does your youths smart phone get disconnected (turned off) because the monthly bill has not been paid?"
label(data$tech_kid_par_app)="Does your youth use any applications (app) or websites on your smart phone or tablet to help him/her with health (e.g., exercise, eating)?"
label(data$tech_parent_privileges)="How often does your youth lose their technology privileges (e.g., have their smart phone or tablet taken away as punishment)?"
label(data$tech_parent_uses)="If your youth was provided with a tablet, would they use the tablet to help them be healthier?"
label(data$tech_parent_complete)="Complete?"
#label(data$pedsql_parent_timestamp)="Survey Timestamp"
label(data$pedsqlparent_01)="1.Walking more than one block"
label(data$pedsqlparent_02)="2.Running"
label(data$pedsqlparent_03)="3.Participating in sports activity or exercise"
label(data$pedsqlparent_04)="4.Lifting something heavy"
label(data$pedsqlparent_05)="5.Taking a bath or shower by him or herself"
label(data$pedsqlparent_06)="6.Doing chores around the house"
label(data$pedsqlparent_07)="7.Having hurts or aches"
label(data$pedsqlparent_08)="8.Low energy level"
label(data$pedsqlparent_09)="9.Feeling afraid or scared"
label(data$pedsqlparent_10)="10.Feeling sad or blue"
label(data$pedsqlparent_11)="11.Feeling angry"
label(data$pedsqlparent_12)="12.Trouble sleeping"
label(data$pedsqlparent_13)="13.Worrying about what will happen to him or her"
label(data$pedsqlparent_14)="14.Getting along with other kids"
label(data$pedsqlparent_15)="Other kids not wanting to be his or her friend"
label(data$pedsqlparent_16)="16.Getting teased by other teens"
label(data$pedsqlparent_17)="17.Not able to do things that other kids his or her age can do"
label(data$pedsqlparent_18)="18.Keeping up with other kids"
label(data$pedsqlparent_19)="19.Paying attention in class"
label(data$pedsqlparent_20)="20.Forgetting things"
label(data$pedsqlparent_21)="21.Keeping up with schoolwork"
label(data$pedsqlparent_22)="22.Missing school because of not feeling well"
label(data$pedsqlparent_23)="23.Missing school to go to the doctor or hospital"
label(data$pedsql_parent_complete)="Complete?"
#label(data$physical_activity_nutrition_parent_timestamp)="Survey Timestamp"
label(data$act_nutri_parent01)="Yesterday, was your child physically active for a total of at least 60 minutes? (Add up all the time he/she spent in any kind of physical activity that increased their heart rate and made them breathe hard some of the time.)"
label(data$act_nutri_parent02)="During the past 7 days, on how many days was your child physically active for a total of at least 60 minutes per day? (Add up all the time he/she spent in any kind of physical activity that increased their heart rate and made them breathe hard some of the time.)"
label(data$act_nutri_parent03)="On how many of the past 7 days did your child exercise or participate in physical activity for at least 20 minutes that made him/her sweat and breathe hard, such as basketball, soccer, running, swimming laps, fast bicycling, fast dancing, or similar aerobic activities?"
label(data$act_nutri_parent04)="On how many of the past 7 days did your child do exercises to strengthen or tone their muscles, such as push-ups, sit-ups, or weight lifting?"
label(data$act_nutri_parent05)="On an average school day, how many hours does your child play video or computer games or use a computer for something that is not school work? (Include activities such as Nintendo, Game Boy, PlayStation, Xbox, computer games, and the Internet.)"
label(data$act_nutri_parent06)="On an average school day, how many hours does your child spend watching DVDs or videos? Include DVDs or videos you watch on a TV, computer, iPod, or other portable device."
label(data$act_nutri_parent07)="On an average school day, how many hours does your child watch TV?"
label(data$act_nutri_parent08)="In an average week when your child is in school, on how many days does he/she go to physical education (PE) classes?"
label(data$act_nutri_parent09)="How many TVs are in your home? (If you sleep in more than one home, answer based on the home you sleep in most.)"
label(data$act_nutri_parent10)="Does your child have a TV in his/her bedroom? (If they have more than one bedroom, answer based on the bedroom they sleep in most.)"
label(data$act_nutri_parent11)=" In an average week when your child is in school, on how many days does he/she walk or ride his/her bike to school when weather allows him/her to do so?"
label(data$act_nutri_parent12)="Encourage your child to do physical activities or play sports?"
label(data$act_nutri_parent13)="Do a physical activity or play sports with your child?"
label(data$act_nutri_parent14)="Provide transportation to a place where your child can do physical activities or play sports?"
label(data$act_nutri_parent15)="Watch your child participate in physical activities or play sports"
label(data$act_nutri_parent16)="During the past 7 days, how many times did your child eat fruit? (Do not count fruit juice.)"
label(data$act_nutri_parent17)="During the past 7 days, how many times did your child eat green salad?"
label(data$act_nutri_parent18)="During the past 7 days, how many times did your child eat French fries or other fried potatoes, such as home fries, hash browns or tater tots? (Do not count potato chips.)"
label(data$act_nutri_parent19)="During the past 7 days, how many times did your child eat carrots?"
label(data$act_nutri_parent20)="During the past 7 days, how many times did your child eat other vegetables? (Do not count green salad, potatoes, or carrots.)"
label(data$act_nutri_parent21)="During the past 7 days, how many times did your child eat pizza?"
label(data$act_nutri_parent22)="During the past 7 days, how many times did your child drink a can, bottle, or glass of soda or pop, such as Coke, Pepsi, or Sprite?"
label(data$act_nutri_parent23)="During the past 7 days, how many times did your child drink a can, bottle, or glass of diet soda or pop, such as Diet Coke, Diet Pepsi, or Sprite Zero?"
label(data$act_nutri_parent24)="During the past 7 days, how many times did your child drink a can, bottle, or glass of a sugar-sweetened beverage such as lemonade, sweetened tea or coffee drinks, flavored milk, Snapple, or Sunny Delight? (Do not count soda or pop, sports drinks, energy drinks, or 100% fruit juice.)"
label(data$act_nutri_parent25)="During the past 7 days, how many times did your child drink a bottle or glass of plain water? Count tap, bottled, and unflavored sparkling water."
label(data$act_nutri_parent26)="About how many cups of fruit (including frozen, canned, and dried fruit and 100% fruit juice) does your child eat or drink each day?"
label(data$act_nutri_parent27)="About how many cups of vegetables (including frozen, canned, and vegetables and 100% vegetable juice) does your child eat or drink each day?"
label(data$act_nutri_parent28)="During the past 7 days, on how many days did your child eat breakfast or a morning meal?"
label(data$act_nutri_parent29)="During the last 7 days, when your child eats dinner at home, how often is a television on while he/ she is eating?"
label(data$act_nutri_parent30)="During the past 7 days, on how many days did your child eat at least one meal or snack from a fast food restaurant such as McDonalds, Taco Bell, or KFC?"
label(data$act_nutri_parent31)="How often are there fruits or vegetables to snack on in your home, such as carrots, celery, apples, bananas, or melon?"
label(data$physical_activity_nutrition_parent_complete)="Complete?"
#label(data$asthma_knowledge_parent_timestamp)="Survey Timestamp"
label(data$asthma_parent01___0)="What are the 3 main symptoms of asthma? (choice= sneezing)"
label(data$asthma_parent01___1)="What are the 3 main symptoms of asthma? (choice= shortness of breath)"
label(data$asthma_parent01___11)="What are the 3 main symptoms of asthma? (choice= coughing)"
label(data$asthma_parent01___00)="What are the 3 main symptoms of asthma? (choice= skin rash)"
label(data$asthma_parent01___000)="What are the 3 main symptoms of asthma? (choice= fever)"
label(data$asthma_parent01___111)="What are the 3 main symptoms of asthma? (choice= wheezing)"
label(data$asthma_parent01___0000)="What are the 3 main symptoms of asthma? (choice= nausea/vomiting)"
label(data$asthma_parent01___00000)="What are the 3 main symptoms of asthma? (choice= runny nose)"
label(data$asthma_parent01___000000)="What are the 3 main symptoms of asthma? (choice= headache)"
label(data$asthma_parent01___1111)="What are the 3 main symptoms of asthma? (choice= chest tightness)"
label(data$asthma_parent02)=" More than 1 in 10 children will have asthma at some time during their childhood."
label(data$asthma_parent03)="Children with asthma have overly sensitive air passages in their lungs."
label(data$asthma_parent04)="If one child in a family has asthma, then all his/her brothers and sisters are almost certain to have asthma."
label(data$asthma_parent05)=" 5. Most children with asthma have an increase in mucus when they drink cows milk."
label(data$asthma_parent07)="Wheezing from asthma can be caused by muscle tightening in the wall of the air passages in the lungs."
label(data$asthma_parent08)="Wheezing from asthma can be caused by swelling in the lining of the air passages in the lungs."
label(data$asthma_parent09)=" 9. Asthma damages the heart."
label(data$asthma_parent10___0)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Albuterol)"
label(data$asthma_parent10___00)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Ventolin)"
label(data$asthma_parent10___1)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Pulmicort)"
label(data$asthma_parent10___000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Decadron)"
label(data$asthma_parent10___0000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Abilify)"
label(data$asthma_parent10___11)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Montelukast)"
label(data$asthma_parent10___00000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Lexapro)"
label(data$asthma_parent10___000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Benadryl)"
label(data$asthma_parent10___0000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Claritin)"
label(data$asthma_parent10___00000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Amoxicillin)"
label(data$asthma_parent10___111)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Singulair)"
label(data$asthma_parent10___000000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Zoloft)"
label(data$asthma_parent10___1111)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Budesonide)"
label(data$asthma_parent10___0000000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Effexor)"
label(data$asthma_parent10___00000000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Atrovent)"
label(data$asthma_parent10___11111)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Flovent)"
label(data$asthma_parent10___000000000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Metformin)"
label(data$asthma_parent10___0000000000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Zithromax)"
label(data$asthma_parent10___000000000000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Zyrtec)"
label(data$asthma_parent10___0000000000000000)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Prednisone)"
label(data$asthma_parent10___111111)="Select two asthma treatments (medicines) that are taken every day on a regular basis to prevent attacks of asthma from occurring. (choice=Qvar)"
label(data$asthma_parent11___1)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Albuterol)"
label(data$asthma_parent11___11)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Ventolin)"
label(data$asthma_parent11___0)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Pulmicort)"
label(data$asthma_parent11___111)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Decadron)"
label(data$asthma_parent11___00)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Abilify)"
label(data$asthma_parent11___000)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Montelukast)"
label(data$asthma_parent11___0000)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Lexapro)"
label(data$asthma_parent11___00000)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Benadryl)"
label(data$asthma_parent11___000000)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Claritin)"
label(data$asthma_parent11___0000000)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Amoxicillin)"
label(data$asthma_parent11___00000000)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Singulair)"
label(data$asthma_parent11___000000000)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Zoloft)"
label(data$asthma_parent11___0000000000)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Budesonide)"
label(data$asthma_parent11___00000000000)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Effexor)"
label(data$asthma_parent11___1111)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Atrovent)"
label(data$asthma_parent11___000000000000)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Flovent)"
label(data$asthma_parent11___0000000000000)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Metformin)"
label(data$asthma_parent11___00000000000000)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Zithromax)"
label(data$asthma_parent11___000000000000000)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Zyrtec)"
label(data$asthma_parent11___11111)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Prednisone)"
label(data$asthma_parent11___0000000000000000)="What are the three asthma treatments (medicines) that are useful during an attack of asthma?  (choice=Qvar)"
label(data$asthma_parent12)="Antibiotics are an important part of treatment for most children with asthma."
label(data$asthma_parent13)="Most children with asthma should not eat dairy products."
label(data$asthma_parent14)=" 14.Allergy injections cure asthma."
label(data$asthma_parent15)="If a child dies from an asthma attack, this usually means that there was no time to start any treatment."
label(data$asthma_parent16)="Children with asthma usually have emotional problems."
label(data$asthma_parent17)="You can catch asthma from another person. "
label(data$asthma_parent18)="Inhaled medications for asthma (for example, Ventolin puffers, Rotacaps) have fewer side effects than tablets."
label(data$asthma_parent19)="Short courses of oral steroids (such as prednisone) usually cause significant side effects."
label(data$asthma_parent20)="Some asthma treatments (such as Ventolin) damage the heart."
label(data$asthma_parent22)="During an attack of asthma that you are managing at home, your child is requesting the nebulizer (mask) every 2 hours. He/she is gaining benefit but is very breathless after 2 hours. Provided that he/she doesnt get any worse, its fine to continue with 2-hourly treatments."
label(data$asthma_parent24)="Children with asthma become addicted to their asthma drugs."
label(data$asthma_parent25)="Swimming is the only good exercise for children with asthma."
label(data$asthma_parent26)="A parents smoking in the home may make the childs asthma worse."
label(data$asthma_parent27)="With the right treatment most children with asthma live a normal life with no restriction on activity."
label(data$asthma_parent28)="The best way to measure how bad a childs asthma is is for the doctor to listen to his/her chest."
label(data$asthma_parent29)="Asthma symptoms usually occur more frequently at night than during the day."
label(data$asthma_parent30)="Most children with asthma will have stunted growth."
label(data$asthma_parent31)="Children who frequently have asthma symptoms should have preventative drugs."
label(data$asthma_knowledge_parent_complete)="Complete?"
#label(data$usherwood_timestamp)="Survey Timestamp"
label(data$usherwood_01)="Your child has been wheezy during the day"
label(data$usherwood_02)="Your child has coughed during the day"
label(data$usherwood_03)="Your child has complained of being short of breath"
label(data$usherwood_04)="Your child has complained of a pain in the chest"
label(data$usherwood_05)="Exertion (e.g., running) has made your child breathless"
label(data$usherwood_06)="Your child has stayed indoors because of wheezing or coughing"
label(data$usherwood_07)="His/her asthma has stopped your child from playing with his or her friends"
label(data$usherwood_08)="During term time, your childs education has suffered due to his or her asthma"
label(data$usherwood_09)="Asthma has stopped your child from doing all the things that a boy or girl should at his or her age"
label(data$usherwood_10)="Your childs asthma has interfered with his or her life"
label(data$usherwood_11)="Asthma has limited your childs activities"
label(data$usherwood_12)="Taking his or her inhaler or other treatment has interrupted your childs life"
label(data$usherwood_13)="Your childs asthma has limited your activities"
label(data$usherwood_14)="You have had to make adjustments to family life because of your childs asthma"
label(data$usherwood_15)="Your child has coughed at night"
label(data$usherwood_16)="Your childs sleep has been disturbed by wheezing or coughing"
label(data$usherwood_17)="Your child has been woken up by wheezing or coughing"
label(data$usherwood_complete)="Complete?"
#label(data$equipment_signout_timestamp)="Survey Timestamp"
label(data$tablet_group)="Were you randomized to the tablet group?"
label(data$equipment_signout_complete)="Complete?"
#label(data$gift_receipt_timestamp)="Survey Timestamp"
label(data$gift_receipt_complete)="Complete?"