#!/bin/bash
#BSUB -L /bin/bash
#BSUB -J DF_980_3_GFP_tdt_align
#BSUB -q normal
#BSUB -o DF_980_3_GFP_tdt_align_%J.out
#BSUB -e DF_980_3_GFP_tdt_align_%J.screen
#BSUB -M 36000
#BSUB -n 12
cd /projects/RNASeq/Lung_AT2/DF_980_3_GFP_tdt/star_out
echo "Junction Spanning Reads: " $(bamtools filter -in DF_980_3_GFP_tdt_accepted_hits.sorted.bam -script /projects/RNASeq/Lung_AT2/DF_980_3_GFP_tdt/cigarN.script | bamtools count ) >> DF_980_3_GFP_tdt_accepted_hits.sorted.bamstats 
java -Xmx2g -jar /opt/software/picard-2.22.0//picard.jar CollectInsertSizeMetrics VALIDATION_STRINGENCY=LENIENT HISTOGRAM_FILE=DF_980_3_GFP_tdt_InsertSizeHist.pdf INPUT=DF_980_3_GFP_tdt_accepted_hits.sorted.bam OUTPUT=DF_980_3_GFP_tdt_InsertSizeMetrics
mkdir /projects/RNASeq/Lung_AT2/DF_980_3_GFP_tdt/htseq_out/
samtools view DF_980_3_GFP_tdt_accepted_hits.sorted.bam | htseq-count -r pos --stranded=no - /projects/Reference/mm10/UCSC_mm10_genes.ERCC.gtf > /projects/RNASeq/Lung_AT2/DF_980_3_GFP_tdt/htseq_out/DF_980_3_GFP_tdt_counts.txt

