#!/bin/bash
#BSUB -L /bin/bash
#BSUB -J DF_927_1_GFP_tdt_align
#BSUB -q normal
#BSUB -o DF_927_1_GFP_tdt_align_%J.out
#BSUB -e DF_927_1_GFP_tdt_align_%J.screen
#BSUB -M 36000
#BSUB -n 12
cd /projects/RNASeq/Lung_AT2/DF_927_1_GFP_tdt/
fastqc -o /projects/RNASeq/Lung_AT2/DF_927_1_GFP_tdt/ --extract /projects/RNASeq/Lung_AT2/00_fastq/927-1-GFP-TdT_R1_001.fastq.gz /projects/RNASeq/Lung_AT2/00_fastq/927-1-GFP-TdT_R2_001.fastq.gz
cd /projects/RNASeq/Lung_AT2/DF_927_1_GFP_tdt/; mv /projects/RNASeq/Lung_AT2/DF_927_1_GFP_tdt/927-1-GFP-TdT_R1_001_fastqc DF_927_1_GFP_tdt_R1_Trimmed_fastqc
zip -rm /projects/RNASeq/Lung_AT2/DF_927_1_GFP_tdt/DF_927_1_GFP_tdt_R1_Trimmed_fastqc.zip DF_927_1_GFP_tdt_R1_Trimmed_fastqc
cd /projects/RNASeq/Lung_AT2/DF_927_1_GFP_tdt/; mv /projects/RNASeq/Lung_AT2/DF_927_1_GFP_tdt/927-1-GFP-TdT_R2_001_fastqc DF_927_1_GFP_tdt_R2_Trimmed_fastqc
zip -rm /projects/RNASeq/Lung_AT2/DF_927_1_GFP_tdt/DF_927_1_GFP_tdt_R2_Trimmed_fastqc.zip DF_927_1_GFP_tdt_R2_Trimmed_fastqc
zcat /projects/RNASeq/Lung_AT2/00_fastq/927-1-GFP-TdT_R1_001.fastq.gz | awk '((NR-2)%4==0){read=$1;total++;count[read]++}END{for(read in count){if(count[read]==1){unique++}};print total,unique,unique*100/total}' > /projects/RNASeq/Lung_AT2/DF_927_1_GFP_tdt/DF_927_1_GFP_tdt_ReadCount
zcat /projects/RNASeq/Lung_AT2/00_fastq/927-1-GFP-TdT_R2_001.fastq.gz | awk '((NR-2)%4==0){read=$1;total++;count[read]++}END{for(read in count){if(count[read]==1){unique++}};print total,unique,unique*100/total}' >> /projects/RNASeq/Lung_AT2/DF_927_1_GFP_tdt/DF_927_1_GFP_tdt_ReadCount
mkdir /projects/RNASeq/Lung_AT2/DF_927_1_GFP_tdt/star_out
cd /projects/RNASeq/Lung_AT2/DF_927_1_GFP_tdt/star_out
STAR --genomeDir /projects/Reference/mm10/STAR_index_2.7.6a --runThreadN 12 --outReadsUnmapped Fastx --outMultimapperOrder Random --outSAMmultNmax 1 --outFilterIntronMotifs RemoveNoncanonical --outSAMstrandField intronMotif --outSAMtype BAM SortedByCoordinate --readFilesIn /projects/RNASeq/Lung_AT2/00_fastq/927-1-GFP-TdT_R1_001.fastq.gz /projects/RNASeq/Lung_AT2/00_fastq/927-1-GFP-TdT_R2_001.fastq.gz --readFilesCommand zcat
samtools sort Aligned.sortedByCoord.out.bam -@12 -T DF_927_1_GFP_tdt.tmp -o DF_927_1_GFP_tdt_accepted_hits.sorted.bam
samtools index -@12 DF_927_1_GFP_tdt_accepted_hits.sorted.bam
samtools idxstats DF_927_1_GFP_tdt_accepted_hits.sorted.bam > DF_927_1_GFP_tdt_accepted_hits.sorted.stats
bamtools stats -in DF_927_1_GFP_tdt_accepted_hits.sorted.bam > DF_927_1_GFP_tdt_accepted_hits.sorted.bamstats
rm Aligned.sortedByCoord.out.bam
java -Xmx2g -jar /opt/software/picard-2.22.0//picard.jar CollectRnaSeqMetrics REF_FLAT=/projects/Reference/mm10/refFlat_UCSC.txt STRAND_SPECIFICITY=NONE VALIDATION_STRINGENCY=LENIENT INPUT=DF_927_1_GFP_tdt_accepted_hits.sorted.bam OUTPUT=DF_927_1_GFP_tdt_RNASeqMetrics
echo "Junction Spanning Reads: " $(bamtools filter -in DF_927_1_GFP_tdt_accepted_hits.sorted.bam -script /projects/RNASeq/Lung_AT2/DF_927_1_GFP_tdt/cigarN.script | bamtools count ) >> DF_927_1_GFP_tdt_accepted_hits.sorted.bamstats 
java -Xmx2g -jar /opt/software/picard-2.22.0//picard.jar CollectInsertSizeMetrics VALIDATION_STRINGENCY=LENIENT HISTOGRAM_FILE=DF_927_1_GFP_tdt_InsertSizeHist.pdf INPUT=DF_927_1_GFP_tdt_accepted_hits.sorted.bam OUTPUT=DF_927_1_GFP_tdt_InsertSizeMetrics
mkdir /projects/RNASeq/Lung_AT2/DF_927_1_GFP_tdt/htseq_out/
samtools view DF_927_1_GFP_tdt_accepted_hits.sorted.bam | htseq-count -r pos --stranded=no - /projects/Reference/mm10/UCSC_mm10_genes.ERCC.gtf > /projects/RNASeq/Lung_AT2/DF_927_1_GFP_tdt/htseq_out/DF_927_1_GFP_tdt_counts.txt

